//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIResponder.h"

#import "QQApiInterfaceDelegate.h"
#import "TencentSessionDelegate.h"
#import "UIApplicationDelegate.h"
#import "UNUserNotificationCenterDelegate.h"
#import "WXApiDelegate.h"
#import "WeiboSDKDelegate.h"

@class AVAudioPlayer, AVAudioSession, NSString, TencentOAuth, UIWindow;

@interface AppDelegate : UIResponder <WXApiDelegate, UNUserNotificationCenterDelegate, QQApiInterfaceDelegate, WeiboSDKDelegate, TencentSessionDelegate, UIApplicationDelegate>
{
    AVAudioSession *session;
    AVAudioPlayer *_player;
    _Bool _allowRotation;
    UIWindow *_window;
    id <WXDelegate> _wxDelegate;
    id <WeiBoDelegate> _weiboDelegate;
    id <QQShareDelegate> _qqDelegate;
    TencentOAuth *_tencentOAuth;
}

@property(retain, nonatomic) TencentOAuth *tencentOAuth; // @synthesize tencentOAuth=_tencentOAuth;
@property(nonatomic) __weak id <QQShareDelegate> qqDelegate; // @synthesize qqDelegate=_qqDelegate;
@property(nonatomic) __weak id <WeiBoDelegate> weiboDelegate; // @synthesize weiboDelegate=_weiboDelegate;
@property(nonatomic) __weak id <WXDelegate> wxDelegate; // @synthesize wxDelegate=_wxDelegate;
@property(retain, nonatomic) UIWindow *window; // @synthesize window=_window;
@property(nonatomic) _Bool allowRotation; // @synthesize allowRotation=_allowRotation;
- (void).cxx_destruct;
- (void)application:(id)arg1 didReceiveRemoteNotification:(id)arg2;
- (void)userNotificationCenter:(id)arg1 didReceiveNotificationResponse:(id)arg2 withCompletionHandler:(CDUnknownBlockType)arg3;
- (void)userNotificationCenter:(id)arg1 willPresentNotification:(id)arg2 withCompletionHandler:(CDUnknownBlockType)arg3;
- (void)registerUm:(id)arg1;
- (void)onResp:(id)arg1;
- (void)onReq:(id)arg1;
- (void)setUpFixiOS11;
- (void)applicationDidReceiveMemoryWarning:(id)arg1;
- (unsigned long long)application:(id)arg1 supportedInterfaceOrientationsForWindow:(id)arg2;
- (void)applicationWillTerminate:(id)arg1;
- (void)applicationDidBecomeActive:(id)arg1;
- (void)applicationWillEnterForeground:(id)arg1;
- (void)m3u8AllTaskFinish;
- (void)applicationDidEnterBackground:(id)arg1;
- (void)applicationWillResignActive:(id)arg1;
- (void)didReceiveWeiboResponse:(id)arg1;
- (void)didReceiveWeiboRequest:(id)arg1;
- (_Bool)application:(id)arg1 continueUserActivity:(id)arg2 restorationHandler:(CDUnknownBlockType)arg3;
- (void)getWakeUpParams:(id)arg1;
- (_Bool)application:(id)arg1 shouldAllowExtensionPointIdentifier:(id)arg2;
- (_Bool)application:(id)arg1 openURL:(id)arg2 options:(id)arg3;
- (void)playbackgroud;
- (_Bool)application:(id)arg1 didFinishLaunchingWithOptions:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

