//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class BarrageDispatcher, BarrageSprite;

@protocol BarrageDispatcherDelegate <NSObject>
- (void)willDeactiveSprite:(BarrageSprite *)arg1;
- (void)willActiveSprite:(BarrageSprite *)arg1;

@optional
- (double)timeForBarrageDispatcher:(BarrageDispatcher *)arg1;
- (_Bool)shouldActiveSprite:(BarrageSprite *)arg1;
@end

