//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface BarrageLoader : NSObject
{
}

+ (void)writeDescriptors:(id)arg1 toFile:(id)arg2 additional:(_Bool)arg3;
+ (id)readDescriptorsWithDamakuFile:(id)arg1;
+ (id)readDescriptorsWithFile:(id)arg1;

@end

