//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray;

@interface BarrageSpriteQueue : NSObject
{
    NSMutableArray *_sprites;
}

@property(readonly, nonatomic) NSMutableArray *sprites; // @synthesize sprites=_sprites;
- (void).cxx_destruct;
- (long long)indexForSprite:(id)arg1;
- (long long)indexForSpriteDelay:(double)arg1;
- (id)spriteQueueWithDelayGreaterThan:(double)arg1 equal:(_Bool)arg2;
- (id)spriteQueueWithDelayGreaterThan:(double)arg1;
- (id)spriteQueueWithDelayGreaterThanOrEqualTo:(double)arg1;
- (id)spriteQueueWithDelayLessThan:(double)arg1 equal:(_Bool)arg2;
- (id)spriteQueueWithDelayLessThan:(double)arg1;
- (id)spriteQueueWithDelayLessThanOrEqualTo:(double)arg1;
- (void)removeSprites:(id)arg1;
- (void)removeSprite:(id)arg1;
- (id)descendingSprites;
- (id)ascendingSprites;
- (void)addSprite:(id)arg1;
- (id)initWithAscendingSprites:(id)arg1;
- (id)init;

@end

