//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class BarrageRenderer, NSDictionary;

@protocol BarrageRendererDelegate <NSObject>

@optional
- (void)barrageRenderer:(BarrageRenderer *)arg1 spriteStage:(long long)arg2 spriteParams:(NSDictionary *)arg3;
- (double)timeForBarrageRenderer:(BarrageRenderer *)arg1;
@end

