//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CLUPnPAVPositionInfo, CLUPnPTransportInfo, NSString;

@protocol CLUPnPResponseDelegate <NSObject>
- (void)upnpGetTransportInfoResponse:(CLUPnPTransportInfo *)arg1;
- (void)upnpSetAVTransportURIResponse;

@optional
- (void)upnpGetPositionInfoResponse:(CLUPnPAVPositionInfo *)arg1;
- (void)upnpGetVolumeResponse:(NSString *)arg1;
- (void)upnpSetNextAVTransportURIResponse;
- (void)upnpSetVolumeResponse;
- (void)upnpNextResponse;
- (void)upnpPreviousResponse;
- (void)upnpSeekResponse;
- (void)upnpStopResponse;
- (void)upnpPauseResponse;
- (void)upnpPlayResponse;
- (void)upnpUndefinedResponse:(NSString *)arg1 postXML:(NSString *)arg2;
@end

