//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CLServiceModel, NSString, NSURL;

@interface CLUPnPDevice : NSObject
{
    NSString *_uuid;
    NSURL *_loaction;
    NSString *_URLHeader;
    NSString *_friendlyName;
    NSString *_modelName;
    CLServiceModel *_AVTransport;
    CLServiceModel *_RenderingControl;
}

@property(retain, nonatomic) CLServiceModel *RenderingControl; // @synthesize RenderingControl=_RenderingControl;
@property(retain, nonatomic) CLServiceModel *AVTransport; // @synthesize AVTransport=_AVTransport;
@property(copy, nonatomic) NSString *modelName; // @synthesize modelName=_modelName;
@property(copy, nonatomic) NSString *friendlyName; // @synthesize friendlyName=_friendlyName;
@property(copy, nonatomic) NSString *URLHeader; // @synthesize URLHeader=_URLHeader;
@property(retain, nonatomic) NSURL *loaction; // @synthesize loaction=_loaction;
@property(copy, nonatomic) NSString *uuid; // @synthesize uuid=_uuid;
- (void).cxx_destruct;
- (id)description;
- (void)setArray:(id)arg1;

@end

