//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface CountryModel : NSObject
{
    NSString *_code;
    NSString *_name;
    NSString *_length;
}

+ (id)modelWithStr:(id)arg1;
@property(copy, nonatomic) NSString *length; // @synthesize length=_length;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
@property(copy, nonatomic) NSString *code; // @synthesize code=_code;
- (void).cxx_destruct;
- (id)description;

@end

