//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "UIGestureRecognizerDelegate.h"

@class NSMutableArray, NSString;

@interface CoverViewer : UIView <UIGestureRecognizerDelegate>
{
    NSMutableArray *_displayViews;
    NSMutableArray *_cacheViews;
    struct CVRange _displayRange;
    long long _totalItems;
    struct CGPoint _oldTrans;
    id <CoverViewerDelegate> _delegate;
    double _leftLimit;
    double _rightLimit;
    double _contentOffset;
}

@property(nonatomic) double contentOffset; // @synthesize contentOffset=_contentOffset;
@property(nonatomic) double rightLimit; // @synthesize rightLimit=_rightLimit;
@property(nonatomic) double leftLimit; // @synthesize leftLimit=_leftLimit;
@property(nonatomic) __weak id <CoverViewerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)setContentOffset:(double)arg1 animated:(_Bool)arg2;
- (void)dragEnd:(struct CGPoint)arg1;
- (id)dequeueItemView;
- (void)processView:(id)arg1 atIndex:(long long)arg2;
- (void)updateScrolling;
- (void)onPan:(id)arg1;
- (double)percentForItemIndex:(long long)arg1;
- (_Bool)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
- (_Bool)gestureRecognizerShouldBegin:(id)arg1;
- (void)reloadDatas;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

