//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"
#import "NSCopying.h"

@class Device, NSArray, NSString;

@interface DeviceDescription : NSObject <NSCopying, NSCoding>
{
    NSString *_deviceType;
    NSString *_friendlyName;
    NSString *_manufacturer;
    NSString *_manufacturerURL;
    NSString *_modelDescription;
    NSString *_modelName;
    NSString *_udn;
    NSArray *_services;
    NSArray *_devices;
    Device *_device;
}

@property(nonatomic) __weak Device *device; // @synthesize device=_device;
@property(copy, nonatomic) NSArray *devices; // @synthesize devices=_devices;
@property(copy, nonatomic) NSArray *services; // @synthesize services=_services;
@property(copy, nonatomic) NSString *udn; // @synthesize udn=_udn;
@property(copy, nonatomic) NSString *modelName; // @synthesize modelName=_modelName;
@property(copy, nonatomic) NSString *modelDescription; // @synthesize modelDescription=_modelDescription;
@property(copy, nonatomic) NSString *manufacturerURL; // @synthesize manufacturerURL=_manufacturerURL;
@property(copy, nonatomic) NSString *manufacturer; // @synthesize manufacturer=_manufacturer;
@property(copy, nonatomic) NSString *friendlyName; // @synthesize friendlyName=_friendlyName;
@property(copy, nonatomic) NSString *deviceType; // @synthesize deviceType=_deviceType;
- (void).cxx_destruct;
- (void)setValue:(id)arg1 forUndefinedKey:(id)arg2;
- (id)description;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithDictionary:(id)arg1;

@end

