//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSString;

@interface FeedBackMsgModel : NSObject
{
    NSString *_content;
    NSString *_replyContent;
    NSString *_submitTime;
    NSString *_replyTime;
    NSString *_state;
    NSString *_title;
    NSArray *_submitTypeList;
}

+ (id)mj_objectClassInArray;
@property(retain, nonatomic) NSArray *submitTypeList; // @synthesize submitTypeList=_submitTypeList;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
@property(retain, nonatomic) NSString *state; // @synthesize state=_state;
@property(retain, nonatomic) NSString *replyTime; // @synthesize replyTime=_replyTime;
@property(retain, nonatomic) NSString *submitTime; // @synthesize submitTime=_submitTime;
@property(retain, nonatomic) NSString *replyContent; // @synthesize replyContent=_replyContent;
@property(retain, nonatomic) NSString *content; // @synthesize content=_content;
- (void).cxx_destruct;

@end

