//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSOperationQueue.h"

@class FlurryActor;

@interface FlurryActorOperationQueue : NSOperationQueue
{
    FlurryActor *_owner;
}

+ (void)initialize;
@property(retain, nonatomic) FlurryActor *owner; // @synthesize owner=_owner;
- (void).cxx_destruct;
- (void)addOperations:(id)arg1 waitUntilFinished:(_Bool)arg2;
- (void)addOperation:(id)arg1;
- (id)initWithActor:(id)arg1;

@end

