//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "FlurryURLSessionTaskDelegate.h"

@class NSDictionary, NSMutableArray, NSString;

@interface FlurryPulseRequest : NSObject <FlurryURLSessionTaskDelegate>
{
    struct avro_obj_t *_pulseRequestSchema;
    struct avro_obj_t *_deviceTagsSchema;
    struct avro_obj_t *_iosTagsSchema;
    struct avro_obj_t *_geoTypeSchema;
    struct avro_obj_t *_geoLocationSchema;
    struct avro_obj_t *_deviceIdTypeSchema;
    struct avro_obj_t *_pulseRequest;
    NSDictionary *params;
    NSMutableArray *runningTasks;
}

+ (void)synchronizedPulseAccessWithCallback_sync:(CDUnknownBlockType)arg1;
+ (void)synchronizedPulseAccessWithCallback_async:(CDUnknownBlockType)arg1;
+ (id)accessQueue;
+ (id)sharedInstance;
@property(retain, nonatomic) NSMutableArray *runningTasks; // @synthesize runningTasks;
- (void).cxx_destruct;
- (void)flurryUrlRequestDidSucceed:(id)arg1 withResponse:(id)arg2;
- (void)flurryUrlRequestDidCancel:(id)arg1 withResponse:(id)arg2;
- (void)flurryUrlRequestDidFail:(id)arg1 withResponse:(id)arg2;
- (void)unregisterTask:(id)arg1;
- (void)sendPulseRequestWithParams:(id)arg1;
- (_Bool)buildObjectWithParams:(id)arg1;
- (void)dealloc;
- (void)cleanUp;
- (void)initSchema;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

