//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface FlurryiOSUtil : NSObject
{
}

+ (_Bool)mainThread_isNotificationsSettingsEnabled;
+ (_Bool)isNotificationsSettingsEnabled;
+ (_Bool)isInBackground;
+ (_Bool)isIPad;
+ (id)getIdentifierForVendor;
+ (id)deviceModel;
+ (id)deviceBuild;
+ (id)appVersion;
+ (id)appShortVersion;
+ (long long)userDeviceIdiom;
+ (unsigned short)agentPlatform;
+ (long long)getStatusBarOrientation;
+ (_Bool)canvasInLandscapeLeft;
+ (_Bool)canvasInLandscapeRight;
+ (_Bool)canvasInLandscape;

@end

