//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"
#import "NSCopying.h"

@class NSArray, NSString;

@interface FlurryPulseEventTrigger : NSObject <NSCoding, NSCopying>
{
    NSString *_eventName;
    NSString *_eventParamName;
    NSArray *_eventParamValues;
}

@property(retain, nonatomic) NSArray *eventParamValues; // @synthesize eventParamValues=_eventParamValues;
@property(retain, nonatomic) NSString *eventParamName; // @synthesize eventParamName=_eventParamName;
@property(retain, nonatomic) NSString *eventName; // @synthesize eventName=_eventName;
- (void).cxx_destruct;
- (_Bool)isEqual:(id)arg1;
- (unsigned long long)hash;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)dataDictionary;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithDictionary:(id)arg1;
- (id)initWithCoder:(id)arg1;

@end

