//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FlurryStreamEntityBase.h"

@class FlurryTransaction, NSDate, NSDictionary, NSNumber, NSString;

@interface FlurryStreamEvent : FlurryStreamEntityBase
{
    _Bool _timed;
    int _frameType;
    NSNumber *_eventLogId;
    NSString *_name;
    NSDate *_started;
    NSDate *_ended;
    NSDictionary *_parameters;
    FlurryTransaction *_transaction;
}

+ (id)streamEntityFromJSONData:(id)arg1;
+ (id)streamEventWithName:(id)arg1 timed:(_Bool)arg2 isStart:(_Bool)arg3 parameters:(id)arg4 transaction:(id)arg5;
@property(retain, nonatomic) FlurryTransaction *transaction; // @synthesize transaction=_transaction;
@property(retain, nonatomic) NSDictionary *parameters; // @synthesize parameters=_parameters;
@property(nonatomic) _Bool timed; // @synthesize timed=_timed;
@property(retain, nonatomic) NSDate *ended; // @synthesize ended=_ended;
@property(retain, nonatomic) NSDate *started; // @synthesize started=_started;
@property(retain, nonatomic) NSString *name; // @synthesize name=_name;
@property(retain, nonatomic) NSNumber *eventLogId; // @synthesize eventLogId=_eventLogId;
- (void)setFrameType:(int)arg1;
- (int)frameType;
- (void).cxx_destruct;
- (id)dictionaryRepresentation;
- (void)setID;
- (id)initWithName:(id)arg1 timed:(_Bool)arg2 isStart:(_Bool)arg3 parameters:(id)arg4 transaction:(id)arg5;

@end

