//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class NSDate;

@protocol FlurryLocationUtilObserver
- (void)setLatitude:(double)arg1 longitude:(double)arg2 horizontalAccuracy:(float)arg3 verticalAccuracy:(float)arg4 altitude:(double)arg5 bearing:(float)arg6 speed:(float)arg7 timestamp:(NSDate *)arg8;
@end

