//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class FlurryPLCrashReporter, NSDate, NSMutableArray, NSMutableDictionary, NSString;

@interface FlurryGlobalVariableStorage : NSObject
{
    _Bool _isInternal;
    _Bool _udidEnabled;
    _Bool _sessionReportsOnCloseEnabled;
    _Bool _sessionReportsOnPauseEnabled;
    _Bool _backgroundSessionEnabled;
    _Bool _crashReportingEnabled;
    _Bool _countBackgroundSessions;
    _Bool _eventLoggingEnabled;
    _Bool _hasSessionOriginName;
    _Bool _hasDeepLinkName;
    _Bool _startSessionCalled;
    _Bool _optOutSessionPending;
    _Bool _appInstallProcessDone;
    _Bool _pulseMonitoringEnabled;
    _Bool _pulseRequestPending;
    _Bool _implicitIAPReporting;
    _Bool _IAPReportingEnabled;
    short _buildEnvironment;
    int _pauseSecondsBeforeStartingNewSession;
    int _pauseSecondsBeforeStartingNewBackgroundSession;
    int _appApplicationState;
    int _age;
    int _maxBitRateKbps;
    NSString *_apiKey;
    NSDate *_pauseTime;
    NSDate *_lastPageViewDate;
    NSString *_deviceToken;
    NSString *_appVersion;
    NSString *_userID;
    NSString *_gender;
    NSString *_sessionOriginName;
    NSString *_deepLinkName;
    NSMutableDictionary *_sessionParameters;
    NSMutableDictionary *_launchOptions;
    id _location;
    FlurryPLCrashReporter *_flurryCrashReporter;
    NSMutableArray *_originSets;
    NSMutableArray *_pendingUrlTimers;
    NSDate *_lastPulseReportTime;
}

+ (id)getPersistentFilePath:(id)arg1;
+ (id)persistentPulsePrepUrlsFilePath;
+ (id)persistentPulseUrlsFilePath;
+ (id)persistentUrlsFilePath;
+ (id)persistentCookiesFilePath;
+ (id)persistentGlobalsFilePath;
+ (void)cleanup;
+ (id)sharedInstance;
@property(nonatomic) _Bool IAPReportingEnabled; // @synthesize IAPReportingEnabled=_IAPReportingEnabled;
@property short buildEnvironment; // @synthesize buildEnvironment=_buildEnvironment;
@property _Bool implicitIAPReporting; // @synthesize implicitIAPReporting=_implicitIAPReporting;
@property(retain) NSDate *lastPulseReportTime; // @synthesize lastPulseReportTime=_lastPulseReportTime;
@property _Bool pulseRequestPending; // @synthesize pulseRequestPending=_pulseRequestPending;
@property _Bool pulseMonitoringEnabled; // @synthesize pulseMonitoringEnabled=_pulseMonitoringEnabled;
@property(retain) NSMutableArray *pendingUrlTimers; // @synthesize pendingUrlTimers=_pendingUrlTimers;
@property(retain, nonatomic) NSMutableArray *originSets; // @synthesize originSets=_originSets;
@property _Bool optOutSessionPending; // @synthesize optOutSessionPending=_optOutSessionPending;
@property(retain, nonatomic) FlurryPLCrashReporter *flurryCrashReporter; // @synthesize flurryCrashReporter=_flurryCrashReporter;
@property(retain) id location; // @synthesize location=_location;
@property(readonly) NSMutableDictionary *launchOptions; // @synthesize launchOptions=_launchOptions;
@property _Bool startSessionCalled; // @synthesize startSessionCalled=_startSessionCalled;
@property(retain) NSMutableDictionary *sessionParameters; // @synthesize sessionParameters=_sessionParameters;
@property(copy) NSString *deepLinkName; // @synthesize deepLinkName=_deepLinkName;
@property(copy) NSString *sessionOriginName; // @synthesize sessionOriginName=_sessionOriginName;
@property _Bool hasDeepLinkName; // @synthesize hasDeepLinkName=_hasDeepLinkName;
@property _Bool hasSessionOriginName; // @synthesize hasSessionOriginName=_hasSessionOriginName;
@property(copy) NSString *gender; // @synthesize gender=_gender;
@property int age; // @synthesize age=_age;
@property(copy) NSString *userID; // @synthesize userID=_userID;
@property _Bool eventLoggingEnabled; // @synthesize eventLoggingEnabled=_eventLoggingEnabled;
@property(copy) NSString *appVersion; // @synthesize appVersion=_appVersion;
@property _Bool countBackgroundSessions; // @synthesize countBackgroundSessions=_countBackgroundSessions;
@property _Bool crashReportingEnabled; // @synthesize crashReportingEnabled=_crashReportingEnabled;
@property int appApplicationState; // @synthesize appApplicationState=_appApplicationState;
@property _Bool backgroundSessionEnabled; // @synthesize backgroundSessionEnabled=_backgroundSessionEnabled;
@property _Bool sessionReportsOnPauseEnabled; // @synthesize sessionReportsOnPauseEnabled=_sessionReportsOnPauseEnabled;
@property _Bool sessionReportsOnCloseEnabled; // @synthesize sessionReportsOnCloseEnabled=_sessionReportsOnCloseEnabled;
@property(retain) NSDate *lastPageViewDate; // @synthesize lastPageViewDate=_lastPageViewDate;
@property(retain) NSDate *pauseTime; // @synthesize pauseTime=_pauseTime;
@property int pauseSecondsBeforeStartingNewBackgroundSession; // @synthesize pauseSecondsBeforeStartingNewBackgroundSession=_pauseSecondsBeforeStartingNewBackgroundSession;
@property int pauseSecondsBeforeStartingNewSession; // @synthesize pauseSecondsBeforeStartingNewSession=_pauseSecondsBeforeStartingNewSession;
@property _Bool udidEnabled; // @synthesize udidEnabled=_udidEnabled;
@property(copy, nonatomic) NSString *apiKey; // @synthesize apiKey=_apiKey;
@property _Bool isInternal; // @synthesize isInternal=_isInternal;
- (void).cxx_destruct;
- (_Bool)isMoPubIntegration;
@property _Bool lastAdTrackingEnabledSetting; // @dynamic lastAdTrackingEnabledSetting;
- (int)logLevel;
- (_Bool)analyticsEnabled;
- (void)removePendingUrlTimers;
- (void)recordOrigin:(id)arg1 originVersion:(id)arg2 withParameters:(id)arg3;
- (void)recordSessionProperties:(id)arg1;
- (void)savePersistentGlobalsToDisk;
@property int maxBitRateKbps; // @synthesize maxBitRateKbps=_maxBitRateKbps;
@property _Bool appInstallProcessDone; // @synthesize appInstallProcessDone=_appInstallProcessDone;
@property(retain, nonatomic) NSString *guidAsIDForSessionReports;
@property(copy) NSString *deviceToken; // @synthesize deviceToken=_deviceToken;
- (void)resetLaunchOptions;
- (id)init;

@end

