//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IFlurryStreamEntityFactory.h"

@class NSDictionary, NSString;

@interface FlurryStreamEntityFactory : NSObject <IFlurryStreamEntityFactory>
{
    NSDictionary *_typeToClass;
}

+ (id)streamEntityFactoryWithFrameTypeToModelClassDictionary:(id)arg1;
@property(retain, nonatomic) NSDictionary *typeToClass; // @synthesize typeToClass=_typeToClass;
- (void).cxx_destruct;
- (id)streamEntitiesFromMessages:(id)arg1;
- (id)initWithFrameTypeToModelClassDictionary:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

