//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class FlurryActor, NSObject<OS_dispatch_queue>;

@interface FlurryActorDeferredQueue : NSObject
{
    unsigned long long _suspendCount;
    NSObject<OS_dispatch_queue> *_queue;
    FlurryActor *_actor;
}

@property(nonatomic) __weak FlurryActor *actor; // @synthesize actor=_actor;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
@property(nonatomic) unsigned long long suspendCount; // @synthesize suspendCount=_suspendCount;
- (void).cxx_destruct;
- (void)resume;
- (void)suspend;
- (void)asyncBlock:(CDUnknownBlockType)arg1;
- (void)syncBlock:(CDUnknownBlockType)arg1;
- (id)initWithDescription:(id)arg1 actor:(id)arg2;
- (id)init;

@end

