//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FlurryActorStreamComponent.h"

#import "IFlurryStreamBuffer.h"

@class FlurryActorDeferredQueue, NSMutableDictionary, NSString;

@interface FlurryStreamBuffer : FlurryActorStreamComponent <IFlurryStreamBuffer>
{
    NSMutableDictionary *_frameTypeToNextStageComponentsMap;
    FlurryActorDeferredQueue *_deferredQueue;
}

+ (id)streamBuffer;
@property(retain, nonatomic) FlurryActorDeferredQueue *deferredQueue; // @synthesize deferredQueue=_deferredQueue;
@property(retain, nonatomic) NSMutableDictionary *frameTypeToNextStageComponentsMap; // @synthesize frameTypeToNextStageComponentsMap=_frameTypeToNextStageComponentsMap;
- (void).cxx_destruct;
- (void)resume;
- (void)pause;
- (void)sendStreamMessage:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

