//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FlurryActor.h"

#import "IFlurryStreamComponent.h"

@class NSMutableDictionary, NSString;

@interface FlurryActorStreamComponent : FlurryActor <IFlurryStreamComponent>
{
    NSMutableDictionary *_frameTypeToNextStageComponentsMap;
}

@property(retain, nonatomic) NSMutableDictionary *frameTypeToNextStageComponentsMap; // @synthesize frameTypeToNextStageComponentsMap=_frameTypeToNextStageComponentsMap;
- (void).cxx_destruct;
- (void)onqueue_sendStreamMessage:(id)arg1;
- (void)onqueue_registerNextStageComponent:(id)arg1;
- (id)supportedFrameTypes;
- (void)registerNextStageComponent:(id)arg1;
- (void)sendStreamMessage:(id)arg1;
- (id)init;
- (id)initWithDescription:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

