//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSProxy.h"

@class NSObject<WCSessionDelegate>;

@interface FlurryWatchConnectivityProxy : NSProxy
{
    NSObject<WCSessionDelegate> *_realObject;
    id <FlurryWatchConnectivityDelegate> _sdkDelegate;
}

+ (_Bool)respondsToSelector:(SEL)arg1;
@property(nonatomic) __weak id <FlurryWatchConnectivityDelegate> sdkDelegate; // @synthesize sdkDelegate=_sdkDelegate;
@property(nonatomic) __weak NSObject<WCSessionDelegate> *realObject; // @synthesize realObject=_realObject;
- (void).cxx_destruct;
- (void)session:(id)arg1 didFinishUserInfoTransfer:(id)arg2 error:(id)arg3;
- (void)session:(id)arg1 didReceiveUserInfo:(id)arg2;
- (id)description;
- (void)forwardInvocation:(id)arg1;
- (_Bool)respondsToSelector:(SEL)arg1;
- (id)methodSignatureForSelector:(SEL)arg1;
- (id)initWithObject:(id)arg1;

@end

