//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray, NSObject<OS_dispatch_queue>;

@interface FlurryPreCacheEventManager : NSObject
{
    NSMutableArray *_log;
    NSMutableArray *_preCacheEventLog;
    NSObject<OS_dispatch_queue> *_queue;
}

+ (id)sharedInstance;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
@property(retain, nonatomic) NSMutableArray *preCacheEventLog; // @synthesize preCacheEventLog=_preCacheEventLog;
@property(retain) NSMutableArray *log; // @synthesize log=_log;
- (void).cxx_destruct;
- (void)processWriteSyncWithBlock:(CDUnknownBlockType)arg1;
- (id)init;

@end

