//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSData;

@interface FlurryStreamFrame : NSObject
{
    unsigned short _frameType;
    NSData *_payload;
    unsigned long long _timeSinceEpochFrame;
    unsigned long long _crc32;
    unsigned long long _totalLength;
}

@property(nonatomic) unsigned long long totalLength; // @synthesize totalLength=_totalLength;
@property(nonatomic) unsigned long long crc32; // @synthesize crc32=_crc32;
@property(nonatomic) unsigned long long timeSinceEpochFrame; // @synthesize timeSinceEpochFrame=_timeSinceEpochFrame;
@property(retain, nonatomic) NSData *payload; // @synthesize payload=_payload;
@property(nonatomic) unsigned short frameType; // @synthesize frameType=_frameType;
- (void).cxx_destruct;
- (id)description;

@end

