//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface FlurryWatch : NSObject
{
}

+ (void)setServerURL:(id)arg1;
+ (_Bool)flurryUserInfo:(id)arg1;
+ (_Bool)isFlurryUserInfo:(id)arg1;
+ (void)disableWatchConnectivity;
+ (void)logWatchError:(id)arg1 message:(id)arg2 error:(id)arg3;
+ (void)logWatchError:(id)arg1 message:(id)arg2 exception:(id)arg3;
+ (int)logWatchEvent:(id)arg1 withParameters:(id)arg2;
+ (int)logWatchEvent:(id)arg1;
+ (id)apiKey;

@end

