//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IFlurryStreamEntity.h"

@class NSData, NSString;

@interface FlurryStreamEntityBase : NSObject <IFlurryStreamEntity>
{
    int _frameType;
    NSData *_payload;
    double _timeStamp;
}

+ (id)dateFormatter;
+ (id)streamEntityFromJSONData:(id)arg1;
@property(nonatomic) double timeStamp; // @synthesize timeStamp=_timeStamp;
@property(retain, nonatomic) NSData *payload; // @synthesize payload=_payload;
@property(nonatomic) int frameType; // @synthesize frameType=_frameType;
- (void).cxx_destruct;
- (id)dictionaryRepresentation;
- (id)jsonRepresentation;
@property(readonly, copy) NSString *description;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

