//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FlurryActor.h"

@interface FlurryBreadcrumbsActor : FlurryActor
{
}

+ (id)sharedInstance;
- (id)listOfBreadcrumbs;
- (int)openOutputFile;
- (void)addString:(id)arg1;
- (id)initSharedInstance;

@end

