//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSData, NSString;

@interface FlurryTransaction : NSObject
{
    NSString *_transactionId;
    NSString *_originalTransactionId;
    NSString *_productId;
    long long _quanity;
    NSString *_price;
    NSString *_currency;
    NSString *_productName;
    NSData *_receiptData;
    long long _transactionState;
}

+ (id)transactionUsingDictionary:(id)arg1;
+ (id)transactionEventEnumToString:(long long)arg1;
+ (id)transactionResultArrayInstance;
@property(nonatomic) long long transactionState; // @synthesize transactionState=_transactionState;
@property(retain, nonatomic) NSData *receiptData; // @synthesize receiptData=_receiptData;
@property(retain, nonatomic) NSString *productName; // @synthesize productName=_productName;
@property(retain, nonatomic) NSString *currency; // @synthesize currency=_currency;
@property(retain, nonatomic) NSString *price; // @synthesize price=_price;
@property(nonatomic) long long quanity; // @synthesize quanity=_quanity;
@property(retain, nonatomic) NSString *productId; // @synthesize productId=_productId;
@property(retain, nonatomic) NSString *originalTransactionId; // @synthesize originalTransactionId=_originalTransactionId;
@property(retain, nonatomic) NSString *transactionId; // @synthesize transactionId=_transactionId;
- (void).cxx_destruct;
- (id)initUsingDictionary:(id)arg1;
- (id)dictionaryRepresentation;
- (id)description;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;

@end

