//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSString;

@interface FlurryPreCacheEvent : NSObject
{
    _Bool _timed;
    NSString *_eventName;
    NSDictionary *_params;
}

@property(nonatomic) _Bool timed; // @synthesize timed=_timed;
@property(retain, nonatomic) NSDictionary *params; // @synthesize params=_params;
@property(retain, nonatomic) NSString *eventName; // @synthesize eventName=_eventName;
- (void).cxx_destruct;
- (id)initWithEventName:(id)arg1 params:(id)arg2 timed:(_Bool)arg3;

@end

