//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface FlurryFileState : NSObject
{
    NSString *_fileName;
    NSString *_filePath;
    long long _fileUploadRetryCounter;
    long long _fileRemoveRetryCounter;
    id _task;
    unsigned long long _fileState;
}

@property(nonatomic) unsigned long long fileState; // @synthesize fileState=_fileState;
@property(retain, nonatomic) id task; // @synthesize task=_task;
@property(nonatomic) long long fileRemoveRetryCounter; // @synthesize fileRemoveRetryCounter=_fileRemoveRetryCounter;
@property(nonatomic) long long fileUploadRetryCounter; // @synthesize fileUploadRetryCounter=_fileUploadRetryCounter;
@property(copy, nonatomic) NSString *filePath; // @synthesize filePath=_filePath;
@property(copy, nonatomic) NSString *fileName; // @synthesize fileName=_fileName;
- (void).cxx_destruct;
- (id)initWithFileName:(id)arg1 withFilePath:(id)arg2 withFileState:(unsigned long long)arg3 withFileUploadRetryCounter:(long long)arg4 withFileRemoveRetryCounter:(long long)arg5 withNetworkTask:(id)arg6;
- (id)init;

@end

