//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSData, NSDictionary, NSError;

@interface FlurryHTTPURLResponse : NSObject
{
    NSData *_body;
    long long _statusCode;
    NSDictionary *_headers;
    NSError *_error;
}

@property(retain, nonatomic) NSError *error; // @synthesize error=_error;
@property(retain, nonatomic) NSDictionary *headers; // @synthesize headers=_headers;
@property(nonatomic) long long statusCode; // @synthesize statusCode=_statusCode;
@property(retain, nonatomic) NSData *body; // @synthesize body=_body;
- (void).cxx_destruct;
- (_Bool)isSuccess;
- (id)description;
- (id)initWithBody:(id)arg1 statusCode:(long long)arg2 headers:(id)arg3 error:(id)arg4;
- (id)initWithResponse:(id)arg1 body:(id)arg2 error:(id)arg3;

@end

