//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSMutableArray;

@interface GCallback : NSObject
{
    NSMutableArray *_targets;
}

- (void).cxx_destruct;
- (void)clean;
- (void)invoke;
- (void)addBlock:(CDUnknownBlockType)arg1;
- (void)addTarget:(id)arg1 action:(SEL)arg2 with:(id)arg3;
@property(readonly, nonatomic) NSArray *targets;
- (id)init;

@end

