//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface GetTransportInfoResponse : NSObject
{
    NSString *_currentSpeed;
    long long _currentTransportState;
    NSString *_currentTransportStatus;
}

@property(copy, nonatomic) NSString *currentTransportStatus; // @synthesize currentTransportStatus=_currentTransportStatus;
@property(nonatomic) long long currentTransportState; // @synthesize currentTransportState=_currentTransportState;
@property(copy, nonatomic) NSString *currentSpeed; // @synthesize currentSpeed=_currentSpeed;
- (void).cxx_destruct;
- (id)initWithData:(id)arg1;
- (id)initWithDictionary:(id)arg1;

@end

