//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface GValue : NSObject
{
    _Bool _first;
    _Bool _isPtr;
    id _data;
    _Bool _dynamic;
    id _target;
    NSString *_property;
}

+ (id)valueWithTarget:(id)arg1 property:(id)arg2;
+ (id)valueWithTarget:(id)arg1 property:(id)arg2 dynamic:(_Bool)arg3;
@property(readonly, nonatomic) NSString *property; // @synthesize property=_property;
@property(readonly, nonatomic) id target; // @synthesize target=_target;
@property(readonly, nonatomic) _Bool isDynamic; // @synthesize isDynamic=_dynamic;
- (void).cxx_destruct;
- (void)reset;
- (id)data;
- (struct CATransform3D)CATransform3DValue;
- (struct CGPoint)CGPointValue;
- (struct CGSize)CGSizeValue;
- (struct CGRect)CGRectValue;
- (float)floatValue;
- (id)initWithTarget:(id)arg1 property:(id)arg2;
- (id)initWithTarget:(id)arg1 property:(id)arg2 dynamic:(_Bool)arg3;

@end

