//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class SKPaymentTransaction;

@protocol IFlurryPaymentTransactionSource <NSObject>
- (void)recordTransaction:(SKPaymentTransaction *)arg1 statusCallback:(void (^)(int))arg2;
- (void)setIAPReportingEnabled:(_Bool)arg1;
@end

