//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IFlurryFrameSource.h"

@class FlurryTransaction, NSDictionary, NSString;

@protocol IFlurryEventFrameSource <IFlurryFrameSource>
- (void)endTimedEvent:(NSString *)arg1 withParameters:(NSDictionary *)arg2;
- (void)recordEvent:(NSString *)arg1 withParameters:(NSDictionary *)arg2 timed:(_Bool)arg3 transaction:(FlurryTransaction *)arg4;
@end

