//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@protocol IFlurryStreamFileManager <NSObject>
- (_Bool)isFilePresentAtPath:(NSString *)arg1;
- (_Bool)truncateFileAtPath:(NSString *)arg1;
- (_Bool)removeItemAtPath:(NSString *)arg1;
- (_Bool)copyFileFrom:(NSString *)arg1 toPath:(NSString *)arg2;
- (_Bool)createIfNotPresentDirectoryAtPath:(NSString *)arg1;
- (_Bool)createFileAtPath:(NSString *)arg1;
@end

