//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@protocol IFlurryStreamComponentsConfigManager <NSObject>
@property(nonatomic) __weak id <FlurryStreamComponentsConfigManagerDelegate> delegate;
@property(readonly, nonatomic) id <IFlurryPaymentTransactionSource> transactionSource;
@property(readonly, nonatomic) id <IFlurryStreamFlushSource> streamFlushSource;
@property(readonly, nonatomic) id <IFlurrySessionInitInfoSource> sessionInitInfoSource;
@property(readonly, nonatomic) id <IFlurryErrorFrameSource> errorFrameSource;
@property(readonly, nonatomic) id <IFlurryEpochFrameSource> epochFrameSource;
@property(readonly, nonatomic) id <IFlurryEventFrameSource> eventFrameSource;
@end

