//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIButton, UILabel, UIWindow;

@interface LXAlertView : UIView
{
    _Bool _dontDissmiss;
    _Bool _isBlueColor;
    CDUnknownBlockType _clickBlock;
    long long _animationStyle;
    UIWindow *_alertWindow;
    UIView *_alertView;
    UILabel *_titleLab;
    UILabel *_messageLab;
    UIButton *_cancelBtn;
    UIButton *_otherBtn;
}

@property(retain, nonatomic) UIButton *otherBtn; // @synthesize otherBtn=_otherBtn;
@property(retain, nonatomic) UIButton *cancelBtn; // @synthesize cancelBtn=_cancelBtn;
@property(retain, nonatomic) UILabel *messageLab; // @synthesize messageLab=_messageLab;
@property(retain, nonatomic) UILabel *titleLab; // @synthesize titleLab=_titleLab;
@property(retain, nonatomic) UIView *alertView; // @synthesize alertView=_alertView;
@property(retain, nonatomic) UIWindow *alertWindow; // @synthesize alertWindow=_alertWindow;
@property(nonatomic) _Bool isBlueColor; // @synthesize isBlueColor=_isBlueColor;
@property(nonatomic) _Bool dontDissmiss; // @synthesize dontDissmiss=_dontDissmiss;
@property(nonatomic) long long animationStyle; // @synthesize animationStyle=_animationStyle;
@property(copy, nonatomic) CDUnknownBlockType clickBlock; // @synthesize clickBlock=_clickBlock;
- (void).cxx_destruct;
- (void)setShowAnimation;
- (void)dismissAlertView;
- (void)showLXAlertView;
- (void)jumpToGuanWang;
- (void)btnClick2:(id)arg1;
- (void)btnClick:(id)arg1;
- (id)initWithNewVersionTitle:(id)arg1 message:(id)arg2 noCancelBtn:(_Bool)arg3 buttonClickBlock:(CDUnknownBlockType)arg4;
- (id)initWithTitle:(id)arg1 message:(id)arg2 cancelBtnTitle:(id)arg3 otherBtnTitle:(id)arg4 clickIndexBlock:(CDUnknownBlockType)arg5;
- (id)initWithTitle:(id)arg1 message:(id)arg2 cancelBtnTitle:(id)arg3 otherBtnTitle:(id)arg4 BlueColor:(_Bool)arg5 clickIndexBlock:(CDUnknownBlockType)arg6;
- (id)initWithMessage:(id)arg1 cancelBtnTitle:(id)arg2 otherBtnTitle:(id)arg3 clickIndexBlock:(CDUnknownBlockType)arg4;

@end

