//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface M3U8SegmentModel : NSObject
{
    double _duration;
    NSString *_locationUrl;
}

@property(copy, nonatomic) NSString *locationUrl; // @synthesize locationUrl=_locationUrl;
@property(nonatomic) double duration; // @synthesize duration=_duration;
- (void).cxx_destruct;

@end

