//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MahuaParentsViewController.h"

#import "UISearchBarDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"
#import "ZTLetterIndexDelegate.h"

@class MiddleSearchBar, NSArray, NSMutableArray, NSString, UITableView, ZTLetterIndex;

@interface MahuaCountryPhoneCodeVC : MahuaParentsViewController <UITableViewDelegate, UITableViewDataSource, UISearchBarDelegate, ZTLetterIndexDelegate>
{
    _Bool _isClick;
    CDUnknownBlockType _selectedModel;
    NSArray *_dataSourceArr;
    NSMutableArray *_resultArr;
    UITableView *_tableView;
    MiddleSearchBar *_searchBar;
    NSMutableArray *_letterArr;
    ZTLetterIndex *_letterIndex;
}

@property(retain, nonatomic) ZTLetterIndex *letterIndex; // @synthesize letterIndex=_letterIndex;
@property(retain, nonatomic) NSMutableArray *letterArr; // @synthesize letterArr=_letterArr;
@property(retain, nonatomic) MiddleSearchBar *searchBar; // @synthesize searchBar=_searchBar;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
@property(retain, nonatomic) NSMutableArray *resultArr; // @synthesize resultArr=_resultArr;
@property(retain, nonatomic) NSArray *dataSourceArr; // @synthesize dataSourceArr=_dataSourceArr;
@property(copy, nonatomic) CDUnknownBlockType selectedModel; // @synthesize selectedModel=_selectedModel;
- (void).cxx_destruct;
- (void)back;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)searchBarSearchButtonClicked:(id)arg1;
- (void)searchBar:(id)arg1 textDidChange:(id)arg2;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)ZTLetterIndex:(id)arg1 isChangingItemWithIndex:(long long)arg2;
- (void)ZTLetterIndex:(id)arg1 endChangeItemWithIndex:(long long)arg2;
- (void)ZTLetterIndex:(id)arg1 beginChangeItemWithIndex:(long long)arg2;
- (void)ZTLetterIndex:(id)arg1 didSelectedItemWithIndex:(long long)arg2;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

