//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface MahuaShareIntroModel : NSObject
{
    long long _method;
    NSString *_title;
    long long _type;
    NSString *_intro;
}

@property(retain, nonatomic) NSString *intro; // @synthesize intro=_intro;
@property(nonatomic) long long type; // @synthesize type=_type;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
@property(nonatomic) long long method; // @synthesize method=_method;
- (void).cxx_destruct;

@end

