//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MahuaHotItemDetailModel, MahuaMovieIntroModel, NSData, NSDictionary, NSString, NSURL, TencentOAuth;

@interface MahuaShareManager : NSObject
{
    MahuaMovieIntroModel *_model;
    MahuaHotItemDetailModel *_itemModel;
    NSDictionary *_shareDic1;
    NSDictionary *_shareDic2;
    NSDictionary *_shareDic3;
    NSDictionary *_gameDic;
    NSString *_fuzhiText;
    NSURL *_shareUrl1;
    NSURL *_shareUrl2;
    NSData *_imageData;
    NSData *_imageDataOnly;
    long long _positionType;
    TencentOAuth *_tencentOauth;
}

+ (id)shareInstance;
@property(retain, nonatomic) TencentOAuth *tencentOauth; // @synthesize tencentOauth=_tencentOauth;
@property(nonatomic) long long positionType; // @synthesize positionType=_positionType;
@property(retain, nonatomic) NSData *imageDataOnly; // @synthesize imageDataOnly=_imageDataOnly;
@property(retain, nonatomic) NSData *imageData; // @synthesize imageData=_imageData;
@property(retain, nonatomic) NSURL *shareUrl2; // @synthesize shareUrl2=_shareUrl2;
@property(retain, nonatomic) NSURL *shareUrl1; // @synthesize shareUrl1=_shareUrl1;
@property(copy, nonatomic) NSString *fuzhiText; // @synthesize fuzhiText=_fuzhiText;
@property(retain, nonatomic) NSDictionary *gameDic; // @synthesize gameDic=_gameDic;
@property(retain, nonatomic) NSDictionary *shareDic3; // @synthesize shareDic3=_shareDic3;
@property(retain, nonatomic) NSDictionary *shareDic2; // @synthesize shareDic2=_shareDic2;
@property(retain, nonatomic) NSDictionary *shareDic1; // @synthesize shareDic1=_shareDic1;
@property(retain, nonatomic) MahuaHotItemDetailModel *itemModel; // @synthesize itemModel=_itemModel;
@property(retain, nonatomic) MahuaMovieIntroModel *model; // @synthesize model=_model;
- (void).cxx_destruct;
- (void)shareNotice:(long long)arg1;
- (id)replaceShareIntroModel:(long long)arg1 andMethod:(long long)arg2;
- (id)imageWithImage:(id)arg1 scaledToSize:(struct CGSize)arg2;
- (void)pasteString;
- (void)shareToWeiBo;
- (void)shareToQQZone;
- (void)shareToQQ;
- (void)shareToWeChatWithFriend:(_Bool)arg1;
- (void)registerSharePlatom;
- (id)init;

@end

