//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MahuaParentsViewController.h"

#import "MahuaCommentDetailCellDelegate.h"
#import "MahuaCommentToolBarDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class MahuaCommentModel, MahuaCommentToolBar, NSMutableArray, NSString, UITableView, UIView;

@interface MahuaCommentDetailMsgVC : MahuaParentsViewController <UITableViewDelegate, UITableViewDataSource, MahuaCommentDetailCellDelegate, MahuaCommentToolBarDelegate>
{
    _Bool _isEditingComment;
    long long _pageIndex;
    UITableView *_tableView;
    NSMutableArray *_dataAryM;
    MahuaCommentModel *_commentModel;
    MahuaCommentToolBar *_commentToolBar;
    double _currentCommentBarHeight;
    double _keyboardHeight;
    MahuaCommentModel *_childCommentModel;
    long long _sendCommentType;
    UIView *_bgView;
}

+ (id)commentDetailWithCommentModel:(id)arg1;
@property(retain, nonatomic) UIView *bgView; // @synthesize bgView=_bgView;
@property(nonatomic) long long sendCommentType; // @synthesize sendCommentType=_sendCommentType;
@property(retain, nonatomic) MahuaCommentModel *childCommentModel; // @synthesize childCommentModel=_childCommentModel;
@property(nonatomic) double keyboardHeight; // @synthesize keyboardHeight=_keyboardHeight;
@property(nonatomic) _Bool isEditingComment; // @synthesize isEditingComment=_isEditingComment;
@property(nonatomic) double currentCommentBarHeight; // @synthesize currentCommentBarHeight=_currentCommentBarHeight;
@property(retain, nonatomic) MahuaCommentToolBar *commentToolBar; // @synthesize commentToolBar=_commentToolBar;
@property(retain, nonatomic) MahuaCommentModel *commentModel; // @synthesize commentModel=_commentModel;
@property(retain, nonatomic) NSMutableArray *dataAryM; // @synthesize dataAryM=_dataAryM;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
@property(nonatomic) long long pageIndex; // @synthesize pageIndex=_pageIndex;
- (void).cxx_destruct;
- (void)didReceiveMemoryWarning;
- (void)p_changeReplyMainComment;
- (void)bgViewClick;
- (void)keyboardWillShow:(id)arg1;
- (void)p_postRequestSendComment:(id)arg1 sendType:(long long)arg2;
- (void)sendCommentToolBar:(id)arg1 text:(id)arg2;
- (void)changeHeightCommentToolBar:(id)arg1 height:(double)arg2;
- (void)endEditingCommentToolBar:(id)arg1;
- (_Bool)beginEditingCommentToolBar:(id)arg1;
- (void)replyCommentMahuaCommentDetailCell:(id)arg1;
- (void)zanCommentMahuaCommentDetailCell:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)p_postRequestChildComment;
- (void)p_loadMoreData;
- (void)viewWillLayoutSubviews;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

