//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface MahuaAvatarModel : NSObject
{
    long long _ID;
    NSString *_path;
    long long _isHighlight;
}

+ (id)mj_replacedKeyFromPropertyName;
@property(nonatomic) long long isHighlight; // @synthesize isHighlight=_isHighlight;
@property(retain, nonatomic) NSString *path; // @synthesize path=_path;
@property(nonatomic) long long ID; // @synthesize ID=_ID;
- (void).cxx_destruct;

@end

