//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MahuaParentsViewController.h"

@class ClickTextView;

@interface MahuaNetErrorViewController : MahuaParentsViewController
{
    ClickTextView *_clickTextView1;
    ClickTextView *_clickTextView3;
    ClickTextView *_clickTextView4;
    ClickTextView *_clickTextView5;
}

@property(retain, nonatomic) ClickTextView *clickTextView5; // @synthesize clickTextView5=_clickTextView5;
@property(retain, nonatomic) ClickTextView *clickTextView4; // @synthesize clickTextView4=_clickTextView4;
@property(retain, nonatomic) ClickTextView *clickTextView3; // @synthesize clickTextView3=_clickTextView3;
@property(retain, nonatomic) ClickTextView *clickTextView1; // @synthesize clickTextView1=_clickTextView1;
- (void).cxx_destruct;
- (void)setUpUI;
- (void)setUpNav;
- (void)viewDidLoad;
- (long long)preferredStatusBarStyle;

@end

