//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface MahuaBarrageDescriptionModel : NSObject
{
    NSString *_Descrition;
    long long _money;
}

+ (id)mj_replacedKeyFromPropertyName;
@property(nonatomic) long long money; // @synthesize money=_money;
@property(retain, nonatomic) NSString *Descrition; // @synthesize Descrition=_Descrition;
- (void).cxx_destruct;

@end

