//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface MahuaGetRequest : NSObject
{
}

+ (void)getUrlNormalRequestWithURL:(id)arg1 andStringSuccessBlock:(CDUnknownBlockType)arg2 andFailBlock:(CDUnknownBlockType)arg3;
+ (void)getTodayUrl;
+ (void)getBlogUrl;
+ (void)getDomainUrl;
+ (id)str:(id)arg1;
+ (void)didWhileGetRequestWithParameter:(id)arg1 andURL:(id)arg2 andStringSuccessBlock:(CDUnknownBlockType)arg3 andExceptionBlock:(CDUnknownBlockType)arg4 andFailBlock:(CDUnknownBlockType)arg5;
+ (void)getRequestWithParameter:(id)arg1 andURL:(id)arg2 andStringSuccessBlock:(CDUnknownBlockType)arg3 andExceptionBlock:(CDUnknownBlockType)arg4 andFailBlock:(CDUnknownBlockType)arg5;
+ (id)responseSerializer;
+ (id)requestSerializer;

@end

