//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface MahuaDuiHuanMaModel : NSObject
{
    NSString *_modifyTime;
    NSString *_code;
    NSString *_authList;
}

@property(copy, nonatomic) NSString *authList; // @synthesize authList=_authList;
@property(copy, nonatomic) NSString *code; // @synthesize code=_code;
@property(copy, nonatomic) NSString *modifyTime; // @synthesize modifyTime=_modifyTime;
- (void).cxx_destruct;

@end

