//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class MahuaExchangeModel, MahuaMovieIntroModel, MahuaUserDetailModel, NSMutableArray, ZFPlayerCustomBtn;

@interface MahuaVideoQualityView : UIView
{
    _Bool _makeViews;
    _Bool _canDownLoad1080P;
    ZFPlayerCustomBtn *_selBtn;
    CDUnknownBlockType _chooseVideoClick;
    CDUnknownBlockType _closeAction;
    CDUnknownBlockType _loginAction;
    CDUnknownBlockType _earnMoneyAction;
    CDUnknownBlockType _blueLightAction;
    MahuaMovieIntroModel *_movieIntroModel;
    NSMutableArray *_btnArray;
    MahuaExchangeModel *_moneyModel;
    MahuaUserDetailModel *_userModel;
}

@property(retain, nonatomic) MahuaUserDetailModel *userModel; // @synthesize userModel=_userModel;
@property(retain, nonatomic) MahuaExchangeModel *moneyModel; // @synthesize moneyModel=_moneyModel;
@property(retain, nonatomic) NSMutableArray *btnArray; // @synthesize btnArray=_btnArray;
@property(nonatomic) _Bool canDownLoad1080P; // @synthesize canDownLoad1080P=_canDownLoad1080P;
@property(nonatomic) _Bool makeViews; // @synthesize makeViews=_makeViews;
@property(retain, nonatomic) MahuaMovieIntroModel *movieIntroModel; // @synthesize movieIntroModel=_movieIntroModel;
@property(copy, nonatomic) CDUnknownBlockType blueLightAction; // @synthesize blueLightAction=_blueLightAction;
@property(copy, nonatomic) CDUnknownBlockType earnMoneyAction; // @synthesize earnMoneyAction=_earnMoneyAction;
@property(copy, nonatomic) CDUnknownBlockType loginAction; // @synthesize loginAction=_loginAction;
@property(copy, nonatomic) CDUnknownBlockType closeAction; // @synthesize closeAction=_closeAction;
@property(copy, nonatomic) CDUnknownBlockType chooseVideoClick; // @synthesize chooseVideoClick=_chooseVideoClick;
@property(retain, nonatomic) ZFPlayerCustomBtn *selBtn; // @synthesize selBtn=_selBtn;
- (void).cxx_destruct;
- (void)hide;
- (void)showWithModel:(id)arg1 WithMoneyModel:(id)arg2;
- (void)hiddenTapGesture:(id)arg1;
- (void)dealWithBtn:(id)arg1;
- (void)getVideoURL:(id)arg1 withPlayType:(id)arg2 WithBtn:(id)arg3;
- (void)finishBtn:(id)arg1;
- (void)btnClick:(id)arg1;
- (void)makeView;
- (id)initWithFrame:(struct CGRect)arg1;

@end

