//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionReusableView.h"

@class NSIndexPath, NSMutableArray, UIButton, UILabel, UIView, ZPCarouselView;

@interface MahuaTwoStyleHeaderCollectionReusableView : UICollectionReusableView
{
    UIView *_topView;
    UIView *_pointView;
    UILabel *_titleLabel;
    UIButton *_moreBtn;
    UIButton *_moreImgaeView;
    ZPCarouselView *_cycleScrollView;
    id <MahuaTwoStyleHeaderCollectionReusableViewDelegate> _delegate;
    NSMutableArray *_bannerArray;
    NSIndexPath *_currentIndexPath;
}

@property(retain, nonatomic) NSIndexPath *currentIndexPath; // @synthesize currentIndexPath=_currentIndexPath;
@property(retain, nonatomic) NSMutableArray *bannerArray; // @synthesize bannerArray=_bannerArray;
@property(nonatomic) __weak id <MahuaTwoStyleHeaderCollectionReusableViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) ZPCarouselView *cycleScrollView; // @synthesize cycleScrollView=_cycleScrollView;
@property(retain, nonatomic) UIButton *moreImgaeView; // @synthesize moreImgaeView=_moreImgaeView;
@property(retain, nonatomic) UIButton *moreBtn; // @synthesize moreBtn=_moreBtn;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UIView *pointView; // @synthesize pointView=_pointView;
@property(retain, nonatomic) UIView *topView; // @synthesize topView=_topView;
- (void).cxx_destruct;
- (void)moreMovie;
- (void)refreshDataWithModel:(id)arg1 BannerModelArr:(id)arg2 NSIndexPath:(id)arg3;
- (void)createUI;
- (id)initWithFrame:(struct CGRect)arg1;

@end

