//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "SDCycleScrollViewDelegate.h"

@class MahuaPageControlView, NSArray, NSString, SDCycleScrollView;

@interface MahuaCycleScrollView : UIView <SDCycleScrollViewDelegate>
{
    CDUnknownBlockType _didSelectItemAtIndex;
    SDCycleScrollView *_cycleScrollView;
    MahuaPageControlView *_pageControl;
    NSArray *_bootadsList;
}

@property(retain, nonatomic) NSArray *bootadsList; // @synthesize bootadsList=_bootadsList;
@property(retain, nonatomic) MahuaPageControlView *pageControl; // @synthesize pageControl=_pageControl;
@property(retain, nonatomic) SDCycleScrollView *cycleScrollView; // @synthesize cycleScrollView=_cycleScrollView;
@property(copy, nonatomic) CDUnknownBlockType didSelectItemAtIndex; // @synthesize didSelectItemAtIndex=_didSelectItemAtIndex;
- (void).cxx_destruct;
- (void)cycleScrollView:(id)arg1 didScrollToIndex:(long long)arg2;
- (void)cycleScrollView:(id)arg1 didSelectItemAtIndex:(long long)arg2;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

