//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MahuaM3U8DownloadManager, NSMutableArray;

@interface MahuaM3U8Session : NSObject
{
    NSMutableArray *_finishedlist;
    NSMutableArray *_downloadinglist;
    CDUnknownBlockType _UpdateProgressBlock;
    MahuaM3U8DownloadManager *_fileInfo;
}

+ (id)allocWithZone:(struct _NSZone *)arg1;
+ (id)sharedInstanse;
@property(retain, nonatomic) MahuaM3U8DownloadManager *fileInfo; // @synthesize fileInfo=_fileInfo;
@property(copy, nonatomic) CDUnknownBlockType UpdateProgressBlock; // @synthesize UpdateProgressBlock=_UpdateProgressBlock;
@property(readonly, nonatomic) NSMutableArray *downloadinglist; // @synthesize downloadinglist=_downloadinglist;
@property(readonly, nonatomic) NSMutableArray *finishedlist; // @synthesize finishedlist=_finishedlist;
- (void).cxx_destruct;
@property(readonly, nonatomic) _Bool isDownLoadingTask;
- (id)returnFBLWithP:(id)arg1;
- (void)deleteDoneManager:(id)arg1;
- (void)resumeDownLoadWithDownLoadingArr:(id)arg1;
- (void)deleteManager:(id)arg1;
- (void)saveFinishedFile:(id)arg1;
- (void)sentDownloadDiryWithManager:(id)arg1;
- (void)downFileUrl:(id)arg1 filename:(id)arg2 filePrex:(id)arg3 fileimage:(id)arg4 totalTime:(id)arg5 viedeoSize:(id)arg6 PlayId:(id)arg7 SortId:(id)arg8 VideoType:(id)arg9 CurrentDownLoadFBL:(id)arg10 withPlaySore:(id)arg11 withSortNum:(id)arg12 ImageUrl:(id)arg13;
- (void)loadloadingfiles;
- (void)loadFinishedfiles;
- (void)saveManager:(id)arg1 ToFile:(id)arg2;
- (void)createPlistDirectory;
- (id)init;

@end

