//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class MahuaMovieIntroModel, MahuaVideoModel, NSDictionary, UIImage;

@interface MahuaFullScreenShareView : UIView
{
    _Bool _loadShare;
    CDUnknownBlockType _copyLinkAction;
    NSDictionary *_dict;
    NSDictionary *_dict2;
    long long _type;
    CDUnknownBlockType _closeAction;
    CDUnknownBlockType _goSharePicAction;
    UIView *_shareView;
    UIImage *_shareImage;
    MahuaMovieIntroModel *_model;
    MahuaVideoModel *_videoModel;
}

@property(retain, nonatomic) MahuaVideoModel *videoModel; // @synthesize videoModel=_videoModel;
@property(retain, nonatomic) MahuaMovieIntroModel *model; // @synthesize model=_model;
@property(retain, nonatomic) UIImage *shareImage; // @synthesize shareImage=_shareImage;
@property(nonatomic) _Bool loadShare; // @synthesize loadShare=_loadShare;
@property(retain, nonatomic) UIView *shareView; // @synthesize shareView=_shareView;
@property(copy, nonatomic) CDUnknownBlockType goSharePicAction; // @synthesize goSharePicAction=_goSharePicAction;
@property(copy, nonatomic) CDUnknownBlockType closeAction; // @synthesize closeAction=_closeAction;
@property(nonatomic) long long type; // @synthesize type=_type;
@property(retain, nonatomic) NSDictionary *dict2; // @synthesize dict2=_dict2;
@property(retain, nonatomic) NSDictionary *dict; // @synthesize dict=_dict;
@property(copy, nonatomic) CDUnknownBlockType copyLinkAction; // @synthesize copyLinkAction=_copyLinkAction;
- (void).cxx_destruct;
- (void)goCopy;
- (void)goWeiBo;
- (void)goQQzone;
- (void)goQQ;
- (id)imageWithImage:(id)arg1 scaledToSize:(struct CGSize)arg2;
- (void)goWechat:(_Bool)arg1;
- (void)shareBtnClick:(id)arg1;
- (void)makeShareViews;
- (void)showShareViewWithModel:(id)arg1 andVideoModel:(id)arg2;
- (void)hide;
- (void)show;
- (void)hiddenTapGesture:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

