//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MahuaParentsViewController.h"

@class MahuaAllMessageModel, NSMutableArray, UIView;

@interface MahuaAllMassageVC : MahuaParentsViewController
{
    NSMutableArray *_dataArray;
    MahuaAllMessageModel *_xitongModel;
    MahuaAllMessageModel *_pinglunModel;
    UIView *_BGView1;
}

@property(retain, nonatomic) UIView *BGView1; // @synthesize BGView1=_BGView1;
@property(retain, nonatomic) MahuaAllMessageModel *pinglunModel; // @synthesize pinglunModel=_pinglunModel;
@property(retain, nonatomic) MahuaAllMessageModel *xitongModel; // @synthesize xitongModel=_xitongModel;
@property(retain, nonatomic) NSMutableArray *dataArray; // @synthesize dataArray=_dataArray;
- (void).cxx_destruct;
- (void)postMessageRequest;
- (void)buttonClick:(id)arg1;
- (void)setUpUI;
- (void)viewDidLoad;

@end

