//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class UIButton, UIImageView, UILabel, UIView;

@interface MahuaHotItemDetailCommentCell : UITableViewCell
{
    UIImageView *_headerView;
    UILabel *_nameLabel;
    UILabel *_timeLabel;
    UILabel *_likeCountLabel;
    UIButton *_likeView;
    UILabel *_commentLabel;
    UIView *_line;
    id <MahuaHotItemDetailCommentCellDelegate> _delegate;
}

@property(nonatomic) __weak id <MahuaHotItemDetailCommentCellDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) UIView *line; // @synthesize line=_line;
@property(retain, nonatomic) UILabel *commentLabel; // @synthesize commentLabel=_commentLabel;
@property(retain, nonatomic) UIButton *likeView; // @synthesize likeView=_likeView;
@property(retain, nonatomic) UILabel *likeCountLabel; // @synthesize likeCountLabel=_likeCountLabel;
@property(retain, nonatomic) UILabel *timeLabel; // @synthesize timeLabel=_timeLabel;
@property(retain, nonatomic) UILabel *nameLabel; // @synthesize nameLabel=_nameLabel;
@property(retain, nonatomic) UIImageView *headerView; // @synthesize headerView=_headerView;
- (void).cxx_destruct;
- (void)likeButtonComment:(id)arg1;
- (void)likeTapComment:(id)arg1;
- (void)configCellWithModel:(id)arg1 NSIndexPath:(id)arg2;
- (void)createUI;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

