//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface MahuaGoldRecordModel : NSObject
{
    NSString *_businessTitle;
    NSString *_gmtCreateStr;
    long long _money;
    long long _type;
}

@property(nonatomic) long long type; // @synthesize type=_type;
@property(nonatomic) long long money; // @synthesize money=_money;
@property(copy, nonatomic) NSString *gmtCreateStr; // @synthesize gmtCreateStr=_gmtCreateStr;
@property(copy, nonatomic) NSString *businessTitle; // @synthesize businessTitle=_businessTitle;
- (void).cxx_destruct;

@end

