//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSTimer, UILabel, ZFPlayerCustomBtn;

@interface MahuaLockScreenView : UIView
{
    CDUnknownBlockType _lockScreenAction;
    ZFPlayerCustomBtn *_lockBtn;
    UILabel *_showLab;
    NSTimer *_timer;
    long long _dismissTime;
}

@property(nonatomic) long long dismissTime; // @synthesize dismissTime=_dismissTime;
@property(retain, nonatomic) NSTimer *timer; // @synthesize timer=_timer;
@property(retain, nonatomic) UILabel *showLab; // @synthesize showLab=_showLab;
@property(retain, nonatomic) ZFPlayerCustomBtn *lockBtn; // @synthesize lockBtn=_lockBtn;
@property(copy, nonatomic) CDUnknownBlockType lockScreenAction; // @synthesize lockScreenAction=_lockScreenAction;
- (void).cxx_destruct;
- (void)dealloc;
- (void)invalidateTimer;
- (void)hide;
- (void)timeChange;
- (void)show;
- (void)lockBtnClick:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

