//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@interface MahuaParentsViewController : UIViewController
{
    _Bool _fromMissonCenter;
    _Bool _fromSpreadRootVC;
    CDUnknownBlockType _dismissLogin;
    CDUnknownBlockType _dismissLoginBlock;
}

@property(copy, nonatomic) CDUnknownBlockType dismissLoginBlock; // @synthesize dismissLoginBlock=_dismissLoginBlock;
@property(nonatomic) _Bool fromSpreadRootVC; // @synthesize fromSpreadRootVC=_fromSpreadRootVC;
@property(copy, nonatomic) CDUnknownBlockType dismissLogin; // @synthesize dismissLogin=_dismissLogin;
@property(nonatomic) _Bool fromMissonCenter; // @synthesize fromMissonCenter=_fromMissonCenter;
- (void).cxx_destruct;
- (void)back;
- (void)didReceiveMemoryWarning;
- (void)panduanNetStatus;
- (void)setUpNav;
- (void)viewDidLoad;
- (_Bool)prefersStatusBarHidden;
- (long long)preferredInterfaceOrientationForPresentation;
- (unsigned long long)supportedInterfaceOrientations;
- (_Bool)shouldAutorotate;
- (long long)preferredStatusBarStyle;

@end

