//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@interface MahuaCollectionUpdateBubbleView : UIView
{
    _Bool _showing;
}

+ (id)shareInstance;
@property(nonatomic) _Bool showing; // @synthesize showing=_showing;
- (void)hide;
- (void)show;

@end

