//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionReusableView.h"

@class NSIndexPath, UIButton, UILabel, UIView;

@interface MahuaRecommandCollectionHeaderReusableView : UICollectionReusableView
{
    UIView *_line;
    UIView *_topView;
    UIView *_pointView;
    UILabel *_titleLabel;
    UIButton *_moreBtn;
    UIButton *_moreImgaeView;
    id <MahuaRecommandCollectionHeaderReusableViewDelegate> _delegate;
    NSIndexPath *_currentIndexPath;
}

@property(retain, nonatomic) NSIndexPath *currentIndexPath; // @synthesize currentIndexPath=_currentIndexPath;
@property(nonatomic) __weak id <MahuaRecommandCollectionHeaderReusableViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) UIButton *moreImgaeView; // @synthesize moreImgaeView=_moreImgaeView;
@property(retain, nonatomic) UIButton *moreBtn; // @synthesize moreBtn=_moreBtn;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UIView *pointView; // @synthesize pointView=_pointView;
@property(retain, nonatomic) UIView *topView; // @synthesize topView=_topView;
@property(retain, nonatomic) UIView *line; // @synthesize line=_line;
- (void).cxx_destruct;
- (void)moreData;
- (void)moreData:(id)arg1;
- (void)refreshDataWithModel:(id)arg1 NSIndexPath:(id)arg2;
- (void)createUI;
- (id)initWithFrame:(struct CGRect)arg1;

@end

