//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WMPageController.h"

@class NSMutableArray, UIView;

@interface MahuaDiscoveryViewController : WMPageController
{
    UIView *_line;
    NSMutableArray *_titleArray;
    UIView *_clickTextView;
}

@property(retain, nonatomic) UIView *clickTextView; // @synthesize clickTextView=_clickTextView;
@property(retain, nonatomic) NSMutableArray *titleArray; // @synthesize titleArray=_titleArray;
@property(retain, nonatomic) UIView *line; // @synthesize line=_line;
- (void).cxx_destruct;
- (void)junmpToIntroVC;
- (void)AFNReachability:(id)arg1;
- (void)didReceiveMemoryWarning;
- (void)passCurrentSeletedIndex:(int)arg1;
- (struct CGRect)pageController:(id)arg1 preferredFrameForContentView:(id)arg2;
- (struct CGRect)pageController:(id)arg1 preferredFrameForMenuView:(id)arg2;
- (double)menuView:(id)arg1 widthForItemAtIndex:(long long)arg2;
- (id)pageController:(id)arg1 viewControllerAtIndex:(long long)arg2;
- (id)pageController:(id)arg1 titleAtIndex:(long long)arg2;
- (long long)numbersOfChildControllersInPageController:(id)arg1;
- (void)dealloc;
- (void)viewDidLoad;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;

@end

