//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MahuaParentsViewController.h"

@class UIButton;

@interface MahuaSubscribeUSViewController : MahuaParentsViewController
{
    UIButton *_backBtn;
}

@property(retain, nonatomic) UIButton *backBtn; // @synthesize backBtn=_backBtn;
- (void).cxx_destruct;
- (void)back;
- (void)didReceiveMemoryWarning;
- (void)router:(id)arg1;
- (void)setUpUI;
- (void)viewDidLoad;

@end

