//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MahuaParentsViewController.h"

@class NSString, UIScrollView;

@interface MahuaHelpAndFeedBackVC : MahuaParentsViewController
{
    _Bool _isFromMoviePlay;
    _Bool _isFromDLNA;
    NSString *_titleName;
    UIScrollView *_scrollV;
}

@property(retain, nonatomic) UIScrollView *scrollV; // @synthesize scrollV=_scrollV;
@property(nonatomic) _Bool isFromDLNA; // @synthesize isFromDLNA=_isFromDLNA;
@property(nonatomic) _Bool isFromMoviePlay; // @synthesize isFromMoviePlay=_isFromMoviePlay;
@property(retain, nonatomic) NSString *titleName; // @synthesize titleName=_titleName;
- (void).cxx_destruct;
- (void)back;
- (void)pushVC;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;

@end

