//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"

@class MahuaRandomBarrage, NSMutableArray, NSString;

@interface MahuaRandomTotalModel : NSObject <NSCoding>
{
    NSString *_ID;
    MahuaRandomBarrage *_barrageList;
    NSMutableArray *_barrageRule;
}

@property(retain, nonatomic) NSMutableArray *barrageRule; // @synthesize barrageRule=_barrageRule;
@property(retain, nonatomic) MahuaRandomBarrage *barrageList; // @synthesize barrageList=_barrageList;
@property(retain, nonatomic) NSString *ID; // @synthesize ID=_ID;
- (void).cxx_destruct;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;

@end

