//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSString;

@interface MahuaAllMessageModel : NSObject
{
    NSString *_messageTypeName;
    NSArray *_list;
    long long _messageType;
}

+ (id)mj_objectClassInArray;
@property(nonatomic) long long messageType; // @synthesize messageType=_messageType;
@property(retain, nonatomic) NSArray *list; // @synthesize list=_list;
@property(retain, nonatomic) NSString *messageTypeName; // @synthesize messageTypeName=_messageTypeName;
- (void).cxx_destruct;

@end

