//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@interface MahuaBlackCoverView : UIView
{
    double _screenValue;
    CDUnknownBlockType _closeBlackCoverView;
}

@property(copy, nonatomic) CDUnknownBlockType closeBlackCoverView; // @synthesize closeBlackCoverView=_closeBlackCoverView;
@property(nonatomic) double screenValue; // @synthesize screenValue=_screenValue;
- (void).cxx_destruct;
- (void)hide;
- (void)show;
- (void)hiddenTapGesture:(id)arg1;
- (void)setupUI;
- (id)initWithFrame:(struct CGRect)arg1;

@end

