//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewCell.h"

@class FLAnimatedImageView, UILabel;

@interface MahuaRecommandCollectionViewCellStyleOne : UICollectionViewCell
{
    FLAnimatedImageView *_coverImage;
    UILabel *_titleLabel;
}

@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) FLAnimatedImageView *coverImage; // @synthesize coverImage=_coverImage;
- (void).cxx_destruct;
- (void)configCellWithModel:(id)arg1;
- (void)createUI;
- (id)initWithFrame:(struct CGRect)arg1;

@end

