//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface MahuaExchangeModel : NSObject
{
    _Bool _enough;
    _Bool _hasBottomLine;
    NSString *_authId;
    NSString *_descrition;
    unsigned long long _hasFlag;
    long long _ID;
    long long _money;
    NSString *_title;
    long long _validNum;
    NSString *_validTime;
    NSString *_currentTime;
    long long _validType;
    long long _validUnit;
}

+ (id)mj_replacedKeyFromPropertyName;
@property(nonatomic) _Bool hasBottomLine; // @synthesize hasBottomLine=_hasBottomLine;
@property(nonatomic) _Bool enough; // @synthesize enough=_enough;
@property(nonatomic) long long validUnit; // @synthesize validUnit=_validUnit;
@property(nonatomic) long long validType; // @synthesize validType=_validType;
@property(copy, nonatomic) NSString *currentTime; // @synthesize currentTime=_currentTime;
@property(copy, nonatomic) NSString *validTime; // @synthesize validTime=_validTime;
@property(nonatomic) long long validNum; // @synthesize validNum=_validNum;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(nonatomic) long long money; // @synthesize money=_money;
@property(nonatomic) long long ID; // @synthesize ID=_ID;
@property(nonatomic) unsigned long long hasFlag; // @synthesize hasFlag=_hasFlag;
@property(copy, nonatomic) NSString *descrition; // @synthesize descrition=_descrition;
@property(copy, nonatomic) NSString *authId; // @synthesize authId=_authId;
- (void).cxx_destruct;
@property(readonly, copy, nonatomic) NSString *unitStr;

@end

