//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface MahuaRankListModel : NSObject
{
    NSString *_rank;
    long long _videoId;
    NSString *_flag;
    NSString *_title;
    NSString *_backgroundColor;
}

@property(copy, nonatomic) NSString *backgroundColor; // @synthesize backgroundColor=_backgroundColor;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(copy, nonatomic) NSString *flag; // @synthesize flag=_flag;
@property(nonatomic) long long videoId; // @synthesize videoId=_videoId;
@property(copy, nonatomic) NSString *rank; // @synthesize rank=_rank;
- (void).cxx_destruct;

@end

