//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface MahuaStatEndTimePModel : NSObject
{
    long long _s;
    long long _e;
}

+ (id)mj_replacedKeyFromPropertyName;
@property(nonatomic) long long e; // @synthesize e=_e;
@property(nonatomic) long long s; // @synthesize s=_s;

@end

