//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface MahuaAnswerModel : NSObject
{
    _Bool _isSelect;
    long long _num;
    NSString *_answer;
}

@property(retain, nonatomic) NSString *answer; // @synthesize answer=_answer;
@property(nonatomic) _Bool isSelect; // @synthesize isSelect=_isSelect;
@property(nonatomic) long long num; // @synthesize num=_num;
- (void).cxx_destruct;

@end

