//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "UITextViewDelegate.h"

@class NSString, UIButton, UITextView;

@interface MahuaCommentToolBar : UIView <UITextViewDelegate>
{
    UIView *_line_view;
    UITextView *_comment_textView;
    UIButton *_send_btn;
    id <MahuaCommentToolBarDelegate> _delegate;
}

@property(nonatomic) __weak id <MahuaCommentToolBarDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) UIButton *send_btn; // @synthesize send_btn=_send_btn;
@property(retain, nonatomic) UITextView *comment_textView; // @synthesize comment_textView=_comment_textView;
@property(retain, nonatomic) UIView *line_view; // @synthesize line_view=_line_view;
- (void).cxx_destruct;
- (void)sendCommentAction:(id)arg1;
- (_Bool)textViewShouldEndEditing:(id)arg1;
- (void)textViewDidChange:(id)arg1;
- (id)filterCharactor:(id)arg1 withRegex:(id)arg2;
- (_Bool)emojiInUnicode:(short)arg1;
- (_Bool)emojiInSoftBankUnicode:(short)arg1;
- (_Bool)stringContainsEmoji:(id)arg1;
- (_Bool)textView:(id)arg1 shouldChangeTextInRange:(struct _NSRange)arg2 replacementText:(id)arg3;
- (_Bool)textViewShouldBeginEditing:(id)arg1;
- (void)becomeFirstResponder;
- (void)p_initUI;
- (_Bool)textViewHasComment;
- (void)changeCommentTextViewPlaceHolder;
- (void)replyMainCommentWithChildUserName:(id)arg1;
- (void)replyChildCommentWithChildUserName:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1 delegate:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

