//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class UILabel, UIView;

@interface MahuaTelevisonNewCell : UITableViewCell
{
    UILabel *_sortNumLabel;
    UILabel *_seekTimeLabel;
    UIView *_line;
}

@property(retain, nonatomic) UIView *line; // @synthesize line=_line;
@property(retain, nonatomic) UILabel *seekTimeLabel; // @synthesize seekTimeLabel=_seekTimeLabel;
@property(retain, nonatomic) UILabel *sortNumLabel; // @synthesize sortNumLabel=_sortNumLabel;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (void)configCellWithManager:(id)arg1;
- (void)createUI;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

