//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class MahuaMovieIntroModel, UIButton, UIScrollView;

@interface MahuaMovieIntroView : UIView
{
    UIButton *_topBtn;
    UIScrollView *_scrollV;
    MahuaMovieIntroModel *_model;
}

@property(retain, nonatomic) MahuaMovieIntroModel *model; // @synthesize model=_model;
@property(retain, nonatomic) UIScrollView *scrollV; // @synthesize scrollV=_scrollV;
@property(retain, nonatomic) UIButton *topBtn; // @synthesize topBtn=_topBtn;
- (void).cxx_destruct;
- (void)cancelBtnClick;
- (struct CGSize)textSize:(id)arg1 font:(id)arg2 maxSize:(struct CGSize)arg3;
- (void)setUpUIWithFrame:(struct CGRect)arg1 andModel:(id)arg2;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1 andModel:(id)arg2;

@end

