//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "MahuaCommentDetailCellDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class NSMutableArray, NSString, UIButton, UILabel, UITableView;

@interface MahuaCommentDetailView : UIView <MahuaCommentDetailCellDelegate, UITableViewDelegate, UITableViewDataSource>
{
    CDUnknownBlockType _closeClickBlock;
    NSMutableArray *_dataAryM;
    id <MahuaCommentProtocol> _commentDelegate;
    id <MahuaCommentDetailViewDelegate> _delegate;
    UIButton *_back_btn;
    UILabel *_title_label;
    UIView *_line_view;
    UITableView *_tableView;
}

@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
@property(retain, nonatomic) UIView *line_view; // @synthesize line_view=_line_view;
@property(retain, nonatomic) UILabel *title_label; // @synthesize title_label=_title_label;
@property(retain, nonatomic) UIButton *back_btn; // @synthesize back_btn=_back_btn;
@property(nonatomic) __weak id <MahuaCommentDetailViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) __weak id <MahuaCommentProtocol> commentDelegate; // @synthesize commentDelegate=_commentDelegate;
@property(retain, nonatomic) NSMutableArray *dataAryM; // @synthesize dataAryM=_dataAryM;
@property(copy, nonatomic) CDUnknownBlockType closeClickBlock; // @synthesize closeClickBlock=_closeClickBlock;
- (void).cxx_destruct;
- (void)changeFootRefreshState:(long long)arg1;
- (void)p_backBtnAction;
- (void)p_loadMoreData;
- (void)p_initUI;
- (void)replyCommentMahuaCommentDetailCell:(id)arg1;
- (void)zanCommentMahuaCommentDetailCell:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

