//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MahuaParentsViewController.h"

#import "MahuaRecommandCollectionHeaderReusableViewDelegate.h"
#import "MahuaTuiJianFootCollectionReusableViewDelegate.h"
#import "MahuaTuiJianHeaderDelegate.h"
#import "MahuaTwoStyleHeaderCollectionReusableViewDelegate.h"
#import "UICollectionViewDataSource.h"
#import "UICollectionViewDelegate.h"
#import "UICollectionViewDelegateFlowLayout.h"

@class MahuaAdvertisingView, MahuaNoticeModel, MahuaRecommandNewItemModel, MahuaTuiJianHeader, MahuaVoidView, NSMutableArray, NSString, UIButton, UICollectionView, UIView;

@interface MahuaTuiJianViewController : MahuaParentsViewController <MahuaTuiJianHeaderDelegate, UICollectionViewDelegate, UICollectionViewDataSource, UICollectionViewDelegateFlowLayout, MahuaTwoStyleHeaderCollectionReusableViewDelegate, MahuaTuiJianFootCollectionReusableViewDelegate, MahuaRecommandCollectionHeaderReusableViewDelegate>
{
    _Bool _isRefresh;
    _Bool _isShowedAD;
    _Bool _isShowedVerion;
    _Bool _isShowedNewRegister;
    _Bool _isRequestADData;
    _Bool _isShowingVerion;
    _Bool _isShowingNewRegister;
    MahuaRecommandNewItemModel *_model;
    long long _typeId;
    CDUnknownBlockType _refreshSearchHotWord;
    CDUnknownBlockType _popFromMoviePlayerVC;
    UIView *_myNav;
    UIButton *_searchBtn;
    NSMutableArray *_dataArray;
    MahuaTuiJianHeader *_headerView;
    MahuaVoidView *_noNetVoidView;
    MahuaVoidView *_noDataVoidView;
    long long _currentPageIndex;
    UICollectionView *_collectionView;
    NSMutableArray *_bannerArr;
    MahuaAdvertisingView *_adAlertView;
    MahuaNoticeModel *_noticeModel;
}

@property(retain, nonatomic) MahuaNoticeModel *noticeModel; // @synthesize noticeModel=_noticeModel;
@property(retain, nonatomic) MahuaAdvertisingView *adAlertView; // @synthesize adAlertView=_adAlertView;
@property(nonatomic) _Bool isShowingNewRegister; // @synthesize isShowingNewRegister=_isShowingNewRegister;
@property(nonatomic) _Bool isShowingVerion; // @synthesize isShowingVerion=_isShowingVerion;
@property(nonatomic) _Bool isRequestADData; // @synthesize isRequestADData=_isRequestADData;
@property(nonatomic) _Bool isShowedNewRegister; // @synthesize isShowedNewRegister=_isShowedNewRegister;
@property(nonatomic) _Bool isShowedVerion; // @synthesize isShowedVerion=_isShowedVerion;
@property(nonatomic) _Bool isShowedAD; // @synthesize isShowedAD=_isShowedAD;
@property(retain, nonatomic) NSMutableArray *bannerArr; // @synthesize bannerArr=_bannerArr;
@property(retain, nonatomic) UICollectionView *collectionView; // @synthesize collectionView=_collectionView;
@property(nonatomic) _Bool isRefresh; // @synthesize isRefresh=_isRefresh;
@property(nonatomic) long long currentPageIndex; // @synthesize currentPageIndex=_currentPageIndex;
@property(retain, nonatomic) MahuaVoidView *noDataVoidView; // @synthesize noDataVoidView=_noDataVoidView;
@property(retain, nonatomic) MahuaVoidView *noNetVoidView; // @synthesize noNetVoidView=_noNetVoidView;
@property(retain, nonatomic) MahuaTuiJianHeader *headerView; // @synthesize headerView=_headerView;
@property(retain, nonatomic) NSMutableArray *dataArray; // @synthesize dataArray=_dataArray;
@property(retain, nonatomic) UIButton *searchBtn; // @synthesize searchBtn=_searchBtn;
@property(retain, nonatomic) UIView *myNav; // @synthesize myNav=_myNav;
@property(copy, nonatomic) CDUnknownBlockType popFromMoviePlayerVC; // @synthesize popFromMoviePlayerVC=_popFromMoviePlayerVC;
@property(copy, nonatomic) CDUnknownBlockType refreshSearchHotWord; // @synthesize refreshSearchHotWord=_refreshSearchHotWord;
@property(nonatomic) long long typeId; // @synthesize typeId=_typeId;
@property(retain, nonatomic) MahuaRecommandNewItemModel *model; // @synthesize model=_model;
- (void).cxx_destruct;
- (id)jsd_getRootViewController;
- (id)getCurrentViewController;
- (void)didReceiveMemoryWarning;
- (void)saveToday;
- (id)currentDay;
- (_Bool)isShowedToday;
- (void)getRegistNum;
- (void)showTuiSongAlert;
- (void)showADAlertView;
- (void)requestADData;
- (void)showNewRegisterAlertView;
- (void)postVersionRequest;
- (void)getVipPower;
- (void)changeDataWithCurrentSectionId:(long long)arg1 currentPage:(long long)arg2 GuDingId:(id)arg3 NSIndexPath:(id)arg4 FirstModel:(id)arg5 SaveFirstModel:(_Bool)arg6 TJModel:(id)arg7;
- (void)passTapAdvImageViewModel:(id)arg1;
- (void)changeDataWithNSIndexpath:(id)arg1;
- (void)moreDataWithNSIndexpath:(id)arg1;
- (void)twoheaderMoreDataWithNSIndexpath:(id)arg1;
- (void)headerMoreDataWithNSIndexpath:(id)arg1;
- (void)ClickIndex:(long long)arg1;
- (void)pushToMoviePlayerVCWithID:(long long)arg1 andcolumnId:(id)arg2 fromPage:(long long)arg3;
- (void)adClickWithID:(long long)arg1 type:(id)arg2;
- (void)openUrl:(id)arg1 withTitleStr:(id)arg2 targetType:(long long)arg3;
- (void)getMoreDataRequest;
- (void)refreshDataRequest;
- (void)setupRefresh;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 referenceSizeForFooterInSection:(long long)arg3;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 referenceSizeForHeaderInSection:(long long)arg3;
- (id)collectionView:(id)arg1 viewForSupplementaryElementOfKind:(id)arg2 atIndexPath:(id)arg3;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (struct UIEdgeInsets)collectionView:(id)arg1 layout:(id)arg2 insetForSectionAtIndex:(long long)arg3;
- (double)collectionView:(id)arg1 layout:(id)arg2 minimumInteritemSpacingForSectionAtIndex:(long long)arg3;
- (double)collectionView:(id)arg1 layout:(id)arg2 minimumLineSpacingForSectionAtIndex:(long long)arg3;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (long long)numberOfSectionsInCollectionView:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)createCollectionView;
- (void)getQueryListCache;
- (void)createDataWithPage:(long long)arg1;
- (void)getBannerCache;
- (void)getBannerData;
- (void)getRandomBarrage;
- (void)getRandomBarrageRule;
- (void)dealloc;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

