//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface MahuaPackModel : NSObject
{
    NSString *_domain;
    NSString *_aesKey;
    NSString *_umPushKey;
    NSString *_weChatKey;
    NSString *_sinaWeiBoKey;
    NSString *_qqKey;
    NSString *_flurryKey;
    NSString *_version;
    NSString *_packageId;
    NSString *_appSecret;
    NSString *_app_Name;
    NSString *_app_moneyName;
    unsigned long long _serverTime;
    double _locelTime;
}

+ (id)fetchPackChannelInfo;
+ (id)shareMahuaPackModel;
@property(nonatomic) double locelTime; // @synthesize locelTime=_locelTime;
@property(nonatomic) unsigned long long serverTime; // @synthesize serverTime=_serverTime;
@property(copy, nonatomic) NSString *app_moneyName; // @synthesize app_moneyName=_app_moneyName;
@property(copy, nonatomic) NSString *app_Name; // @synthesize app_Name=_app_Name;
@property(copy, nonatomic) NSString *appSecret; // @synthesize appSecret=_appSecret;
@property(copy, nonatomic) NSString *packageId; // @synthesize packageId=_packageId;
@property(copy, nonatomic) NSString *version; // @synthesize version=_version;
@property(copy, nonatomic) NSString *flurryKey; // @synthesize flurryKey=_flurryKey;
@property(copy, nonatomic) NSString *qqKey; // @synthesize qqKey=_qqKey;
@property(copy, nonatomic) NSString *sinaWeiBoKey; // @synthesize sinaWeiBoKey=_sinaWeiBoKey;
@property(copy, nonatomic) NSString *weChatKey; // @synthesize weChatKey=_weChatKey;
@property(copy, nonatomic) NSString *umPushKey; // @synthesize umPushKey=_umPushKey;
@property(copy, nonatomic) NSString *aesKey; // @synthesize aesKey=_aesKey;
@property(copy, nonatomic) NSString *domain; // @synthesize domain=_domain;
- (void).cxx_destruct;

@end

