//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MahuaParentsViewController.h"

#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class MahuaChooseSaveCountCell, NSMutableArray, NSString, UITableView;

@interface MahuaChooseDownLoadCountVC : MahuaParentsViewController <UITableViewDelegate, UITableViewDataSource>
{
    UITableView *_tableView;
    NSMutableArray *_dataArray;
    int downLoadCount;
    CDUnknownBlockType _retureDownLoadCount;
    MahuaChooseSaveCountCell *_selectCell;
}

@property(retain, nonatomic) MahuaChooseSaveCountCell *selectCell; // @synthesize selectCell=_selectCell;
@property(copy, nonatomic) CDUnknownBlockType retureDownLoadCount; // @synthesize retureDownLoadCount=_retureDownLoadCount;
- (void).cxx_destruct;
- (void)didReceiveMemoryWarning;
- (void)back;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)createTableView;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

