//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "MahuaChooseFBLViewDelegate.h"
#import "UICollectionViewDataSource.h"
#import "UICollectionViewDelegate.h"
#import "UICollectionViewDelegateFlowLayout.h"
#import "UIGestureRecognizerDelegate.h"

@class MahuaChooseFBLView, MahuaExchangeModel, MahuaMovieIntroModel, NSData, NSMutableArray, NSString, UIButton, UICollectionView, UIImageView, UILabel, UIScrollView;

@interface MahuaDownLoadView : UIView <UICollectionViewDelegate, UICollectionViewDataSource, UICollectionViewDelegateFlowLayout, UIGestureRecognizerDelegate, MahuaChooseFBLViewDelegate>
{
    long long saveCount;
    NSString *currentfenbianlv;
    long long keyId;
    NSMutableArray *videoPageListInfo;
    _Bool showAlert;
    _Bool _showFbl;
    _Bool _isFromDetail;
    _Bool _canDownLoadHotMovie;
    int _allreadySaveCount;
    CDUnknownBlockType _clickIndex;
    CDUnknownBlockType _clickMissonCenterIndex;
    CDUnknownBlockType _dismissdownloadview;
    MahuaExchangeModel *_canDownLoad1080P;
    NSMutableArray *_dataSource;
    long long _currentRequestPage;
    UILabel *_downloadCountLabel;
    NSData *_imageDataaaa;
    NSString *_imageUrl;
    UILabel *_diskSizeLabel;
    UIImageView *_fenbianlvView;
    UIButton *_allBtn;
    UIButton *_downBtn;
    UILabel *_savecountLabel;
    UIButton *_fenbianlvButton;
    NSMutableArray *_zldownloadArray;
    NSMutableArray *_savedownloadArray;
    NSMutableArray *_currentdownloadfinishArray;
    NSMutableArray *_currentdownLoadingArray;
    NSMutableArray *_lastselectedArray;
    NSMutableArray *_selectedArray;
    UICollectionView *_collectionView;
    NSMutableArray *_itemArray;
    UILabel *_titlelabel;
    UIButton *_closeBtn;
    UILabel *_selectedLab;
    UIView *_bottomView;
    UIScrollView *_scrollV;
    MahuaMovieIntroModel *_introModel;
    NSMutableArray *_labelArray;
    UIImageView *_imagev;
    MahuaChooseFBLView *_chooseFBLView;
    long long _currentPlaySortId;
}

@property(nonatomic) _Bool canDownLoadHotMovie; // @synthesize canDownLoadHotMovie=_canDownLoadHotMovie;
@property(nonatomic) long long currentPlaySortId; // @synthesize currentPlaySortId=_currentPlaySortId;
@property(nonatomic) _Bool isFromDetail; // @synthesize isFromDetail=_isFromDetail;
@property(retain, nonatomic) MahuaChooseFBLView *chooseFBLView; // @synthesize chooseFBLView=_chooseFBLView;
@property(retain, nonatomic) UIImageView *imagev; // @synthesize imagev=_imagev;
@property(retain, nonatomic) NSMutableArray *labelArray; // @synthesize labelArray=_labelArray;
@property(retain, nonatomic) MahuaMovieIntroModel *introModel; // @synthesize introModel=_introModel;
@property(retain, nonatomic) UIScrollView *scrollV; // @synthesize scrollV=_scrollV;
@property(retain, nonatomic) UIView *bottomView; // @synthesize bottomView=_bottomView;
@property(retain, nonatomic) UILabel *selectedLab; // @synthesize selectedLab=_selectedLab;
@property(retain, nonatomic) UIButton *closeBtn; // @synthesize closeBtn=_closeBtn;
@property(retain, nonatomic) UILabel *titlelabel; // @synthesize titlelabel=_titlelabel;
@property(retain, nonatomic) NSMutableArray *itemArray; // @synthesize itemArray=_itemArray;
@property(retain, nonatomic) UICollectionView *collectionView; // @synthesize collectionView=_collectionView;
@property(retain, nonatomic) NSMutableArray *selectedArray; // @synthesize selectedArray=_selectedArray;
@property(retain, nonatomic) NSMutableArray *lastselectedArray; // @synthesize lastselectedArray=_lastselectedArray;
@property(retain, nonatomic) NSMutableArray *currentdownLoadingArray; // @synthesize currentdownLoadingArray=_currentdownLoadingArray;
@property(retain, nonatomic) NSMutableArray *currentdownloadfinishArray; // @synthesize currentdownloadfinishArray=_currentdownloadfinishArray;
@property(retain, nonatomic) NSMutableArray *savedownloadArray; // @synthesize savedownloadArray=_savedownloadArray;
@property(retain, nonatomic) NSMutableArray *zldownloadArray; // @synthesize zldownloadArray=_zldownloadArray;
@property(retain, nonatomic) UIButton *fenbianlvButton; // @synthesize fenbianlvButton=_fenbianlvButton;
@property(retain, nonatomic) UILabel *savecountLabel; // @synthesize savecountLabel=_savecountLabel;
@property(retain, nonatomic) UIButton *downBtn; // @synthesize downBtn=_downBtn;
@property(retain, nonatomic) UIButton *allBtn; // @synthesize allBtn=_allBtn;
@property(retain, nonatomic) UIImageView *fenbianlvView; // @synthesize fenbianlvView=_fenbianlvView;
@property(retain, nonatomic) UILabel *diskSizeLabel; // @synthesize diskSizeLabel=_diskSizeLabel;
@property(nonatomic) int allreadySaveCount; // @synthesize allreadySaveCount=_allreadySaveCount;
@property(copy, nonatomic) NSString *imageUrl; // @synthesize imageUrl=_imageUrl;
@property(retain, nonatomic) NSData *imageDataaaa; // @synthesize imageDataaaa=_imageDataaaa;
@property(nonatomic) _Bool showFbl; // @synthesize showFbl=_showFbl;
@property(retain, nonatomic) UILabel *downloadCountLabel; // @synthesize downloadCountLabel=_downloadCountLabel;
@property(nonatomic) long long currentRequestPage; // @synthesize currentRequestPage=_currentRequestPage;
@property(retain, nonatomic) NSMutableArray *dataSource; // @synthesize dataSource=_dataSource;
@property(retain, nonatomic) MahuaExchangeModel *canDownLoad1080P; // @synthesize canDownLoad1080P=_canDownLoad1080P;
@property(copy, nonatomic) CDUnknownBlockType dismissdownloadview; // @synthesize dismissdownloadview=_dismissdownloadview;
@property(copy, nonatomic) CDUnknownBlockType clickMissonCenterIndex; // @synthesize clickMissonCenterIndex=_clickMissonCenterIndex;
@property(copy, nonatomic) CDUnknownBlockType clickIndex; // @synthesize clickIndex=_clickIndex;
- (void).cxx_destruct;
- (void)resetrestCacheNumUI;
- (void)postListRequest;
- (void)dealloc;
- (void)bottomLabelClick:(id)arg1;
- (void)cancelBtnClick;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (void)goToMissionCenter;
- (void)dismiss;
- (void)passFbl:(id)arg1;
- (void)selectAllCell:(id)arg1;
- (void)downLoadWithUrlArray:(id)arg1 ModelArr:(id)arg2 FileManager:(id)arg3;
- (void)requestDownLoadUrlWithDownloadIDArray:(id)arg1 ModelArray:(id)arg2 FileManager:(id)arg3;
- (void)downloadWithArr:(id)arg1 FileManager:(id)arg2;
- (void)downLoadAllChooseMovie;
- (void)goToDownLoadVC;
- (id)retureKeyWithModel:(id)arg1;
- (void)downLoadWithUrlArray:(id)arg1 Model:(id)arg2;
- (void)requestDownLoadUrlWithDownloadIDArray:(id)arg1 Model:(id)arg2;
- (void)downLoadWithModel:(id)arg1;
- (void)deleteDownWithManager:(id)arg1 Model:(id)arg2;
- (void)setUpBottomBar;
- (void)changeFenBianLvWithModel:(id)arg1;
- (void)setUpChooseFenBianLvView;
- (void)chooseFenBianLv:(id)arg1;
- (struct UIEdgeInsets)collectionView:(id)arg1 layout:(id)arg2 insetForSectionAtIndex:(long long)arg3;
- (void)setUpUIWithFrame:(struct CGRect)arg1;
- (void)buttonTitleLeft:(id)arg1 space:(double)arg2;
- (void)getListInfoWithVideoPlayList:(id)arg1;
- (void)compareIsDownlaodWithDownLoadingArray:(id)arg1 DownloadFinishArray:(id)arg2;
- (id)initWithFrame:(struct CGRect)arg1 andModel:(id)arg2 Id:(id)arg3 FromDetail:(_Bool)arg4 CanDownLoadHotVideo:(_Bool)arg5;
- (id)initWithFrame:(struct CGRect)arg1 PlayId:(id)arg2 PageArray:(id)arg3 Model:(id)arg4 FromDetail:(_Bool)arg5 CanDownLoadHotVideo:(_Bool)arg6;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

