//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSString;

@interface MahuaRecommanBannerModel : NSObject
{
    long long id;
    long long _type;
    NSString *_thumbnailUrl;
    NSString *_linkUrl;
    long long _targetType;
    long long _showType;
    long long _videoInfoId;
    NSString *_title;
    NSString *_picUrl;
    long long _topicId;
    NSDictionary *_bannerVideoVo;
}

@property(retain, nonatomic) NSDictionary *bannerVideoVo; // @synthesize bannerVideoVo=_bannerVideoVo;
@property(nonatomic) long long topicId; // @synthesize topicId=_topicId;
@property(copy, nonatomic) NSString *picUrl; // @synthesize picUrl=_picUrl;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(nonatomic) long long videoInfoId; // @synthesize videoInfoId=_videoInfoId;
@property(nonatomic) long long showType; // @synthesize showType=_showType;
@property(nonatomic) long long targetType; // @synthesize targetType=_targetType;
@property(copy, nonatomic) NSString *linkUrl; // @synthesize linkUrl=_linkUrl;
@property(copy, nonatomic) NSString *thumbnailUrl; // @synthesize thumbnailUrl=_thumbnailUrl;
@property(nonatomic) long long type; // @synthesize type=_type;
@property(nonatomic) long long id; // @synthesize id;
- (void).cxx_destruct;

@end

