//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "UIGestureRecognizerDelegate.h"

@class NSArray, NSMutableArray, NSString, UIButton, UILabel, UIScrollView;

@interface MahuaAllMovieTopChooseView : UIView <UIGestureRecognizerDelegate>
{
    CDUnknownBlockType _topBlock;
    CDUnknownBlockType _titleBlock;
    CDUnknownBlockType _title2Block;
    CDUnknownBlockType _title3Block;
    CDUnknownBlockType _title4Block;
    CDUnknownBlockType _title5Block;
    CDUnknownBlockType _passCurrentSelectIndex;
    NSArray *_topArr;
    UIButton *_topBtn;
    UIScrollView *_scrollV0;
    UIScrollView *_scrollV1;
    UIScrollView *_scrollV2;
    UIScrollView *_bottomScrollV;
    UIScrollView *_bottomScrollV1;
    UIScrollView *_bottomScrollV2;
    UILabel *_selected0Lab;
    UILabel *_selectedLab;
    UILabel *_selected2Lab;
    UILabel *_selected3Lab;
    UILabel *_selected4Lab;
    UILabel *_selected5Lab;
    NSMutableArray *_btnArray;
    NSMutableArray *_labelArray0;
    NSMutableArray *_labelArray1;
    NSMutableArray *_labelArray2;
    NSMutableArray *_labelArray3;
    NSMutableArray *_labelArray4;
    NSMutableArray *_labelArray5;
    NSMutableArray *_titleDataArray;
    NSMutableArray *_array1;
    NSMutableArray *_array2;
    NSMutableArray *_array3;
    NSMutableArray *_array4;
    NSMutableArray *_array5;
    long long _selectedId;
    long long _rowIndex;
}

@property(nonatomic) long long rowIndex; // @synthesize rowIndex=_rowIndex;
@property(nonatomic) long long selectedId; // @synthesize selectedId=_selectedId;
@property(retain, nonatomic) NSMutableArray *array5; // @synthesize array5=_array5;
@property(retain, nonatomic) NSMutableArray *array4; // @synthesize array4=_array4;
@property(retain, nonatomic) NSMutableArray *array3; // @synthesize array3=_array3;
@property(retain, nonatomic) NSMutableArray *array2; // @synthesize array2=_array2;
@property(retain, nonatomic) NSMutableArray *array1; // @synthesize array1=_array1;
@property(retain, nonatomic) NSMutableArray *titleDataArray; // @synthesize titleDataArray=_titleDataArray;
@property(retain, nonatomic) NSMutableArray *labelArray5; // @synthesize labelArray5=_labelArray5;
@property(retain, nonatomic) NSMutableArray *labelArray4; // @synthesize labelArray4=_labelArray4;
@property(retain, nonatomic) NSMutableArray *labelArray3; // @synthesize labelArray3=_labelArray3;
@property(retain, nonatomic) NSMutableArray *labelArray2; // @synthesize labelArray2=_labelArray2;
@property(retain, nonatomic) NSMutableArray *labelArray1; // @synthesize labelArray1=_labelArray1;
@property(retain, nonatomic) NSMutableArray *labelArray0; // @synthesize labelArray0=_labelArray0;
@property(retain, nonatomic) NSMutableArray *btnArray; // @synthesize btnArray=_btnArray;
@property(retain, nonatomic) UILabel *selected5Lab; // @synthesize selected5Lab=_selected5Lab;
@property(retain, nonatomic) UILabel *selected4Lab; // @synthesize selected4Lab=_selected4Lab;
@property(retain, nonatomic) UILabel *selected3Lab; // @synthesize selected3Lab=_selected3Lab;
@property(retain, nonatomic) UILabel *selected2Lab; // @synthesize selected2Lab=_selected2Lab;
@property(retain, nonatomic) UILabel *selectedLab; // @synthesize selectedLab=_selectedLab;
@property(retain, nonatomic) UILabel *selected0Lab; // @synthesize selected0Lab=_selected0Lab;
@property(retain, nonatomic) UIScrollView *bottomScrollV2; // @synthesize bottomScrollV2=_bottomScrollV2;
@property(retain, nonatomic) UIScrollView *bottomScrollV1; // @synthesize bottomScrollV1=_bottomScrollV1;
@property(retain, nonatomic) UIScrollView *bottomScrollV; // @synthesize bottomScrollV=_bottomScrollV;
@property(retain, nonatomic) UIScrollView *scrollV2; // @synthesize scrollV2=_scrollV2;
@property(retain, nonatomic) UIScrollView *scrollV1; // @synthesize scrollV1=_scrollV1;
@property(retain, nonatomic) UIScrollView *scrollV0; // @synthesize scrollV0=_scrollV0;
@property(retain, nonatomic) UIButton *topBtn; // @synthesize topBtn=_topBtn;
@property(retain, nonatomic) NSArray *topArr; // @synthesize topArr=_topArr;
@property(copy, nonatomic) CDUnknownBlockType passCurrentSelectIndex; // @synthesize passCurrentSelectIndex=_passCurrentSelectIndex;
@property(copy, nonatomic) CDUnknownBlockType title5Block; // @synthesize title5Block=_title5Block;
@property(copy, nonatomic) CDUnknownBlockType title4Block; // @synthesize title4Block=_title4Block;
@property(copy, nonatomic) CDUnknownBlockType title3Block; // @synthesize title3Block=_title3Block;
@property(copy, nonatomic) CDUnknownBlockType title2Block; // @synthesize title2Block=_title2Block;
@property(copy, nonatomic) CDUnknownBlockType titleBlock; // @synthesize titleBlock=_titleBlock;
@property(copy, nonatomic) CDUnknownBlockType topBlock; // @synthesize topBlock=_topBlock;
- (void).cxx_destruct;
- (void)bottomLabelClick3:(id)arg1;
- (void)bottomLabelClick2:(id)arg1;
- (void)bottomLabelClick:(id)arg1;
- (void)bottomScrollWithIndex:(long long)arg1;
- (void)MiddleScrollWithIndex:(long long)arg1;
- (void)topScrollWithIndex:(long long)arg1;
- (void)twoLabelClick:(id)arg1;
- (void)middleLabelClick:(id)arg1;
- (void)changeIndex;
- (void)topLabelClick:(id)arg1;
- (void)setUpUI;
- (id)initWithFrame:(struct CGRect)arg1 andArray:(id)arg2 currentSelectedId:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

