//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "UIWebViewDelegate.h"

@class MahuaNoticeModel, NSString, UIButton, UIImageView, UIWebView;

@interface MahuaAdvertisingView : UIView <UIWebViewDelegate>
{
    _Bool _showing;
    CDUnknownBlockType _imgClick;
    CDUnknownBlockType _closeBtnDidiClick;
    UIImageView *_tapView;
    UIButton *_closebtn;
    MahuaNoticeModel *_model;
    UIView *_containerView;
    UIWebView *_webView;
}

@property(retain, nonatomic) UIWebView *webView; // @synthesize webView=_webView;
@property(retain, nonatomic) UIView *containerView; // @synthesize containerView=_containerView;
@property(retain, nonatomic) MahuaNoticeModel *model; // @synthesize model=_model;
@property(retain, nonatomic) UIButton *closebtn; // @synthesize closebtn=_closebtn;
@property(retain, nonatomic) UIImageView *tapView; // @synthesize tapView=_tapView;
@property(copy, nonatomic) CDUnknownBlockType closeBtnDidiClick; // @synthesize closeBtnDidiClick=_closeBtnDidiClick;
@property(copy, nonatomic) CDUnknownBlockType imgClick; // @synthesize imgClick=_imgClick;
@property(nonatomic, getter=isShowing) _Bool showing; // @synthesize showing=_showing;
- (void).cxx_destruct;
- (void)closeBtnClick;
- (void)sendEvent:(id)arg1;
- (void)imgClick:(id)arg1;
- (void)webView:(id)arg1 didFailLoadWithError:(id)arg2;
- (void)webViewDidStartLoad:(id)arg1;
- (void)webViewDidFinishLoad:(id)arg1;
- (_Bool)webView:(id)arg1 shouldStartLoadWithRequest:(id)arg2 navigationType:(long long)arg3;
- (void)closeViewWithAnimations:(_Bool)arg1;
- (void)showADViewWithModel:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

