//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface MahuaADVModel : NSObject
{
    long long id;
    NSString *_linkUrl;
    long long _targetType;
    NSString *_thumbnailUrl;
    NSString *_title;
    long long _videoInfoId;
    long long _showPosition;
    NSString *_slaveTitle;
}

@property(copy, nonatomic) NSString *slaveTitle; // @synthesize slaveTitle=_slaveTitle;
@property(nonatomic) long long showPosition; // @synthesize showPosition=_showPosition;
@property(nonatomic) long long videoInfoId; // @synthesize videoInfoId=_videoInfoId;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(copy, nonatomic) NSString *thumbnailUrl; // @synthesize thumbnailUrl=_thumbnailUrl;
@property(nonatomic) long long targetType; // @synthesize targetType=_targetType;
@property(copy, nonatomic) NSString *linkUrl; // @synthesize linkUrl=_linkUrl;
@property(nonatomic) long long id; // @synthesize id;
- (void).cxx_destruct;

@end

