//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface MahuaPlayedRecordTool : NSObject
{
}

+ (void)clearAllRecords;
+ (_Bool)saveAllRecords:(id)arg1;
+ (id)readAllRecords;
+ (void)writeRecord:(id)arg1;
+ (id)path;
+ (long long)readTelevisionSetsPlayedCount:(id)arg1;

@end

