//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITabBar.h"

@class UIButton;

@interface MahuaTabBar : UITabBar
{
    UIButton *_firstBtn;
    UIButton *_secondBtn;
    UIButton *_thirdBtn;
    UIButton *_fourthBtn;
    UIButton *_fifthBtn;
}

@property(retain, nonatomic) UIButton *fifthBtn; // @synthesize fifthBtn=_fifthBtn;
@property(retain, nonatomic) UIButton *fourthBtn; // @synthesize fourthBtn=_fourthBtn;
@property(retain, nonatomic) UIButton *thirdBtn; // @synthesize thirdBtn=_thirdBtn;
@property(retain, nonatomic) UIButton *secondBtn; // @synthesize secondBtn=_secondBtn;
@property(retain, nonatomic) UIButton *firstBtn; // @synthesize firstBtn=_firstBtn;
- (void).cxx_destruct;
- (void)initView;
- (id)init;

@end

