//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MahuaCommentToolBar, NSString;

@protocol MahuaCommentToolBarDelegate <NSObject>
- (void)sendCommentToolBar:(MahuaCommentToolBar *)arg1 text:(NSString *)arg2;
- (void)changeHeightCommentToolBar:(MahuaCommentToolBar *)arg1 height:(double)arg2;
- (void)endEditingCommentToolBar:(MahuaCommentToolBar *)arg1;
- (_Bool)beginEditingCommentToolBar:(MahuaCommentToolBar *)arg1;
@end

