//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class UIImageView, UILabel;

@interface MahuaRankTableViewCell : UITableViewCell
{
    UIImageView *_numView;
    UILabel *_titleLabel;
    UILabel *_tabLabel;
    UIImageView *_rankView;
}

@property(retain, nonatomic) UIImageView *rankView; // @synthesize rankView=_rankView;
@property(retain, nonatomic) UILabel *tabLabel; // @synthesize tabLabel=_tabLabel;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UIImageView *numView; // @synthesize numView=_numView;
- (void).cxx_destruct;
- (void)configCellWithModel:(id)arg1 NSIndexPath:(id)arg2;
- (void)createUI;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

