//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIButton, UILabel;

@interface MahuaTryPlayView : UIView
{
    CDUnknownBlockType _buyAction;
    UILabel *_textLab;
    UIButton *_buyBtn;
}

@property(retain, nonatomic) UIButton *buyBtn; // @synthesize buyBtn=_buyBtn;
@property(retain, nonatomic) UILabel *textLab; // @synthesize textLab=_textLab;
@property(copy, nonatomic) CDUnknownBlockType buyAction; // @synthesize buyAction=_buyAction;
- (void).cxx_destruct;
- (void)hidden;
- (void)show;
- (void)buyBtnClick;
- (void)setupUI;
- (id)initWithFrame:(struct CGRect)arg1;

@end

