//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"

@class NSMutableArray;

@interface MahuaRandomBarrage : NSObject <NSCoding>
{
    NSMutableArray *_type4;
    NSMutableArray *_type3;
    NSMutableArray *_type2;
    NSMutableArray *_type1;
}

+ (id)mj_objectClassInArray;
@property(retain, nonatomic) NSMutableArray *type1; // @synthesize type1=_type1;
@property(retain, nonatomic) NSMutableArray *type2; // @synthesize type2=_type2;
@property(retain, nonatomic) NSMutableArray *type3; // @synthesize type3=_type3;
@property(retain, nonatomic) NSMutableArray *type4; // @synthesize type4=_type4;
- (void).cxx_destruct;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;

@end

