//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "MahuaCommentADCellDelegate.h"
#import "MahuaCommentCellDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class MahuaRefreshFooter, NSMutableArray, NSMutableDictionary, NSString, UITableView, UnderLineBtn;

@interface MahuaCommentView : UIView <UITableViewDelegate, UITableViewDataSource, MahuaCommentCellDelegate, MahuaCommentADCellDelegate>
{
    CDUnknownBlockType _closeClickBlock;
    CDUnknownBlockType _detailClickBlock;
    id <MahuaCommentProtocol> _commentDelegate;
    long long _endRefreshType;
    NSMutableDictionary *_dataDictM;
    UIView *_firstHeaderView;
    UITableView *_tableView;
    MahuaRefreshFooter *_footer;
    long long _type;
    CDUnknownBlockType _selectedCommentType;
    CDUnknownBlockType _clickAD;
    UIView *_hotHeaderView;
    UIView *_rankHeaderView;
    UnderLineBtn *_hotbtn;
    UnderLineBtn *_newbtn;
    NSMutableArray *_thirdBootadsList;
}

@property(retain, nonatomic) NSMutableArray *thirdBootadsList; // @synthesize thirdBootadsList=_thirdBootadsList;
@property(retain, nonatomic) UnderLineBtn *newbtn; // @synthesize newbtn=_newbtn;
@property(retain, nonatomic) UnderLineBtn *hotbtn; // @synthesize hotbtn=_hotbtn;
@property(retain, nonatomic) UIView *rankHeaderView; // @synthesize rankHeaderView=_rankHeaderView;
@property(retain, nonatomic) UIView *hotHeaderView; // @synthesize hotHeaderView=_hotHeaderView;
@property(copy, nonatomic) CDUnknownBlockType clickAD; // @synthesize clickAD=_clickAD;
@property(copy, nonatomic) CDUnknownBlockType selectedCommentType; // @synthesize selectedCommentType=_selectedCommentType;
@property(nonatomic) long long type; // @synthesize type=_type;
@property(retain, nonatomic) MahuaRefreshFooter *footer; // @synthesize footer=_footer;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
@property(retain, nonatomic) UIView *firstHeaderView; // @synthesize firstHeaderView=_firstHeaderView;
@property(retain, nonatomic) NSMutableDictionary *dataDictM; // @synthesize dataDictM=_dataDictM;
@property(nonatomic) long long endRefreshType; // @synthesize endRefreshType=_endRefreshType;
@property(nonatomic) __weak id <MahuaCommentProtocol> commentDelegate; // @synthesize commentDelegate=_commentDelegate;
@property(copy, nonatomic) CDUnknownBlockType detailClickBlock; // @synthesize detailClickBlock=_detailClickBlock;
@property(copy, nonatomic) CDUnknownBlockType closeClickBlock; // @synthesize closeClickBlock=_closeClickBlock;
- (void).cxx_destruct;
- (void)scrollToTheTop;
- (void)reload;
- (id)buttonWithFrame:(struct CGRect)arg1 fontSize:(double)arg2 text:(id)arg3 textColor:(id)arg4 target:(id)arg5 action:(SEL)arg6;
- (void)newBtnClick:(id)arg1;
- (void)hotBtnClick:(id)arg1;
- (void)changeFootRefreshState:(long long)arg1;
- (void)p_loadMoreData;
- (void)p_closeBtnAction;
- (id)p_fetchCommentModelWithCommentCell:(id)arg1;
- (void)jumpCommentDetailMahuaCommentCell:(id)arg1;
- (void)zanCommentMahuaCommentCell:(id)arg1;
- (void)ClickADCell:(id)arg1;
- (void)scrollViewDidScrollToTop:(id)arg1;
- (_Bool)scrollViewShouldScrollToTop:(id)arg1;
- (void)scrollViewDidEndZooming:(id)arg1 withView:(id)arg2 atScale:(double)arg3;
- (void)scrollViewWillBeginZooming:(id)arg1 withView:(id)arg2;
- (void)scrollViewDidEndScrollingAnimation:(id)arg1;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewWillBeginDecelerating:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (void)scrollViewWillEndDragging:(id)arg1 withVelocity:(struct CGPoint)arg2 targetContentOffset:(inout struct CGPoint *)arg3;
- (void)scrollViewDidScroll:(id)arg1;
- (void)scrollViewDidZoom:(id)arg1;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)getADDate;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

