//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"

@class NSString;

@interface MahuaRandomBarrageRule : NSObject <NSCoding>
{
    NSString *_ID;
    long long _limitNum;
    long long _limitUp;
    long long _limitDown;
    long long _isOpen;
    long long _updateTime;
    long long _timeStart;
    long long _timeEnd;
    long long _shelfStartDate;
    long long _shelfEndDate;
    long long _type;
}

+ (id)mj_replacedKeyFromPropertyName;
@property(nonatomic) long long type; // @synthesize type=_type;
@property(nonatomic) long long shelfEndDate; // @synthesize shelfEndDate=_shelfEndDate;
@property(nonatomic) long long shelfStartDate; // @synthesize shelfStartDate=_shelfStartDate;
@property(nonatomic) long long timeEnd; // @synthesize timeEnd=_timeEnd;
@property(nonatomic) long long timeStart; // @synthesize timeStart=_timeStart;
@property(nonatomic) long long updateTime; // @synthesize updateTime=_updateTime;
@property(nonatomic) long long isOpen; // @synthesize isOpen=_isOpen;
@property(nonatomic) long long limitDown; // @synthesize limitDown=_limitDown;
@property(nonatomic) long long limitUp; // @synthesize limitUp=_limitUp;
@property(nonatomic) long long limitNum; // @synthesize limitNum=_limitNum;
@property(copy, nonatomic) NSString *ID; // @synthesize ID=_ID;
- (void).cxx_destruct;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;

@end

