//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class MahuaCommentModel, NSIndexPath, UIButton, UIImageView, UILabel;

@interface MahuaCommentDetailCell : UITableViewCell
{
    MahuaCommentModel *_commentModel;
    NSIndexPath *_currentIndexPath;
    id <MahuaCommentDetailCellDelegate> _delegate;
    UIImageView *_avatar_imgView;
    UILabel *_name_label;
    UIButton *_zan_btn;
    UILabel *_zanCount_label;
    UIButton *_reply_btn;
    UILabel *_time_label;
    UILabel *_content_label;
}

@property(retain, nonatomic) UILabel *content_label; // @synthesize content_label=_content_label;
@property(retain, nonatomic) UILabel *time_label; // @synthesize time_label=_time_label;
@property(retain, nonatomic) UIButton *reply_btn; // @synthesize reply_btn=_reply_btn;
@property(retain, nonatomic) UILabel *zanCount_label; // @synthesize zanCount_label=_zanCount_label;
@property(retain, nonatomic) UIButton *zan_btn; // @synthesize zan_btn=_zan_btn;
@property(retain, nonatomic) UILabel *name_label; // @synthesize name_label=_name_label;
@property(retain, nonatomic) UIImageView *avatar_imgView; // @synthesize avatar_imgView=_avatar_imgView;
@property(nonatomic) __weak id <MahuaCommentDetailCellDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) NSIndexPath *currentIndexPath; // @synthesize currentIndexPath=_currentIndexPath;
@property(retain, nonatomic) MahuaCommentModel *commentModel; // @synthesize commentModel=_commentModel;
- (void).cxx_destruct;
- (void)replyBtnAction;
- (void)zanBtnAction:(id)arg1;
- (void)p_initUI;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

