//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class NSMutableArray, UIImageView, UILabel, UIView;

@interface MahuaDownloadedCell : UITableViewCell
{
    UILabel *_timeLabel;
    UIImageView *_imageV;
    UIImageView *_zheImageV;
    UIImageView *_teleImageV;
    UILabel *_fileNameLabel;
    UILabel *_sizeLabel;
    UILabel *_lookedLabel;
    UIView *_bottomV;
    UILabel *_countLabel;
    UIView *_bgV;
    NSMutableArray *_arr;
}

+ (id)createCellWithTableView:(id)arg1;
@property(retain, nonatomic) NSMutableArray *arr; // @synthesize arr=_arr;
@property(nonatomic) __weak UIView *bgV; // @synthesize bgV=_bgV;
@property(nonatomic) __weak UILabel *countLabel; // @synthesize countLabel=_countLabel;
@property(nonatomic) __weak UIView *bottomV; // @synthesize bottomV=_bottomV;
@property(nonatomic) __weak UILabel *lookedLabel; // @synthesize lookedLabel=_lookedLabel;
@property(nonatomic) __weak UILabel *sizeLabel; // @synthesize sizeLabel=_sizeLabel;
@property(nonatomic) __weak UILabel *fileNameLabel; // @synthesize fileNameLabel=_fileNameLabel;
@property(nonatomic) __weak UIImageView *teleImageV; // @synthesize teleImageV=_teleImageV;
@property(nonatomic) __weak UIImageView *zheImageV; // @synthesize zheImageV=_zheImageV;
@property(nonatomic) __weak UIImageView *imageV; // @synthesize imageV=_imageV;
@property(nonatomic) __weak UILabel *timeLabel; // @synthesize timeLabel=_timeLabel;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (id)thumbnailImageForVideo:(id)arg1 atTime:(double)arg2;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)awakeFromNib;

@end

