//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class UIImageView, UILabel, UIView;

@interface MahuaItemMovieCell : UITableViewCell
{
    UIView *_bgv;
    UILabel *_titleLabel;
    UIImageView *_playIcon;
}

@property(retain, nonatomic) UIImageView *playIcon; // @synthesize playIcon=_playIcon;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UIView *bgv; // @synthesize bgv=_bgv;
- (void).cxx_destruct;
- (void)configcellWithModel:(id)arg1;
- (void)createUI;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

