//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MahuaParentsViewController.h"

#import "WKDelegate.h"
#import "WKNavigationDelegate.h"
#import "WKScriptMessageHandler.h"
#import "WKUIDelegate.h"

@class MahuaShareView, NSString, UIView, WKUserContentController, WKWebView;

@interface MahuaMallWebViewController : MahuaParentsViewController <WKNavigationDelegate, WKUIDelegate, WKScriptMessageHandler, WKDelegate>
{
    _Bool _didWebViewLoadOK;
    WKWebView *_webView;
    WKUserContentController *_userContentController;
    NSString *_urlStr;
    NSString *_titleStr;
    MahuaShareView *_shareView;
    UIView *_BGView2;
}

@property(retain, nonatomic) UIView *BGView2; // @synthesize BGView2=_BGView2;
@property(nonatomic) _Bool didWebViewLoadOK; // @synthesize didWebViewLoadOK=_didWebViewLoadOK;
@property(retain, nonatomic) MahuaShareView *shareView; // @synthesize shareView=_shareView;
@property(retain, nonatomic) NSString *titleStr; // @synthesize titleStr=_titleStr;
@property(retain, nonatomic) NSString *urlStr; // @synthesize urlStr=_urlStr;
@property(retain, nonatomic) WKUserContentController *userContentController; // @synthesize userContentController=_userContentController;
@property(retain, nonatomic) WKWebView *webView; // @synthesize webView=_webView;
- (void).cxx_destruct;
- (void)endFullScreen;
- (void)back;
- (void)begainFullScreen;
- (void)webView:(id)arg1 decidePolicyForNavigationAction:(id)arg2 decisionHandler:(CDUnknownBlockType)arg3;
- (void)webView:(id)arg1 decidePolicyForNavigationResponse:(id)arg2 decisionHandler:(CDUnknownBlockType)arg3;
- (void)webView:(id)arg1 didReceiveServerRedirectForProvisionalNavigation:(id)arg2;
- (void)webView:(id)arg1 didFailProvisionalNavigation:(id)arg2 withError:(id)arg3;
- (void)webView:(id)arg1 didFinishNavigation:(id)arg2;
- (void)webView:(id)arg1 didCommitNavigation:(id)arg2;
- (void)webView:(id)arg1 didStartProvisionalNavigation:(id)arg2;
- (void)shareClickWithDict:(id)arg1;
- (void)userContentController:(id)arg1 didReceiveScriptMessage:(id)arg2;
- (void)dealloc;
- (void)postRequest;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)initWithUrlStr:(id)arg1 andTitle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

