//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class MahuaDownloadPlayerVC, MahuaMoviePlayerVC, NSMutableArray, NSString, UIButton;

@interface MahuaDLNASuspendView : UIView
{
    _Bool _showAirPlay;
    MahuaMoviePlayerVC *_DLNAPlayerVC;
    long long _videoInfoID;
    long long _videoID;
    NSString *_videoLevel;
    NSString *_videoTime;
    NSMutableArray *_device;
    UIButton *_btn;
    CDUnknownBlockType _BackToDLNAPlayVCBlock;
    MahuaDownloadPlayerVC *_DLNADownLoadPlayerVC;
}

+ (id)allocWithZone:(struct _NSZone *)arg1;
+ (id)sharedDLNABtn;
@property(retain, nonatomic) MahuaDownloadPlayerVC *DLNADownLoadPlayerVC; // @synthesize DLNADownLoadPlayerVC=_DLNADownLoadPlayerVC;
@property(copy, nonatomic) CDUnknownBlockType BackToDLNAPlayVCBlock; // @synthesize BackToDLNAPlayVCBlock=_BackToDLNAPlayVCBlock;
@property(retain, nonatomic) UIButton *btn; // @synthesize btn=_btn;
@property(retain, nonatomic) NSMutableArray *device; // @synthesize device=_device;
@property(retain, nonatomic) NSString *videoTime; // @synthesize videoTime=_videoTime;
@property(retain, nonatomic) NSString *videoLevel; // @synthesize videoLevel=_videoLevel;
@property(nonatomic) long long videoID; // @synthesize videoID=_videoID;
@property(nonatomic) long long videoInfoID; // @synthesize videoInfoID=_videoInfoID;
@property(nonatomic) _Bool showAirPlay; // @synthesize showAirPlay=_showAirPlay;
@property(retain, nonatomic) MahuaMoviePlayerVC *DLNAPlayerVC; // @synthesize DLNAPlayerVC=_DLNAPlayerVC;
- (void).cxx_destruct;
- (void)dealloc;
- (void)removePlayerVC;
- (void)pushOwnDLNAPlayVC;
- (void)clickBtn;
- (void)setUp;
- (id)initWithFrame:(struct CGRect)arg1;

@end

