//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MahuaParentsViewController.h"

#import "UICollectionViewDataSource.h"
#import "UICollectionViewDelegate.h"
#import "UICollectionViewDelegateFlowLayout.h"
#import "UIScrollViewDelegate.h"

@class MahuaAllMovieTopChooseView, MahuaAllMovieTopSelectedChooseView, MahuaVoidView, NSMutableArray, NSString, UICollectionView, UIView;

@interface MahuaAllMovieViewController : MahuaParentsViewController <UICollectionViewDelegate, UICollectionViewDataSource, UICollectionViewDelegateFlowLayout, UIScrollViewDelegate>
{
    _Bool _isSelected;
    NSString *_navTitle;
    long long _selectedId;
    UICollectionView *_collectionView;
    NSMutableArray *_titleArray;
    NSMutableArray *_dataArray;
    UIView *_BGView1;
    long long _type;
    long long _topIndex;
    long long _titleIndex;
    long long _title2Index;
    long long _title3Index;
    long long _title4Index;
    long long _title5Index;
    NSString *_topTitle;
    NSString *_title1;
    NSString *_title2;
    NSString *_title3;
    NSString *_title4;
    NSString *_title5;
    NSString *_currentSeletedRowId;
    long long _currentPage;
    MahuaAllMovieTopChooseView *_topChooseView;
    MahuaAllMovieTopSelectedChooseView *_topSelectedView;
    NSMutableArray *_allNavIdArray;
    long long _currentSelectedRow;
    MahuaVoidView *_noNetVoidView;
}

@property(retain, nonatomic) MahuaVoidView *noNetVoidView; // @synthesize noNetVoidView=_noNetVoidView;
@property(nonatomic) long long currentSelectedRow; // @synthesize currentSelectedRow=_currentSelectedRow;
@property(nonatomic) _Bool isSelected; // @synthesize isSelected=_isSelected;
@property(retain, nonatomic) NSMutableArray *allNavIdArray; // @synthesize allNavIdArray=_allNavIdArray;
@property(retain, nonatomic) MahuaAllMovieTopSelectedChooseView *topSelectedView; // @synthesize topSelectedView=_topSelectedView;
@property(retain, nonatomic) MahuaAllMovieTopChooseView *topChooseView; // @synthesize topChooseView=_topChooseView;
@property(nonatomic) long long currentPage; // @synthesize currentPage=_currentPage;
@property(copy, nonatomic) NSString *currentSeletedRowId; // @synthesize currentSeletedRowId=_currentSeletedRowId;
@property(copy, nonatomic) NSString *title5; // @synthesize title5=_title5;
@property(copy, nonatomic) NSString *title4; // @synthesize title4=_title4;
@property(copy, nonatomic) NSString *title3; // @synthesize title3=_title3;
@property(copy, nonatomic) NSString *title2; // @synthesize title2=_title2;
@property(copy, nonatomic) NSString *title1; // @synthesize title1=_title1;
@property(copy, nonatomic) NSString *topTitle; // @synthesize topTitle=_topTitle;
@property(nonatomic) long long title5Index; // @synthesize title5Index=_title5Index;
@property(nonatomic) long long title4Index; // @synthesize title4Index=_title4Index;
@property(nonatomic) long long title3Index; // @synthesize title3Index=_title3Index;
@property(nonatomic) long long title2Index; // @synthesize title2Index=_title2Index;
@property(nonatomic) long long titleIndex; // @synthesize titleIndex=_titleIndex;
@property(nonatomic) long long topIndex; // @synthesize topIndex=_topIndex;
@property(nonatomic) long long type; // @synthesize type=_type;
@property(retain, nonatomic) UIView *BGView1; // @synthesize BGView1=_BGView1;
@property(retain, nonatomic) NSMutableArray *dataArray; // @synthesize dataArray=_dataArray;
@property(retain, nonatomic) NSMutableArray *titleArray; // @synthesize titleArray=_titleArray;
@property(retain, nonatomic) UICollectionView *collectionView; // @synthesize collectionView=_collectionView;
@property(nonatomic) long long selectedId; // @synthesize selectedId=_selectedId;
@property(copy, nonatomic) NSString *navTitle; // @synthesize navTitle=_navTitle;
- (void).cxx_destruct;
- (void)request;
- (void)getMoreRequest;
- (void)setUpGIFRrfresh;
- (void)searchTableVC;
- (void)scrollViewDidScroll:(id)arg1;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (double)collectionView:(id)arg1 layout:(id)arg2 minimumLineSpacingForSectionAtIndex:(long long)arg3;
- (double)collectionView:(id)arg1 layout:(id)arg2 minimumInteritemSpacingForSectionAtIndex:(long long)arg3;
- (id)layoutAttributesForItemAtIndexPath:(id)arg1;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (void)setUpTopView;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;
- (id)initWithType:(long long)arg1 andArray:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

