//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class UIImageView, UILabel, UIView;

@interface MahuaHotItemTableViewCell : UITableViewCell
{
    UILabel *_titleLabel;
    UIImageView *_cover;
    UIImageView *_tapView;
    UILabel *_timeLabel;
    UIImageView *_shareButton;
    UIView *_shareBgv;
    UIView *_line;
    id <MahuaHotItemTableViewCellDelegate> _delegate;
}

@property(nonatomic) __weak id <MahuaHotItemTableViewCellDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) UIView *line; // @synthesize line=_line;
@property(retain, nonatomic) UIView *shareBgv; // @synthesize shareBgv=_shareBgv;
@property(retain, nonatomic) UIImageView *shareButton; // @synthesize shareButton=_shareButton;
@property(retain, nonatomic) UILabel *timeLabel; // @synthesize timeLabel=_timeLabel;
@property(retain, nonatomic) UIImageView *tapView; // @synthesize tapView=_tapView;
@property(retain, nonatomic) UIImageView *cover; // @synthesize cover=_cover;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
- (void).cxx_destruct;
- (void)share:(id)arg1;
- (void)configCellWithModel:(id)arg1;
- (void)createUI;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

