//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIButton.h"

@class NSString, UILabel;

@interface MahuaTagButton : UIButton
{
    _Bool _isMine;
    NSString *_extraText;
    UILabel *_extraL;
}

@property(nonatomic) __weak UILabel *extraL; // @synthesize extraL=_extraL;
@property(nonatomic) _Bool isMine; // @synthesize isMine=_isMine;
@property(copy, nonatomic) NSString *extraText; // @synthesize extraText=_extraText;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (void)awakeFromNib;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)setupUI;

@end

