//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface MahuaGrowthRecordModel : NSObject
{
    NSString *_date;
    long long _extension;
    NSString *_type;
    NSString *_value;
}

@property(retain, nonatomic) NSString *value; // @synthesize value=_value;
@property(retain, nonatomic) NSString *type; // @synthesize type=_type;
@property(nonatomic) long long extension; // @synthesize extension=_extension;
@property(retain, nonatomic) NSString *date; // @synthesize date=_date;
- (void).cxx_destruct;

@end

