//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewCell.h"

@class FLAnimatedImageView, MahuaQueryListModel, UIImageView, UILabel;

@interface MahuaGuessLikeCollectionCell : UICollectionViewCell
{
    _Bool _hideScore;
    _Bool _resetView;
    FLAnimatedImageView *_bgImgView;
    UILabel *_titleLabel;
    UILabel *_subTitleLabel;
    MahuaQueryListModel *_model;
    UILabel *_tagLab;
    UILabel *_scoreLab;
    UILabel *_sortNumLab;
    UIImageView *_coverImage;
}

@property(retain, nonatomic) UIImageView *coverImage; // @synthesize coverImage=_coverImage;
@property(retain, nonatomic) UILabel *sortNumLab; // @synthesize sortNumLab=_sortNumLab;
@property(retain, nonatomic) UILabel *scoreLab; // @synthesize scoreLab=_scoreLab;
@property(nonatomic) _Bool resetView; // @synthesize resetView=_resetView;
@property(nonatomic) _Bool hideScore; // @synthesize hideScore=_hideScore;
@property(retain, nonatomic) UILabel *tagLab; // @synthesize tagLab=_tagLab;
@property(retain, nonatomic) MahuaQueryListModel *model; // @synthesize model=_model;
@property(retain, nonatomic) UILabel *subTitleLabel; // @synthesize subTitleLabel=_subTitleLabel;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) FLAnimatedImageView *bgImgView; // @synthesize bgImgView=_bgImgView;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (void)setUpUI;
- (id)initWithFrame:(struct CGRect)arg1;

@end

