//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface MahuaMyPromotionModel : NSObject
{
    NSString *_nickName;
    NSString *_registerTime;
    NSString *_userId;
}

@property(retain, nonatomic) NSString *userId; // @synthesize userId=_userId;
@property(retain, nonatomic) NSString *registerTime; // @synthesize registerTime=_registerTime;
@property(retain, nonatomic) NSString *nickName; // @synthesize nickName=_nickName;
- (void).cxx_destruct;

@end

