//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UILabel, UISlider;

@interface MahuaBarrageSettingView : UIView
{
    CDUnknownBlockType _closeBarrageSetView;
    CDUnknownBlockType _changeBarrageAlpha;
    CDUnknownBlockType _changeBarrageText;
    CDUnknownBlockType _changeBarrageArea;
    CDUnknownBlockType _changeBarrageSpeed;
    UIView *_barrageView;
    UILabel *_firstValue;
    UILabel *_secondValue;
    UILabel *_thirdValue;
    UILabel *_fourValue;
    UISlider *_firstSlider;
    UISlider *_secondSlider;
    UISlider *_thirdSlider;
    UISlider *_fourSlider;
    long long _level;
}

@property(nonatomic) long long level; // @synthesize level=_level;
@property(retain, nonatomic) UISlider *fourSlider; // @synthesize fourSlider=_fourSlider;
@property(retain, nonatomic) UISlider *thirdSlider; // @synthesize thirdSlider=_thirdSlider;
@property(retain, nonatomic) UISlider *secondSlider; // @synthesize secondSlider=_secondSlider;
@property(retain, nonatomic) UISlider *firstSlider; // @synthesize firstSlider=_firstSlider;
@property(retain, nonatomic) UILabel *fourValue; // @synthesize fourValue=_fourValue;
@property(retain, nonatomic) UILabel *thirdValue; // @synthesize thirdValue=_thirdValue;
@property(retain, nonatomic) UILabel *secondValue; // @synthesize secondValue=_secondValue;
@property(retain, nonatomic) UILabel *firstValue; // @synthesize firstValue=_firstValue;
@property(retain, nonatomic) UIView *barrageView; // @synthesize barrageView=_barrageView;
@property(copy, nonatomic) CDUnknownBlockType changeBarrageSpeed; // @synthesize changeBarrageSpeed=_changeBarrageSpeed;
@property(copy, nonatomic) CDUnknownBlockType changeBarrageArea; // @synthesize changeBarrageArea=_changeBarrageArea;
@property(copy, nonatomic) CDUnknownBlockType changeBarrageText; // @synthesize changeBarrageText=_changeBarrageText;
@property(copy, nonatomic) CDUnknownBlockType changeBarrageAlpha; // @synthesize changeBarrageAlpha=_changeBarrageAlpha;
@property(copy, nonatomic) CDUnknownBlockType closeBarrageSetView; // @synthesize closeBarrageSetView=_closeBarrageSetView;
- (void).cxx_destruct;
- (void)show;
- (void)hide;
- (void)hiddenTapGesture:(id)arg1;
- (void)setupBaseSlider:(id)arg1;
- (void)fourSliderChange:(id)arg1;
- (void)thirdSliderChange:(id)arg1;
- (void)dealWithSecondValue:(id)arg1;
- (void)dealWithFirstValue:(id)arg1;
- (void)secondSliderChanged:(id)arg1;
- (void)secondSliderChange:(id)arg1;
- (void)firstSliderChanged:(id)arg1;
- (void)setupBarrageDetails;
- (void)setupUI;
- (id)initWithFrame:(struct CGRect)arg1;

@end

