//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSMutableArray, NSString, UIButton, UIImage, UIImageView, UILabel;

@interface MahuaImageView : UIView
{
    CDUnknownBlockType _closeAction;
    UIImageView *_picImageView;
    NSString *_type;
    UIButton *_backBtn;
    UIView *_shareView;
    UIImage *_screenShot;
    NSMutableArray *_imageArray;
    NSString *_screenType;
    UIImageView *_coverView;
    NSString *_gifPath;
    UIView *_alterView;
    UILabel *_titleLab;
    UIButton *_cancelBtn;
    UIButton *_goBtn;
    UIView *_coverBGView;
}

@property(retain, nonatomic) UIView *coverBGView; // @synthesize coverBGView=_coverBGView;
@property(retain, nonatomic) UIButton *goBtn; // @synthesize goBtn=_goBtn;
@property(retain, nonatomic) UIButton *cancelBtn; // @synthesize cancelBtn=_cancelBtn;
@property(retain, nonatomic) UILabel *titleLab; // @synthesize titleLab=_titleLab;
@property(retain, nonatomic) UIView *alterView; // @synthesize alterView=_alterView;
@property(retain, nonatomic) NSString *gifPath; // @synthesize gifPath=_gifPath;
@property(retain, nonatomic) UIImageView *coverView; // @synthesize coverView=_coverView;
@property(retain, nonatomic) NSString *screenType; // @synthesize screenType=_screenType;
@property(retain, nonatomic) NSMutableArray *imageArray; // @synthesize imageArray=_imageArray;
@property(retain, nonatomic) UIImage *screenShot; // @synthesize screenShot=_screenShot;
@property(retain, nonatomic) UIView *shareView; // @synthesize shareView=_shareView;
@property(retain, nonatomic) UIButton *backBtn; // @synthesize backBtn=_backBtn;
@property(retain, nonatomic) NSString *type; // @synthesize type=_type;
@property(retain, nonatomic) UIImageView *picImageView; // @synthesize picImageView=_picImageView;
@property(copy, nonatomic) CDUnknownBlockType closeAction; // @synthesize closeAction=_closeAction;
- (void).cxx_destruct;
- (void)hiden;
- (id)imageWithImage:(id)arg1 scaledToSize:(struct CGSize)arg2;
- (void)creatGif;
- (void)shareStickersToWeixinBase:(int)arg1 with:(id)arg2;
- (void)goWechat:(_Bool)arg1;
- (void)image:(id)arg1 didFinishSavingWithError:(id)arg2 contextInfo:(void *)arg3;
- (void)copyNow;
- (void)goWeiBo;
- (void)goQQzone;
- (void)goQQ;
- (void)btnClick:(id)arg1;
- (void)setupShareView;
- (void)showWith:(id)arg1 withImage:(id)arg2;
- (void)goBtnClick;
- (void)cancelBtnClick;
- (void)setupAlterView;
- (void)setupUI;
- (id)initWithFrame:(struct CGRect)arg1;

@end

