//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableAttributedString, NSNumber, NSString;

@interface MahuaCommentModel : NSObject
{
    NSNumber *_approveNum;
    NSString *_avatarUrl;
    NSString *_byIssueUserId;
    NSString *_byIssueUserName;
    NSNumber *_childNum;
    NSString *_content;
    NSNumber *_id;
    NSNumber *_isApprove;
    NSString *_issueTimeStr;
    NSNumber *_issueUserId;
    NSString *_issueUserName;
    NSNumber *_tier;
    NSNumber *_videoInfoId;
    NSString *_videoTitle;
    double _contentHeight;
    double _cellHeigt;
    double _myContentHeight;
    double _myCommentCellHeight;
    NSMutableAttributedString *_showContent;
}

@property(retain, nonatomic) NSMutableAttributedString *showContent; // @synthesize showContent=_showContent;
@property(nonatomic) double myCommentCellHeight; // @synthesize myCommentCellHeight=_myCommentCellHeight;
@property(nonatomic) double myContentHeight; // @synthesize myContentHeight=_myContentHeight;
@property(nonatomic) double cellHeigt; // @synthesize cellHeigt=_cellHeigt;
@property(nonatomic) double contentHeight; // @synthesize contentHeight=_contentHeight;
@property(copy, nonatomic) NSString *videoTitle; // @synthesize videoTitle=_videoTitle;
@property(copy, nonatomic) NSNumber *videoInfoId; // @synthesize videoInfoId=_videoInfoId;
@property(copy, nonatomic) NSNumber *tier; // @synthesize tier=_tier;
@property(copy, nonatomic) NSString *issueUserName; // @synthesize issueUserName=_issueUserName;
@property(copy, nonatomic) NSNumber *issueUserId; // @synthesize issueUserId=_issueUserId;
@property(copy, nonatomic) NSString *issueTimeStr; // @synthesize issueTimeStr=_issueTimeStr;
@property(copy, nonatomic) NSNumber *isApprove; // @synthesize isApprove=_isApprove;
@property(copy, nonatomic) NSNumber *id; // @synthesize id=_id;
@property(copy, nonatomic) NSString *content; // @synthesize content=_content;
@property(copy, nonatomic) NSNumber *childNum; // @synthesize childNum=_childNum;
@property(copy, nonatomic) NSString *byIssueUserName; // @synthesize byIssueUserName=_byIssueUserName;
@property(copy, nonatomic) NSString *byIssueUserId; // @synthesize byIssueUserId=_byIssueUserId;
@property(copy, nonatomic) NSString *avatarUrl; // @synthesize avatarUrl=_avatarUrl;
@property(copy, nonatomic) NSNumber *approveNum; // @synthesize approveNum=_approveNum;
- (void).cxx_destruct;

@end

