//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewCell.h"

@class MahuaAvatarModel, UIButton, UIImageView;

@interface MahuaAvatarCollectionCell : UICollectionViewCell
{
    MahuaAvatarModel *_model;
    MahuaAvatarModel *_testModel;
    UIImageView *_icon;
    UIButton *_select;
}

@property(nonatomic) __weak UIButton *select; // @synthesize select=_select;
@property(nonatomic) __weak UIImageView *icon; // @synthesize icon=_icon;
@property(retain, nonatomic) MahuaAvatarModel *testModel; // @synthesize testModel=_testModel;
@property(retain, nonatomic) MahuaAvatarModel *model; // @synthesize model=_model;
- (void).cxx_destruct;
- (void)awakeFromNib;

@end

