//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewCell.h"

@class MahuaVideoModel, UIButton, UILabel;

@interface MahuaTeleplaySelectCell : UICollectionViewCell
{
    MahuaVideoModel *_videoModel;
    long long _movieType;
    double _WH;
    UILabel *_numberLabel;
    UIButton *_hotButton;
}

@property(retain, nonatomic) UIButton *hotButton; // @synthesize hotButton=_hotButton;
@property(retain, nonatomic) UILabel *numberLabel; // @synthesize numberLabel=_numberLabel;
@property(nonatomic) double WH; // @synthesize WH=_WH;
@property(nonatomic) long long movieType; // @synthesize movieType=_movieType;
@property(retain, nonatomic) MahuaVideoModel *videoModel; // @synthesize videoModel=_videoModel;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (void)setUpUI;
- (id)initWithFrame:(struct CGRect)arg1;

@end

