//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewCell.h"

@class FLAnimatedImageView, UIImageView, UILabel;

@interface MahuaRecommandCollectionViewCellAdv : UICollectionViewCell
{
    FLAnimatedImageView *_cover;
    UILabel *_titleLabel;
    UILabel *_descLabel;
    UILabel *_scoreLabel;
    UIImageView *_shadow;
    UILabel *_tabLabel;
    UIImageView *_adImageV;
}

@property(retain, nonatomic) UIImageView *adImageV; // @synthesize adImageV=_adImageV;
@property(retain, nonatomic) UILabel *tabLabel; // @synthesize tabLabel=_tabLabel;
@property(retain, nonatomic) UIImageView *shadow; // @synthesize shadow=_shadow;
@property(retain, nonatomic) UILabel *scoreLabel; // @synthesize scoreLabel=_scoreLabel;
@property(retain, nonatomic) UILabel *descLabel; // @synthesize descLabel=_descLabel;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) FLAnimatedImageView *cover; // @synthesize cover=_cover;
- (void).cxx_destruct;
- (void)configCellWithModel:(id)arg1;
- (void)createUI;
- (id)initWithFrame:(struct CGRect)arg1;

@end

