//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface MahuaNoticeModel : NSObject
{
    NSString *_ID;
    NSString *_noticeName;
    NSString *_noticeUrl;
    NSString *_ejectionMode;
    NSString *_time;
    NSString *_state;
    NSString *_isDelete;
    NSString *_terminal;
    NSString *_displayWay;
    NSString *_imgUrlWay;
    NSString *_imgAddress;
    NSString *_imgUrl;
    NSString *_startTime;
    NSString *_endTime;
}

+ (id)mj_replacedKeyFromPropertyName;
@property(copy, nonatomic) NSString *endTime; // @synthesize endTime=_endTime;
@property(copy, nonatomic) NSString *startTime; // @synthesize startTime=_startTime;
@property(copy, nonatomic) NSString *imgUrl; // @synthesize imgUrl=_imgUrl;
@property(copy, nonatomic) NSString *imgAddress; // @synthesize imgAddress=_imgAddress;
@property(copy, nonatomic) NSString *imgUrlWay; // @synthesize imgUrlWay=_imgUrlWay;
@property(copy, nonatomic) NSString *displayWay; // @synthesize displayWay=_displayWay;
@property(copy, nonatomic) NSString *terminal; // @synthesize terminal=_terminal;
@property(copy, nonatomic) NSString *isDelete; // @synthesize isDelete=_isDelete;
@property(copy, nonatomic) NSString *state; // @synthesize state=_state;
@property(copy, nonatomic) NSString *time; // @synthesize time=_time;
@property(copy, nonatomic) NSString *ejectionMode; // @synthesize ejectionMode=_ejectionMode;
@property(copy, nonatomic) NSString *noticeUrl; // @synthesize noticeUrl=_noticeUrl;
@property(copy, nonatomic) NSString *noticeName; // @synthesize noticeName=_noticeName;
@property(copy, nonatomic) NSString *ID; // @synthesize ID=_ID;
- (void).cxx_destruct;

@end

