//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface MahuaPostRequest : NSObject
{
}

+ (void)didv3WhilePostRequestWithParameter:(id)arg1 andURL:(id)arg2 andStringSuccessBlock:(CDUnknownBlockType)arg3 andExceptionBlock:(CDUnknownBlockType)arg4 andFailBlock:(CDUnknownBlockType)arg5;
+ (void)postV3RequestWithParameter:(id)arg1 andURL:(id)arg2 andStringSuccessBlock:(CDUnknownBlockType)arg3 andExceptionBlock:(CDUnknownBlockType)arg4 andFailBlock:(CDUnknownBlockType)arg5;

@end

