//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MahuaParentsViewController.h"

#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class MahuaVoidView, NSMutableArray, NSString, UIImageView, UILabel, UITableView;

@interface MahuaGoldRecordViewController : MahuaParentsViewController <UITableViewDelegate, UITableViewDataSource>
{
    _Bool _isRefresh;
    _Bool _isFirstLoadingData;
    CDUnknownBlockType _exitBlock;
    UIImageView *_header;
    UITableView *_tableview;
    NSMutableArray *_datasource;
    UILabel *_goldLabel;
    UIImageView *_goldicon;
    unsigned long long _currentPageIndex;
    MahuaVoidView *_noDataView;
    MahuaVoidView *_noNetView;
}

@property(nonatomic) _Bool isFirstLoadingData; // @synthesize isFirstLoadingData=_isFirstLoadingData;
@property(nonatomic) _Bool isRefresh; // @synthesize isRefresh=_isRefresh;
@property(retain, nonatomic) MahuaVoidView *noNetView; // @synthesize noNetView=_noNetView;
@property(retain, nonatomic) MahuaVoidView *noDataView; // @synthesize noDataView=_noDataView;
@property(nonatomic) unsigned long long currentPageIndex; // @synthesize currentPageIndex=_currentPageIndex;
@property(nonatomic) __weak UIImageView *goldicon; // @synthesize goldicon=_goldicon;
@property(nonatomic) __weak UILabel *goldLabel; // @synthesize goldLabel=_goldLabel;
@property(retain, nonatomic) NSMutableArray *datasource; // @synthesize datasource=_datasource;
@property(retain, nonatomic) UITableView *tableview; // @synthesize tableview=_tableview;
@property(retain, nonatomic) UIImageView *header; // @synthesize header=_header;
@property(copy, nonatomic) CDUnknownBlockType exitBlock; // @synthesize exitBlock=_exitBlock;
- (void).cxx_destruct;
- (void)zuanqian;
- (void)getGoldConsumeRecord;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)setMoreFresh;
- (void)setRefresh;
- (void)setUpTableView;
- (void)setUpHeader;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

