//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"

@class NSArray, NSMutableArray, NSString;

@interface MahuaQueryVideoInfoModel : NSObject <NSCoding>
{
    long long _bootadsFlag;
    long long _esFlag;
    long long _orderNum;
    NSString *_title;
    NSString *_detailTitle;
    long long _columnId;
    long long _isLandscape;
    long long _topNum;
    NSArray *_bootadsList;
    NSMutableArray *_queryList;
    long long _cellHight;
    long long _VIPPageIndex;
    NSMutableArray *_VipDataSource;
    NSString *_videoType;
    NSString *_videoTypeStr;
    long long _currentPage;
    long long _id;
    long long _type;
    long long _headPushSwitch;
    long long _supportSwitch;
    NSString *_picUrl;
    NSMutableArray *_infoBootads;
}

+ (id)mj_objectClassInArray;
@property(retain, nonatomic) NSMutableArray *infoBootads; // @synthesize infoBootads=_infoBootads;
@property(copy, nonatomic) NSString *picUrl; // @synthesize picUrl=_picUrl;
@property(nonatomic) long long supportSwitch; // @synthesize supportSwitch=_supportSwitch;
@property(nonatomic) long long headPushSwitch; // @synthesize headPushSwitch=_headPushSwitch;
@property(nonatomic) long long type; // @synthesize type=_type;
@property(nonatomic) long long id; // @synthesize id=_id;
@property(nonatomic) long long currentPage; // @synthesize currentPage=_currentPage;
@property(copy, nonatomic) NSString *videoTypeStr; // @synthesize videoTypeStr=_videoTypeStr;
@property(copy, nonatomic) NSString *videoType; // @synthesize videoType=_videoType;
@property(retain, nonatomic) NSMutableArray *VipDataSource; // @synthesize VipDataSource=_VipDataSource;
@property(nonatomic) long long VIPPageIndex; // @synthesize VIPPageIndex=_VIPPageIndex;
@property(nonatomic) long long cellHight; // @synthesize cellHight=_cellHight;
@property(retain, nonatomic) NSMutableArray *queryList; // @synthesize queryList=_queryList;
@property(retain, nonatomic) NSArray *bootadsList; // @synthesize bootadsList=_bootadsList;
@property(nonatomic) long long topNum; // @synthesize topNum=_topNum;
@property(nonatomic) long long isLandscape; // @synthesize isLandscape=_isLandscape;
@property(nonatomic) long long columnId; // @synthesize columnId=_columnId;
@property(retain, nonatomic) NSString *detailTitle; // @synthesize detailTitle=_detailTitle;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
@property(nonatomic) long long orderNum; // @synthesize orderNum=_orderNum;
@property(nonatomic) long long esFlag; // @synthesize esFlag=_esFlag;
@property(nonatomic) long long bootadsFlag; // @synthesize bootadsFlag=_bootadsFlag;
- (void).cxx_destruct;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;

@end

