//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@interface MahuaCollectionLeadView : UIView
{
}

+ (id)shareInstance;
- (_Bool)read;
- (void)save;
- (void)tapClick:(id)arg1;
- (_Bool)isShowedThisVersion;
- (void)hide;
- (void)showInView:(id)arg1;

@end

