//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@interface MahuaProgressView : UIView
{
    double _progress;
    UIView *_tView;
}

@property(nonatomic) __weak UIView *tView; // @synthesize tView=_tView;
@property(nonatomic) double progress; // @synthesize progress=_progress;
- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1 bgImageColorString:(id)arg2 andProgressColorStr:(id)arg3;

@end

