//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MJRefreshGifHeader.h"

@class UIImageView;

@interface MahuaHomeRefreshGifHeader : MJRefreshGifHeader
{
    UIImageView *_refreshImage;
}

@property(retain, nonatomic) UIImageView *refreshImage; // @synthesize refreshImage=_refreshImage;
- (void).cxx_destruct;
- (void)placeSubviews;
- (void)prepare;

@end

