//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class FLAnimatedImageView, MahuaQueryListModel, NSLayoutConstraint, UILabel;

@interface MahuaSearchResultCell : UITableViewCell
{
    MahuaQueryListModel *_model;
    MahuaQueryListModel *_model2;
    FLAnimatedImageView *_imageV;
    UILabel *_jifenLabel;
    UILabel *_nameLabel;
    UILabel *_countlabel;
    UILabel *_timelabel;
    UILabel *_doubanLabel;
    NSLayoutConstraint *_jifenWidth;
}

+ (id)createCellWithTableView:(id)arg1;
@property(nonatomic) __weak NSLayoutConstraint *jifenWidth; // @synthesize jifenWidth=_jifenWidth;
@property(nonatomic) __weak UILabel *doubanLabel; // @synthesize doubanLabel=_doubanLabel;
@property(nonatomic) __weak UILabel *timelabel; // @synthesize timelabel=_timelabel;
@property(nonatomic) __weak UILabel *countlabel; // @synthesize countlabel=_countlabel;
@property(nonatomic) __weak UILabel *nameLabel; // @synthesize nameLabel=_nameLabel;
@property(nonatomic) __weak UILabel *jifenLabel; // @synthesize jifenLabel=_jifenLabel;
@property(nonatomic) __weak FLAnimatedImageView *imageV; // @synthesize imageV=_imageV;
@property(retain, nonatomic) MahuaQueryListModel *model2; // @synthesize model2=_model2;
@property(retain, nonatomic) MahuaQueryListModel *model; // @synthesize model=_model;
- (void).cxx_destruct;
- (id)attrStrFrom:(id)arg1 searchStr:(id)arg2;
- (void)awakeFromNib;

@end

