//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class UIButton, UILabel;

@protocol MahuaHotItemDetailCommentCellDelegate <NSObject>
- (void)likeCommentWithRow:(long long)arg1 LikeButton:(UIButton *)arg2 LikeLabel:(UILabel *)arg3 CurrentLikeCount:(long long)arg4;
@end

