//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewCell.h"

@class MahuaQueryListModel, UIImageView, UILabel;

@interface MahuaShowTypeVerticalCell : UICollectionViewCell
{
    UIImageView *_tabView;
    MahuaQueryListModel *_model;
    UIImageView *_imageV;
    UILabel *_titleLabel;
    UILabel *_subjectLabel;
    UILabel *_timeLabel;
    UILabel *_doubanLabel;
}

@property(nonatomic) __weak UILabel *doubanLabel; // @synthesize doubanLabel=_doubanLabel;
@property(nonatomic) __weak UILabel *timeLabel; // @synthesize timeLabel=_timeLabel;
@property(nonatomic) __weak UILabel *subjectLabel; // @synthesize subjectLabel=_subjectLabel;
@property(nonatomic) __weak UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(nonatomic) __weak UIImageView *imageV; // @synthesize imageV=_imageV;
@property(retain, nonatomic) MahuaQueryListModel *model; // @synthesize model=_model;
@property(nonatomic) __weak UIImageView *tabView; // @synthesize tabView=_tabView;
- (void).cxx_destruct;
- (void)awakeFromNib;

@end

