//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "UIScrollViewDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class NSMutableArray, NSString, UIButton, UIScrollView;

@interface MahuaSearchRankView : UIView <UIScrollViewDelegate, UITableViewDelegate, UITableViewDataSource>
{
    id <MahuaSearchRankViewDelegate> _delegate;
    UIScrollView *_scrollView;
    UIView *_clickButtonBgv;
    UIButton *_selectedBtn;
    long long _currentSelectedIndex;
    NSMutableArray *_dataArray;
    NSMutableArray *_bigDataArray;
}

@property(retain, nonatomic) NSMutableArray *bigDataArray; // @synthesize bigDataArray=_bigDataArray;
@property(retain, nonatomic) NSMutableArray *dataArray; // @synthesize dataArray=_dataArray;
@property(nonatomic) long long currentSelectedIndex; // @synthesize currentSelectedIndex=_currentSelectedIndex;
@property(retain, nonatomic) UIButton *selectedBtn; // @synthesize selectedBtn=_selectedBtn;
@property(retain, nonatomic) UIView *clickButtonBgv; // @synthesize clickButtonBgv=_clickButtonBgv;
@property(retain, nonatomic) UIScrollView *scrollView; // @synthesize scrollView=_scrollView;
@property(nonatomic) __weak id <MahuaSearchRankViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)getDataWithCurrentSelectedIndex:(long long)arg1;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)click:(id)arg1;
- (void)refreshUIWithArr:(id)arg1;
- (void)createUI;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

