//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MahuaParentsViewController.h"

@class UILabel;

@interface MahuaTuiSongViewController : MahuaParentsViewController
{
    UILabel *_statusLabel;
}

@property(retain, nonatomic) UILabel *statusLabel; // @synthesize statusLabel=_statusLabel;
- (void).cxx_destruct;
- (void)panduan;
- (void)viewWillAppear:(_Bool)arg1;
- (void)btnClick;
- (void)setUpUI;
- (void)dealloc;
- (void)viewDidLoad;

@end

