//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class MahuaCycleScrollView, NSArray;

@interface MahuaCommentADCell : UITableViewCell
{
    MahuaCycleScrollView *_adView;
    NSArray *_bootadsList;
    id <MahuaCommentADCellDelegate> _delegate;
}

@property(nonatomic) __weak id <MahuaCommentADCellDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) NSArray *bootadsList; // @synthesize bootadsList=_bootadsList;
@property(retain, nonatomic) MahuaCycleScrollView *adView; // @synthesize adView=_adView;
- (void).cxx_destruct;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)awakeFromNib;
- (void)createUI;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

