//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MahuaParentsViewController.h"

#import "MahuaDuiHuanMaHeaderViewDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class MahuaDuiHuanMaHeaderView, MahuaVoidView, NSMutableArray, NSString, UITableView;

@interface MahuaDuiHuanMaViewController : MahuaParentsViewController <UITableViewDelegate, UITableViewDataSource, MahuaDuiHuanMaHeaderViewDelegate>
{
    _Bool _refreshData;
    UITableView *_tableView;
    NSMutableArray *_dataArray;
    MahuaDuiHuanMaHeaderView *_headerView;
    MahuaVoidView *_noNetVoidView;
    MahuaVoidView *_noDataVoidView;
    long long _currentPage;
}

@property(nonatomic) _Bool refreshData; // @synthesize refreshData=_refreshData;
@property(nonatomic) long long currentPage; // @synthesize currentPage=_currentPage;
@property(retain, nonatomic) MahuaVoidView *noDataVoidView; // @synthesize noDataVoidView=_noDataVoidView;
@property(retain, nonatomic) MahuaVoidView *noNetVoidView; // @synthesize noNetVoidView=_noNetVoidView;
@property(retain, nonatomic) MahuaDuiHuanMaHeaderView *headerView; // @synthesize headerView=_headerView;
@property(retain, nonatomic) NSMutableArray *dataArray; // @synthesize dataArray=_dataArray;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
- (void).cxx_destruct;
- (void)exchangeWithExchangeCode:(id)arg1;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)getData;
- (void)getMoreDataRequest;
- (void)createTableView;
- (void)createHeaderView;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

