//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class FLAnimatedImageView, UIButton, UIImageView, UILabel, UIView;

@interface MahuaSeeMoviewRankTableViewCell : UITableViewCell
{
    UILabel *_numberLabel;
    UILabel *_renqiLabel;
    UIImageView *_renqiView;
    FLAnimatedImageView *_cover;
    UILabel *_titleLabel;
    UILabel *_tapLabel;
    UILabel *_introLabel;
    UIButton *_seeButton;
    UIView *_line;
    id <MahuaSeeMoviewRankTableViewCellDelegate> _delegate;
}

@property(nonatomic) __weak id <MahuaSeeMoviewRankTableViewCellDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) UIView *line; // @synthesize line=_line;
@property(retain, nonatomic) UIButton *seeButton; // @synthesize seeButton=_seeButton;
@property(retain, nonatomic) UILabel *introLabel; // @synthesize introLabel=_introLabel;
@property(retain, nonatomic) UILabel *tapLabel; // @synthesize tapLabel=_tapLabel;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) FLAnimatedImageView *cover; // @synthesize cover=_cover;
@property(retain, nonatomic) UIImageView *renqiView; // @synthesize renqiView=_renqiView;
@property(retain, nonatomic) UILabel *renqiLabel; // @synthesize renqiLabel=_renqiLabel;
@property(retain, nonatomic) UILabel *numberLabel; // @synthesize numberLabel=_numberLabel;
- (void).cxx_destruct;
- (void)seeMovie:(id)arg1;
- (void)configCellWithModel:(id)arg1 NSIndexPath:(id)arg2;
- (void)createUI;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

