//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WMPageController.h"

#import "MHSpreadToastViewDelegate.h"

@class MHSpreadAlertView, MahuaVoidView, NSMutableArray, NSString, UIButton, UIImageView, UILabel, UIView;

@interface MahuaRecommadNewNewViewController : WMPageController <MHSpreadToastViewDelegate>
{
    _Bool _firstLoad;
    _Bool _popFromMoviePlayerVC;
    _Bool _isFirstLoadSpreadAlertView;
    unsigned long long _menuViewPosition;
    NSMutableArray *_titleArray;
    UIView *_myNav;
    UIButton *_searchBtn;
    NSMutableArray *_searchHotWordsArray;
    UIButton *_historyBtn;
    UIButton *_downloadBtn;
    UIButton *_allbtn;
    UIImageView *_allView;
    NSMutableArray *_allTitleArray;
    UILabel *_keyWordLabel1;
    UILabel *_keyWordLabel2;
    NSMutableArray *_keyWordsArr;
    long long _currentSelectedIndex;
    NSMutableArray *_classifyNameLengthArr;
    MahuaVoidView *_noNetVoidView;
    NSMutableArray *_searchRankAll;
    NSString *_collectionUpdateTimestamp;
    MHSpreadAlertView *_spreadAlertView;
    UIView *_clickTextView;
}

@property(retain, nonatomic) UIView *clickTextView; // @synthesize clickTextView=_clickTextView;
@property(nonatomic) _Bool isFirstLoadSpreadAlertView; // @synthesize isFirstLoadSpreadAlertView=_isFirstLoadSpreadAlertView;
@property(retain, nonatomic) MHSpreadAlertView *spreadAlertView; // @synthesize spreadAlertView=_spreadAlertView;
@property(nonatomic) _Bool popFromMoviePlayerVC; // @synthesize popFromMoviePlayerVC=_popFromMoviePlayerVC;
@property(nonatomic) _Bool firstLoad; // @synthesize firstLoad=_firstLoad;
@property(copy, nonatomic) NSString *collectionUpdateTimestamp; // @synthesize collectionUpdateTimestamp=_collectionUpdateTimestamp;
@property(retain, nonatomic) NSMutableArray *searchRankAll; // @synthesize searchRankAll=_searchRankAll;
@property(retain, nonatomic) MahuaVoidView *noNetVoidView; // @synthesize noNetVoidView=_noNetVoidView;
@property(retain, nonatomic) NSMutableArray *classifyNameLengthArr; // @synthesize classifyNameLengthArr=_classifyNameLengthArr;
@property(nonatomic) long long currentSelectedIndex; // @synthesize currentSelectedIndex=_currentSelectedIndex;
@property(retain, nonatomic) NSMutableArray *keyWordsArr; // @synthesize keyWordsArr=_keyWordsArr;
@property(retain, nonatomic) UILabel *keyWordLabel2; // @synthesize keyWordLabel2=_keyWordLabel2;
@property(retain, nonatomic) UILabel *keyWordLabel1; // @synthesize keyWordLabel1=_keyWordLabel1;
@property(retain, nonatomic) NSMutableArray *allTitleArray; // @synthesize allTitleArray=_allTitleArray;
@property(retain, nonatomic) UIImageView *allView; // @synthesize allView=_allView;
@property(retain, nonatomic) UIButton *allbtn; // @synthesize allbtn=_allbtn;
@property(retain, nonatomic) UIButton *downloadBtn; // @synthesize downloadBtn=_downloadBtn;
@property(retain, nonatomic) UIButton *historyBtn; // @synthesize historyBtn=_historyBtn;
@property(retain, nonatomic) NSMutableArray *searchHotWordsArray; // @synthesize searchHotWordsArray=_searchHotWordsArray;
@property(retain, nonatomic) UIButton *searchBtn; // @synthesize searchBtn=_searchBtn;
@property(retain, nonatomic) UIView *myNav; // @synthesize myNav=_myNav;
@property(retain, nonatomic) NSMutableArray *titleArray; // @synthesize titleArray=_titleArray;
@property(nonatomic) unsigned long long menuViewPosition; // @synthesize menuViewPosition=_menuViewPosition;
- (void).cxx_destruct;
- (void)junmpToIntroVC;
- (void)AFNReachability:(id)arg1;
- (void)didReceiveMemoryWarning;
- (void)requestShareData;
- (void)closeSpreadViewAction;
- (void)_joinSpreadSystem;
- (void)joinPartnerAction;
- (void)_showSpreadToast;
- (void)_judgeShowSpreadToast;
- (void)refreshSearchBarPlaceHolderWithNavName:(id)arg1;
- (void)passCurrentSeletedIndex:(int)arg1;
- (struct CGRect)pageController:(id)arg1 preferredFrameForContentView:(id)arg2;
- (struct CGRect)pageController:(id)arg1 preferredFrameForMenuView:(id)arg2;
- (double)menuView:(id)arg1 widthForItemAtIndex:(long long)arg2;
- (id)pageController:(id)arg1 viewControllerAtIndex:(long long)arg2;
- (id)pageController:(id)arg1 titleAtIndex:(long long)arg2;
- (long long)numbersOfChildControllersInPageController:(id)arg1;
- (void)goToMoviePlayVCWithPlayId:(long long)arg1;
- (void)goToAllMovieWithText2:(id)arg1;
- (void)goToAllMovieWithText1:(id)arg1;
- (void)goToAllMovie;
- (void)downloadClick;
- (void)historyClick;
- (void)goToSearchVC:(id)arg1;
- (void)setUpNav;
- (void)ADViewDissmiss:(id)arg1;
- (_Bool)isUpdateSystemMessage;
- (void)getCollectionUpdate:(id)arg1;
- (void)getWordsCache;
- (void)getWords;
- (void)navRequestWithPlateId:(long long)arg1 WithType:(id)arg2 SelectedId:(long long)arg3 NavName:(id)arg4;
- (void)getItemCache;
- (void)getItemData;
- (void)postJsonToServer;
- (void)getRequestData;
- (void)dealloc;
- (void)viewDidAppear:(_Bool)arg1;
- (void)didGoExchangeCenter;
- (void)goExchangeCenter;
- (void)goVIP;
- (void)viewDidLoad;
- (void)changeNavSkin:(id)arg1;
- (long long)preferredStatusBarStyle;
- (id)classifyNameArr;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

