//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class NSArray, NSString, UILabel, UITableView, ZFPlayerController;

@interface MahuaAirPlayChangeView : UIView <UITableViewDelegate, UITableViewDataSource>
{
    _Bool _isPortrait;
    NSString *_title;
    NSArray *_dataSouce;
    CDUnknownBlockType _changeBlock;
    ZFPlayerController *_player;
    UILabel *_titleLab;
    UIView *_back;
    UITableView *_table;
}

@property(nonatomic) _Bool isPortrait; // @synthesize isPortrait=_isPortrait;
@property(nonatomic) __weak UITableView *table; // @synthesize table=_table;
@property(nonatomic) __weak UIView *back; // @synthesize back=_back;
@property(nonatomic) __weak UILabel *titleLab; // @synthesize titleLab=_titleLab;
@property(nonatomic) __weak ZFPlayerController *player; // @synthesize player=_player;
@property(copy, nonatomic) CDUnknownBlockType changeBlock; // @synthesize changeBlock=_changeBlock;
@property(retain, nonatomic) NSArray *dataSouce; // @synthesize dataSouce=_dataSouce;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
- (void).cxx_destruct;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)ClickbackView;
- (void)showinView:(id)arg1;
- (void)setUp;
- (id)initWithFullScreen:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

