//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MahuaParentsViewController.h"

#import "MahuaRecommandCollectionHeaderReusableViewDelegate.h"
#import "MahuaTuiJianFootCollectionReusableViewDelegate.h"
#import "MahuaTuiJianHeaderDelegate.h"
#import "MahuaTwoStyleHeaderCollectionReusableViewDelegate.h"
#import "UICollectionViewDataSource.h"
#import "UICollectionViewDelegate.h"
#import "UICollectionViewDelegateFlowLayout.h"

@class MahuaRecommandNewItemModel, MahuaTuiJianHeader, MahuaVoidView, NSMutableArray, NSString, UIButton, UICollectionView, UIView;

@interface MahuaUsualViewController : MahuaParentsViewController <MahuaTuiJianHeaderDelegate, UICollectionViewDelegate, UICollectionViewDataSource, UICollectionViewDelegateFlowLayout, MahuaTwoStyleHeaderCollectionReusableViewDelegate, MahuaTuiJianFootCollectionReusableViewDelegate, MahuaRecommandCollectionHeaderReusableViewDelegate>
{
    _Bool _isRefresh;
    CDUnknownBlockType _refreshSearchHotWord;
    long long _currentSelectedIndex;
    MahuaRecommandNewItemModel *_model;
    long long _typeId;
    long long _supportBanner;
    CDUnknownBlockType _popFromMoviePlayerVC;
    UIView *_myNav;
    UIButton *_searchBtn;
    MahuaTuiJianHeader *_headerView;
    MahuaVoidView *_noNetVoidView;
    NSMutableArray *_dataArray;
    UICollectionView *_collectionView;
    NSMutableArray *_keyWordArr;
    long long _currentPageIndex;
    NSMutableArray *_bannerArr;
    MahuaVoidView *_noDataVoidView;
}

@property(retain, nonatomic) MahuaVoidView *noDataVoidView; // @synthesize noDataVoidView=_noDataVoidView;
@property(retain, nonatomic) NSMutableArray *bannerArr; // @synthesize bannerArr=_bannerArr;
@property(nonatomic) _Bool isRefresh; // @synthesize isRefresh=_isRefresh;
@property(nonatomic) long long currentPageIndex; // @synthesize currentPageIndex=_currentPageIndex;
@property(retain, nonatomic) NSMutableArray *keyWordArr; // @synthesize keyWordArr=_keyWordArr;
@property(retain, nonatomic) UICollectionView *collectionView; // @synthesize collectionView=_collectionView;
@property(retain, nonatomic) NSMutableArray *dataArray; // @synthesize dataArray=_dataArray;
@property(retain, nonatomic) MahuaVoidView *noNetVoidView; // @synthesize noNetVoidView=_noNetVoidView;
@property(retain, nonatomic) MahuaTuiJianHeader *headerView; // @synthesize headerView=_headerView;
@property(retain, nonatomic) UIButton *searchBtn; // @synthesize searchBtn=_searchBtn;
@property(retain, nonatomic) UIView *myNav; // @synthesize myNav=_myNav;
@property(copy, nonatomic) CDUnknownBlockType popFromMoviePlayerVC; // @synthesize popFromMoviePlayerVC=_popFromMoviePlayerVC;
@property(nonatomic) long long supportBanner; // @synthesize supportBanner=_supportBanner;
@property(nonatomic) long long typeId; // @synthesize typeId=_typeId;
@property(retain, nonatomic) MahuaRecommandNewItemModel *model; // @synthesize model=_model;
@property(nonatomic) long long currentSelectedIndex; // @synthesize currentSelectedIndex=_currentSelectedIndex;
@property(copy, nonatomic) CDUnknownBlockType refreshSearchHotWord; // @synthesize refreshSearchHotWord=_refreshSearchHotWord;
- (void).cxx_destruct;
- (void)didReceiveMemoryWarning;
- (void)changeDataWithCurrentSectionId:(long long)arg1 currentPage:(long long)arg2 GuDingId:(id)arg3 NSIndexPath:(id)arg4 FirstModel:(id)arg5 SaveFirstModel:(_Bool)arg6 TJModel:(id)arg7;
- (void)passTapAdvImageViewModel:(id)arg1;
- (void)changeDataWithNSIndexpath:(id)arg1;
- (void)moreDataWithNSIndexpath:(id)arg1;
- (void)twoheaderMoreDataWithNSIndexpath:(id)arg1;
- (void)headerMoreDataWithNSIndexpath:(id)arg1;
- (void)ClickIndex:(long long)arg1;
- (void)pushToMoviePlayerVCWithID:(long long)arg1 andcolumnId:(id)arg2 fromPage:(long long)arg3;
- (void)adClickWithID:(long long)arg1 type:(id)arg2;
- (void)openUrl:(id)arg1 withTitleStr:(id)arg2 targetType:(long long)arg3;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 referenceSizeForFooterInSection:(long long)arg3;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 referenceSizeForHeaderInSection:(long long)arg3;
- (id)collectionView:(id)arg1 viewForSupplementaryElementOfKind:(id)arg2 atIndexPath:(id)arg3;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (struct UIEdgeInsets)collectionView:(id)arg1 layout:(id)arg2 insetForSectionAtIndex:(long long)arg3;
- (double)collectionView:(id)arg1 layout:(id)arg2 minimumLineSpacingForSectionAtIndex:(long long)arg3;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (long long)numberOfSectionsInCollectionView:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)getMoreDataRequest;
- (void)refreshDataRequest;
- (void)setupRefresh;
- (void)createCollectionView;
- (void)getUsualCache;
- (void)createDataWithPage:(long long)arg1;
- (void)getBannerCache;
- (void)getBannerData;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

