//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSString;

@interface MahuaSeeMovieRankModel : NSObject
{
    NSString *_statu;
    long long _videoInfoId;
    NSString *_title;
    NSArray *_classfiyList;
    NSString *_coverHUrl;
    NSString *_coverUrl;
    NSString *_highCoverHUrl;
    NSString *_highCoverUrl;
    NSString *_intro;
}

@property(copy, nonatomic) NSString *intro; // @synthesize intro=_intro;
@property(copy, nonatomic) NSString *highCoverUrl; // @synthesize highCoverUrl=_highCoverUrl;
@property(copy, nonatomic) NSString *highCoverHUrl; // @synthesize highCoverHUrl=_highCoverHUrl;
@property(copy, nonatomic) NSString *coverUrl; // @synthesize coverUrl=_coverUrl;
@property(copy, nonatomic) NSString *coverHUrl; // @synthesize coverHUrl=_coverHUrl;
@property(copy, nonatomic) NSArray *classfiyList; // @synthesize classfiyList=_classfiyList;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(nonatomic) long long videoInfoId; // @synthesize videoInfoId=_videoInfoId;
@property(copy, nonatomic) NSString *statu; // @synthesize statu=_statu;
- (void).cxx_destruct;

@end

