//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSString;

@interface MahuaNavTitleMoel : NSObject
{
    long long _pId;
    long long _ID;
    NSString *_classifyName;
    long long _level;
    NSArray *_childList;
}

+ (id)mj_objectClassInArray;
+ (id)mj_replacedKeyFromPropertyName;
@property(retain, nonatomic) NSArray *childList; // @synthesize childList=_childList;
@property(nonatomic) long long level; // @synthesize level=_level;
@property(retain, nonatomic) NSString *classifyName; // @synthesize classifyName=_classifyName;
@property(nonatomic) long long ID; // @synthesize ID=_ID;
@property(nonatomic) long long pId; // @synthesize pId=_pId;
- (void).cxx_destruct;

@end

