//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSDate, NSString, NSTimer, UIColor, UIFont, UILabel;

@interface MBProgressHUD : UIView
{
    _Bool useAnimation;
    SEL methodForExecution;
    id targetForExecution;
    id objectForExecution;
    UILabel *label;
    UILabel *middleLabel;
    UILabel *detailsLabel;
    _Bool isFinished;
    struct CGAffineTransform rotationTransform;
    _Bool square;
    _Bool dimBackground;
    _Bool taskInProgress;
    _Bool removeFromSuperViewOnHide;
    int animationType;
    float opacity;
    float xOffset;
    float yOffset;
    float margin;
    float graceTime;
    float minShowTime;
    int mode;
    float progress;
    id <MBProgressHUDDelegate> delegate;
    UIColor *color;
    UIFont *labelFont;
    UIFont *detailsLabelFont;
    UIFont *middleLabelFont;
    UIView *indicator;
    NSTimer *graceTimer;
    NSTimer *minShowTimer;
    UIView *customView;
    NSDate *showStarted;
    NSString *labelText;
    NSString *detailsLabelText;
    NSString *middleLabelText;
    CDUnknownBlockType completionBlock;
    UIColor *_labelTextColor;
    UIColor *_middleLabelTextColor;
    UIColor *_detailsLabelTextColor;
    struct CGSize minSize;
    struct CGSize size;
}

+ (id)allHUDsForView:(id)arg1;
+ (id)HUDForView:(id)arg1;
+ (unsigned long long)hideAllHUDsForView:(id)arg1 animated:(_Bool)arg2;
+ (_Bool)hideHUDForView:(id)arg1 animated:(_Bool)arg2;
+ (id)showHUDAddedTo:(id)arg1 animated:(_Bool)arg2;
+ (void)hideHUD;
+ (void)hideHUDForView:(id)arg1;
+ (id)showMessage:(id)arg1;
+ (void)showError:(id)arg1;
+ (void)showSuccess:(id)arg1;
+ (id)showAnimationAndWords:(id)arg1 toView:(id)arg2;
+ (id)showAnimationForView:(id)arg1;
+ (id)showAnimation;
+ (void)showFourGWords:(id)arg1 toView:(id)arg2;
+ (id)showMessage:(id)arg1 toView:(id)arg2;
+ (void)showWords:(id)arg1 toView:(id)arg2 duration:(long long)arg3;
+ (void)showWords:(id)arg1 toView:(id)arg2 completionBlock:(CDUnknownBlockType)arg3;
+ (void)showTitle:(id)arg1 details:(id)arg2 toView:(id)arg3;
+ (void)showTitle:(id)arg1 andAttributeStrHud:(id)arg2 toView:(id)arg3;
+ (void)showAttributeStrHud:(id)arg1 toView:(id)arg2;
+ (void)showTitle:(id)arg1 titleColor:(id)arg2 middle:(id)arg3 midColor:(id)arg4 details:(id)arg5 toView:(id)arg6 viewColor:(id)arg7;
+ (void)showTitle:(id)arg1 middle:(id)arg2 details:(id)arg3 toView:(id)arg4;
+ (void)showLevelTitle:(id)arg1 middle:(id)arg2 details:(id)arg3 toView:(id)arg4;
+ (void)showDeleteWords:(id)arg1 toView:(id)arg2;
+ (void)showWords:(id)arg1 toView:(id)arg2;
+ (void)showSuccess:(id)arg1 toView:(id)arg2;
+ (void)showError:(id)arg1 toView:(id)arg2;
+ (void)show:(id)arg1 icon:(id)arg2 view:(id)arg3;
@property(retain, nonatomic) UIColor *detailsLabelTextColor; // @synthesize detailsLabelTextColor=_detailsLabelTextColor;
@property(retain, nonatomic) UIColor *middleLabelTextColor; // @synthesize middleLabelTextColor=_middleLabelTextColor;
@property(retain, nonatomic) UIColor *labelTextColor; // @synthesize labelTextColor=_labelTextColor;
@property(copy) CDUnknownBlockType completionBlock; // @synthesize completionBlock;
@property struct CGSize size; // @synthesize size;
@property float progress; // @synthesize progress;
@property(copy) NSString *middleLabelText; // @synthesize middleLabelText;
@property(copy) NSString *detailsLabelText; // @synthesize detailsLabelText;
@property(copy) NSString *labelText; // @synthesize labelText;
@property int mode; // @synthesize mode;
@property(retain) NSDate *showStarted; // @synthesize showStarted;
@property(retain) UIView *customView; // @synthesize customView;
@property _Bool removeFromSuperViewOnHide; // @synthesize removeFromSuperViewOnHide;
@property _Bool taskInProgress; // @synthesize taskInProgress;
@property(retain) NSTimer *minShowTimer; // @synthesize minShowTimer;
@property(retain) NSTimer *graceTimer; // @synthesize graceTimer;
@property float minShowTime; // @synthesize minShowTime;
@property float graceTime; // @synthesize graceTime;
@property _Bool dimBackground; // @synthesize dimBackground;
@property float margin; // @synthesize margin;
@property(getter=isSquare) _Bool square; // @synthesize square;
@property struct CGSize minSize; // @synthesize minSize;
@property float yOffset; // @synthesize yOffset;
@property float xOffset; // @synthesize xOffset;
@property(retain) UIView *indicator; // @synthesize indicator;
@property(retain) UIFont *middleLabelFont; // @synthesize middleLabelFont;
@property(retain) UIFont *detailsLabelFont; // @synthesize detailsLabelFont;
@property(retain) UIFont *labelFont; // @synthesize labelFont;
@property(retain) UIColor *color; // @synthesize color;
@property float opacity; // @synthesize opacity;
@property __weak id <MBProgressHUDDelegate> delegate; // @synthesize delegate;
@property int animationType; // @synthesize animationType;
- (void).cxx_destruct;
- (void)setTransformForCurrentOrientation:(_Bool)arg1;
- (void)deviceOrientationDidChange:(id)arg1;
- (void)unregisterFromNotifications;
- (void)registerForNotifications;
- (void)updateUIForKeypath:(id)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (id)observableKeypaths;
- (void)unregisterFromKVO;
- (void)registerForKVO;
- (void)drawRect:(struct CGRect)arg1;
- (void)layoutSubviews;
- (void)updateIndicators;
- (void)setupLabels;
- (void)cleanUp;
- (void)launchExecution;
- (void)showAnimated:(_Bool)arg1 whileExecutingBlock:(CDUnknownBlockType)arg2 onQueue:(id)arg3 completionBlock:(CDUnknownBlockType)arg4;
- (void)showAnimated:(_Bool)arg1 whileExecutingBlock:(CDUnknownBlockType)arg2 onQueue:(id)arg3;
- (void)showAnimated:(_Bool)arg1 whileExecutingBlock:(CDUnknownBlockType)arg2 completionBlock:(CDUnknownBlockType)arg3;
- (void)showAnimated:(_Bool)arg1 whileExecutingBlock:(CDUnknownBlockType)arg2;
- (void)showWhileExecuting:(SEL)arg1 onTarget:(id)arg2 withObject:(id)arg3 animated:(_Bool)arg4;
- (void)done;
- (void)animationFinished:(id)arg1 finished:(_Bool)arg2 context:(void *)arg3;
- (void)hideUsingAnimation:(_Bool)arg1;
- (void)showUsingAnimation:(_Bool)arg1;
- (void)didMoveToSuperview;
- (void)handleMinShowTimer:(id)arg1;
- (void)handleGraceTimer:(id)arg1;
- (void)hideDelayed:(id)arg1;
- (void)hide:(_Bool)arg1 afterDelay:(double)arg2;
- (void)hide:(_Bool)arg1;
- (void)show:(_Bool)arg1;
- (void)dealloc;
- (id)initWithWindow:(id)arg1;
- (id)initWithView:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

