//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MHRemotePlayer.h"

@class AVPlayer, AVPlayerLayer, UIView;

@interface MHAirplayPlayer : MHRemotePlayer
{
    AVPlayer *_player;
    AVPlayerLayer *_playerLayer;
    UIView *_view;
}

@property(retain, nonatomic) UIView *view; // @synthesize view=_view;
- (void).cxx_destruct;
- (long long)volume;
- (void)setVolume:(long long)arg1;
- (double)currentTime;
- (void)seek:(double)arg1;
- (double)duration;
- (_Bool)isPlaying;
- (void)pause;
- (void)play;
- (void)close;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)start;

@end

