//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class MHBankModel, UILabel;

@interface MHBankListCell : UITableViewCell
{
    MHBankModel *_bankModel;
    UILabel *_label;
}

@property(retain, nonatomic) UILabel *label; // @synthesize label=_label;
@property(copy, nonatomic) MHBankModel *bankModel; // @synthesize bankModel=_bankModel;
- (void).cxx_destruct;
- (void)drawRect:(struct CGRect)arg1;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

