//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MHSpreadBaseVC.h"

@class MHBdingAliContainerView, MHBdingBankContainerView;

@interface MHBdingViewController : MHSpreadBaseVC
{
    long long _type;
    CDUnknownBlockType _bindingBlock;
    CDUnknownBlockType _successBlock;
    MHBdingAliContainerView *_aliContainerView;
    MHBdingBankContainerView *_bankContainerView;
}

@property(retain, nonatomic) MHBdingBankContainerView *bankContainerView; // @synthesize bankContainerView=_bankContainerView;
@property(retain, nonatomic) MHBdingAliContainerView *aliContainerView; // @synthesize aliContainerView=_aliContainerView;
@property(copy, nonatomic) CDUnknownBlockType successBlock; // @synthesize successBlock=_successBlock;
@property(copy, nonatomic) CDUnknownBlockType bindingBlock; // @synthesize bindingBlock=_bindingBlock;
@property(nonatomic) long long type; // @synthesize type=_type;
- (void).cxx_destruct;
- (void)_bindingBank:(id)arg1;
- (void)_requestBindAliAccount:(id)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)initUI;
- (void)changType;
- (void)dealloc;
- (void)setupNav;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;

@end

