//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface MHDelegateModel : NSObject
{
    NSString *_customerAccount;
    NSString *_customerState;
    NSString *_customerType;
    NSString *_ID;
    NSString *_nickname;
    NSString *_operatePerson;
}

+ (id)mj_replacedKeyFromPropertyName;
@property(copy, nonatomic) NSString *operatePerson; // @synthesize operatePerson=_operatePerson;
@property(copy, nonatomic) NSString *nickname; // @synthesize nickname=_nickname;
@property(copy, nonatomic) NSString *ID; // @synthesize ID=_ID;
@property(copy, nonatomic) NSString *customerType; // @synthesize customerType=_customerType;
@property(copy, nonatomic) NSString *customerState; // @synthesize customerState=_customerState;
@property(copy, nonatomic) NSString *customerAccount; // @synthesize customerAccount=_customerAccount;
- (void).cxx_destruct;

@end

