//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CLUPnPDevice, CLUPnPRenderer, NSString;

@interface MHDLNARenderer : NSObject
{
    CLUPnPDevice *_device;
    CLUPnPRenderer *_renderer;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) CLUPnPRenderer *avRenderer;
@property(readonly, nonatomic) NSString *udn;
@property(readonly, nonatomic) NSString *modelName;
@property(readonly, nonatomic) NSString *smallestIcon;
@property(readonly, nonatomic) NSString *friendlyName;
- (id)initWithDevice:(id)arg1;

@end

