//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface MHEventModel : NSObject
{
    long long _id;
    NSString *_jsonString;
    long long _isSending;
}

@property(nonatomic) long long isSending; // @synthesize isSending=_isSending;
@property(copy, nonatomic) NSString *jsonString; // @synthesize jsonString=_jsonString;
@property(nonatomic) long long id; // @synthesize id=_id;
- (void).cxx_destruct;

@end

