//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSNumber;

@interface MHFetchCashModel : NSObject
{
    NSNumber *_alipaySwitch;
    NSNumber *_bankSwitch;
    NSNumber *_maxExchangeMoney;
    NSNumber *_minExchangeMoney;
    NSNumber *_payFee;
    NSNumber *_userDayExchangeFreq;
    NSNumber *_userDayExchangeMoney;
    NSNumber *_userEachExchangeMoney;
    NSNumber *_baseTimesMoney;
}

@property(copy, nonatomic) NSNumber *baseTimesMoney; // @synthesize baseTimesMoney=_baseTimesMoney;
@property(copy, nonatomic) NSNumber *userEachExchangeMoney; // @synthesize userEachExchangeMoney=_userEachExchangeMoney;
@property(copy, nonatomic) NSNumber *userDayExchangeMoney; // @synthesize userDayExchangeMoney=_userDayExchangeMoney;
@property(copy, nonatomic) NSNumber *userDayExchangeFreq; // @synthesize userDayExchangeFreq=_userDayExchangeFreq;
@property(copy, nonatomic) NSNumber *payFee; // @synthesize payFee=_payFee;
@property(copy, nonatomic) NSNumber *minExchangeMoney; // @synthesize minExchangeMoney=_minExchangeMoney;
@property(copy, nonatomic) NSNumber *maxExchangeMoney; // @synthesize maxExchangeMoney=_maxExchangeMoney;
@property(copy, nonatomic) NSNumber *bankSwitch; // @synthesize bankSwitch=_bankSwitch;
@property(copy, nonatomic) NSNumber *alipaySwitch; // @synthesize alipaySwitch=_alipaySwitch;
- (void).cxx_destruct;

@end

