//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MHSpreadBaseVC.h"

#import "UITextFieldDelegate.h"

@class MHBindinfoModel, MHFetchCashModel, NSNumber, NSString, UIButton, UILabel, UITextField, UIView;

@interface MHFetchMoneyVC : MHSpreadBaseVC <UITextFieldDelegate>
{
    long long _fetchType;
    UIButton *_bank_btn;
    UIButton *_ali_btn;
    UIView *_directive_view;
    UIView *_money_view;
    UILabel *_money_label;
    UIButton *_bdingBank_btn;
    UIButton *_bdingAli_btn;
    UIView *_bankView;
    UILabel *_bankName_label;
    UILabel *_bankNumber_label;
    UIView *_aliView;
    UILabel *_aliName_label;
    UILabel *_aliNumber_label;
    UIView *_fetchMoney_view;
    UITextField *_money_textField;
    UIButton *_fetch_btn;
    UILabel *_tip_label;
    MHBindinfoModel *_bindModel;
    NSNumber *_allMoney;
    MHFetchCashModel *_fetchModel;
    UIView *_BGView2;
    UILabel *_rate_label;
    NSString *_sp_defaultTip;
}

@property(copy, nonatomic) NSString *sp_defaultTip; // @synthesize sp_defaultTip=_sp_defaultTip;
@property(retain, nonatomic) UILabel *rate_label; // @synthesize rate_label=_rate_label;
@property(retain, nonatomic) UIView *BGView2; // @synthesize BGView2=_BGView2;
@property(retain, nonatomic) MHFetchCashModel *fetchModel; // @synthesize fetchModel=_fetchModel;
@property(copy, nonatomic) NSNumber *allMoney; // @synthesize allMoney=_allMoney;
@property(retain, nonatomic) MHBindinfoModel *bindModel; // @synthesize bindModel=_bindModel;
@property(retain, nonatomic) UILabel *tip_label; // @synthesize tip_label=_tip_label;
@property(retain, nonatomic) UIButton *fetch_btn; // @synthesize fetch_btn=_fetch_btn;
@property(retain, nonatomic) UITextField *money_textField; // @synthesize money_textField=_money_textField;
@property(retain, nonatomic) UIView *fetchMoney_view; // @synthesize fetchMoney_view=_fetchMoney_view;
@property(retain, nonatomic) UILabel *aliNumber_label; // @synthesize aliNumber_label=_aliNumber_label;
@property(retain, nonatomic) UILabel *aliName_label; // @synthesize aliName_label=_aliName_label;
@property(retain, nonatomic) UIView *aliView; // @synthesize aliView=_aliView;
@property(retain, nonatomic) UILabel *bankNumber_label; // @synthesize bankNumber_label=_bankNumber_label;
@property(retain, nonatomic) UILabel *bankName_label; // @synthesize bankName_label=_bankName_label;
@property(retain, nonatomic) UIView *bankView; // @synthesize bankView=_bankView;
@property(retain, nonatomic) UIButton *bdingAli_btn; // @synthesize bdingAli_btn=_bdingAli_btn;
@property(retain, nonatomic) UIButton *bdingBank_btn; // @synthesize bdingBank_btn=_bdingBank_btn;
@property(retain, nonatomic) UILabel *money_label; // @synthesize money_label=_money_label;
@property(retain, nonatomic) UIView *money_view; // @synthesize money_view=_money_view;
@property(retain, nonatomic) UIView *directive_view; // @synthesize directive_view=_directive_view;
@property(retain, nonatomic) UIButton *ali_btn; // @synthesize ali_btn=_ali_btn;
@property(retain, nonatomic) UIButton *bank_btn; // @synthesize bank_btn=_bank_btn;
@property(nonatomic) long long fetchType; // @synthesize fetchType=_fetchType;
- (void).cxx_destruct;
- (void)didReceiveMemoryWarning;
- (id)_fetchAttributeStringMoney:(id)arg1;
- (void)keyboardWillHide:(id)arg1;
- (void)keyboardWillShow:(id)arg1;
- (void)textFieldDidEndEditing:(id)arg1;
- (void)textFieldDidChanged:(id)arg1;
- (_Bool)isValidEmail:(id)arg1;
- (_Bool)deptNumInputShouldNumber:(id)arg1;
- (_Bool)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)fetchBtnAction;
- (void)bdingWithType:(long long)arg1;
- (void)bdingAliBtnAction;
- (void)bdingBankBtnAction;
- (void)historyAction;
- (void)aliBtnAction:(id)arg1;
- (void)bankBtnAction:(id)arg1;
- (void)_changeViewFetchType:(long long)arg1;
- (void)_initUI;
- (void)_requestData;
- (void)dealloc;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)initWithMoney:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

