//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IJKIOContext.h"

@class MHM3U8Loader;

@interface MHIOContext : IJKIOContext
{
    MHM3U8Loader *_loader;
    Class _loaderClass;
}

@property(retain, nonatomic) Class loaderClass; // @synthesize loaderClass=_loaderClass;
- (void).cxx_destruct;
- (_Bool)openFile:(id)arg1;
- (long long)seek:(long long)arg1 whence:(int)arg2;
- (int)readPacket:(char *)arg1 size:(int)arg2;

@end

