//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface MHIPItem : NSObject
{
    NSString *_ipAddress;
    NSString *_ifaName;
}

@property(retain, nonatomic) NSString *ifaName; // @synthesize ifaName=_ifaName;
@property(retain, nonatomic) NSString *ipAddress; // @synthesize ipAddress=_ipAddress;
- (void).cxx_destruct;

@end

