//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GCDWebServer.h"

@class NSMutableDictionary;

@interface MHLocalServer : GCDWebServer
{
    NSMutableDictionary *_items;
}

+ (id)ipAddresses;
@property(readonly, nonatomic) NSMutableDictionary *items; // @synthesize items=_items;
- (void).cxx_destruct;
- (void)asyncProcessBlock:(id)arg1 complete:(CDUnknownBlockType)arg2;
- (void)stopItem:(id)arg1;
- (void)startItem:(id)arg1 block:(CDUnknownBlockType)arg2;
- (void)startItem:(id)arg1 loaderClass:(Class)arg2 block:(CDUnknownBlockType)arg3;
- (void)dealloc;
- (id)init;

@end

