//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSURLSessionDataDelegate.h"

@class MHResourceSet, NSMutableData, NSObject<OS_dispatch_semaphore>, NSOperationQueue, NSString, NSURL, NSURLSession, NSURLSessionDataTask;

@interface MHM3U8Loader : NSObject <NSURLSessionDataDelegate>
{
    NSObject<OS_dispatch_semaphore> *_semaphore;
    NSOperationQueue *_taskQueue;
    NSURLSession *_session;
    unsigned long long _requestType;
    NSURL *_url;
    NSString *_filePath;
    NSMutableData *_content;
    _Bool _active;
    long long _state;
    const char *_readBuffer;
    unsigned long long _readLength;
    _Bool _readActive;
    unsigned long long _readOffset;
    NSURLSessionDataTask *_dataTask;
    MHResourceSet *_resources;
}

+ (void)setPlaylistValidate:(CDUnknownBlockType)arg1;
@property(readonly, nonatomic) MHResourceSet *resources; // @synthesize resources=_resources;
- (void).cxx_destruct;
- (id)processData:(id)arg1;
- (void)cancel;
- (void)restart;
- (void)URLSession:(id)arg1 task:(id)arg2 didCompleteWithError:(id)arg3;
- (void)URLSession:(id)arg1 dataTask:(id)arg2 didReceiveData:(id)arg3;
- (void)URLSession:(id)arg1 dataTask:(id)arg2 didReceiveResponse:(id)arg3 completionHandler:(CDUnknownBlockType)arg4;
- (unsigned long long)seek:(unsigned long long)arg1 whence:(int)arg2;
- (id)loadAll;
- (int)readData:(char *)arg1 size:(unsigned long long)arg2;
- (int)readLine:(char *)arg1 size:(unsigned long long)arg2;
- (void)open:(id)arg1;
- (id)initWithResources:(id)arg1 queue:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

