//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSNumber, NSString;

@interface MHMarqueeModel : NSObject
{
    NSNumber *_time;
    NSString *_money;
    NSString *_phone;
    NSNumber *_requestTime;
    long long _gapTime;
}

@property(nonatomic) long long gapTime; // @synthesize gapTime=_gapTime;
@property(retain, nonatomic) NSNumber *requestTime; // @synthesize requestTime=_requestTime;
@property(copy, nonatomic) NSString *phone; // @synthesize phone=_phone;
@property(copy, nonatomic) NSString *money; // @synthesize money=_money;
@property(retain, nonatomic) NSNumber *time; // @synthesize time=_time;
- (void).cxx_destruct;
- (id)description;

@end

