//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MHResourceItem, MHResourceSet, NSMutableArray, NSObject<OS_dispatch_semaphore>;

@interface MHResourcePlayItem : NSObject
{
    struct _NSRange _requestRange;
    NSMutableArray *_currentDownloadings;
    CDUnknownBlockType _onComplete;
    long long _currentIndex;
    MHResourceItem *_currentItem;
    NSObject<OS_dispatch_semaphore> *_pauseSemaphore;
    _Bool _active;
    _Bool _isPaused;
    MHResourceSet *_resource;
    unsigned long long _preloadCount;
    long long _playerNumber;
}

@property(readonly, nonatomic) _Bool isPaused; // @synthesize isPaused=_isPaused;
@property(nonatomic) long long playerNumber; // @synthesize playerNumber=_playerNumber;
@property(nonatomic) unsigned long long preloadCount; // @synthesize preloadCount=_preloadCount;
@property(readonly, nonatomic) _Bool active; // @synthesize active=_active;
@property(nonatomic) __weak MHResourceSet *resource; // @synthesize resource=_resource;
- (void).cxx_destruct;
- (void)resume;
- (void)pause;
- (void)requestForward;
- (void)startItem:(id)arg1;
@property(readonly, nonatomic) unsigned long long cachedTo;
- (void)exitPlaying;
- (int)requirePlay:(long long)arg1;
- (void)start;
- (id)init;

@end

