//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSMutableDictionary, NSString, NSTimer, UIButton, UITextView;

@interface MHResourcesManager : NSObject
{
    NSDictionary *_customerHttpHeaders;
    NSString *_cachePath;
    NSMutableDictionary *_resources;
    NSTimer *_time;
    NSMutableDictionary *_currentDownloading;
    NSMutableDictionary *_maskkeys;
    UITextView *_logContentView;
    UIButton *_logCloseButton;
    _Bool _playing;
    unsigned long long _bandwidthLimit;
    unsigned long long _preloadCount;
}

+ (id)instance;
@property(nonatomic) _Bool playing; // @synthesize playing=_playing;
@property(nonatomic) unsigned long long preloadCount; // @synthesize preloadCount=_preloadCount;
@property(nonatomic) unsigned long long bandwidthLimit; // @synthesize bandwidthLimit=_bandwidthLimit;
- (void).cxx_destruct;
- (void)closeTextView;
- (void)showLogs;
- (void)setCustomerHttpHeaders:(id)arg1;
- (id)customerHttpHeaders;
- (void)refreshNetwork;
- (void)clearCache:(unsigned long long)arg1 whiteList:(id)arg2 wantUrl:(id)arg3;
- (void)clearAllAESkeys;
- (id)maskkeyForKey:(id)arg1;
- (void)setAESkey:(id)arg1 forURL:(id)arg2;
- (void)setAESkey:(id)arg1 forKey:(id)arg2;
- (void)clearAllMaskkeys;
- (void)setMaskkey:(unsigned long long)arg1 forURL:(id)arg2;
- (void)setMaskkey:(unsigned long long)arg1 forKey:(id)arg2;
- (void)onResourceSetStoped:(id)arg1;
- (void)onResourceSetStarted:(id)arg1;
- (void)onClock;
- (void)removeResource:(id)arg1;
- (id)resourcesFromURL:(id)arg1;
- (id)keyFromURL:(id)arg1;
- (id)resourcesFromKey:(id)arg1;
- (void)setup:(id)arg1;
- (void)dealloc;
- (id)init;

@end

