//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MHResourcesManager, NSArray, NSMutableArray, NSMutableDictionary, NSObject<OS_dispatch_queue>, NSOperationQueue, NSString;

@interface MHResourceSet : NSObject
{
    NSMutableDictionary *_keyStore;
    struct _NSRange _requestRange;
    NSMutableArray *_currentDownloadings;
    struct list<unsigned long, std::__1::allocator<unsigned long>> _cacheSpeeds;
    unsigned long long _secDownloaded;
    struct mutex _downloadMutex;
    unsigned long long _currentIndex;
    long long _onSeekIndex;
    _Bool _onSeek;
    NSMutableArray *_playItems;
    unsigned char _rStatus;
    NSString *_path;
    NSString *_key;
    NSArray *_items;
    MHResourcesManager *_manager;
    unsigned long long _retryCount;
    unsigned long long _downloadSpeed;
    unsigned long long _diskSize;
    unsigned long long _completeCount;
    NSOperationQueue *_queue;
    id <MHResourceSetDelegate> _delegate;
    unsigned long long _status;
    NSObject<OS_dispatch_queue> *_dispatchQueue;
    NSMutableDictionary *_cryptoCache;
}

@property(readonly, nonatomic) NSMutableDictionary *cryptoCache; // @synthesize cryptoCache=_cryptoCache;
@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *dispatchQueue; // @synthesize dispatchQueue=_dispatchQueue;
@property(readonly, nonatomic) unsigned char rStatus; // @synthesize rStatus=_rStatus;
@property(nonatomic) unsigned long long status; // @synthesize status=_status;
@property(nonatomic) __weak id <MHResourceSetDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) NSOperationQueue *queue; // @synthesize queue=_queue;
@property(readonly, nonatomic) unsigned long long completeCount; // @synthesize completeCount=_completeCount;
@property(readonly, nonatomic) unsigned long long diskSize; // @synthesize diskSize=_diskSize;
@property(readonly, nonatomic) unsigned long long downloadSpeed; // @synthesize downloadSpeed=_downloadSpeed;
@property(nonatomic) unsigned long long retryCount; // @synthesize retryCount=_retryCount;
@property(readonly, nonatomic) __weak MHResourcesManager *manager; // @synthesize manager=_manager;
@property(readonly, nonatomic) NSArray *items; // @synthesize items=_items;
@property(readonly, nonatomic) NSString *key; // @synthesize key=_key;
@property(readonly, nonatomic) NSString *path; // @synthesize path=_path;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)onItemRequestFailed:(id)arg1;
- (void)onItemRequestComplete:(id)arg1 during:(double)arg2;
- (void)onItemRequestStart:(id)arg1;
- (void)onItemDownloaded:(id)arg1 size:(unsigned long long)arg2;
- (void)onClock;
- (void)requestForward:(_Bool)arg1;
- (void)requestForward;
- (void)startDownloadItem:(id)arg1;
- (void)dealloc;
- (void)clearCache;
- (void)loadItemsFromUrl:(id)arg1 loaderClass:(Class)arg2 block:(CDUnknownBlockType)arg3;
- (void)loadItemsFromUrl:(id)arg1 block:(CDUnknownBlockType)arg2;
@property(readonly, nonatomic) float progress;
- (void)seekComplete;
- (id)getPlayItemWithNumber:(long long)arg1;
- (void)onSeek;
- (id)keyStore:(id)arg1;
- (void)start;
- (void)_start;
- (void)stop;
- (void)_stop;
- (_Bool)loadItemsFromDisk:(id)arg1;
- (void)checkDir;
- (void)checkStatus;
@property(readonly, nonatomic) _Bool isDownloading;
@property(readonly, nonatomic) _Bool isPlaying;
- (void)onPlayerItemExit:(id)arg1;
- (id)playItems:(id)arg1 start:(_Bool)arg2;
- (void)setItems:(id)arg1;
- (void)setManager:(id)arg1;
- (id)initWithPath:(id)arg1 key:(id)arg2;

@end

