//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSArray, UIImage, UIScrollView;

@interface MHSpreadBottomShareView : UIView
{
    long long _positionType;
    long long _type;
    UIImage *_shareImg;
    UIScrollView *_scrollView;
    NSArray *_titlesArr;
    NSArray *_imagesArr;
}

@property(retain, nonatomic) NSArray *imagesArr; // @synthesize imagesArr=_imagesArr;
@property(retain, nonatomic) NSArray *titlesArr; // @synthesize titlesArr=_titlesArr;
@property(retain, nonatomic) UIScrollView *scrollView; // @synthesize scrollView=_scrollView;
@property(retain, nonatomic) UIImage *shareImg; // @synthesize shareImg=_shareImg;
@property(nonatomic) long long type; // @synthesize type=_type;
@property(nonatomic) long long positionType; // @synthesize positionType=_positionType;
- (void).cxx_destruct;
- (void)isShareToPengyouquan:(_Bool)arg1;
- (void)shareQQ:(_Bool)arg1;
- (void)shareWeiBo;
- (void)goWeiBo;
- (void)goQQZone;
- (void)goQQ;
- (void)shareBtnClick:(id)arg1;
- (void)createShareBtn:(long long)arg1 frame:(struct CGRect)arg2;
- (void)initSubView;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithCoder:(id)arg1;

@end

