//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class MHSpreadRecordModel, UILabel;

@interface MHSpreadDetailCell : UITableViewCell
{
    MHSpreadRecordModel *_recordModel;
    UILabel *_date_label;
    UILabel *_personCount_label;
    UILabel *_money_label;
    UILabel *_allMoney_label;
}

@property(nonatomic) __weak UILabel *allMoney_label; // @synthesize allMoney_label=_allMoney_label;
@property(nonatomic) __weak UILabel *money_label; // @synthesize money_label=_money_label;
@property(nonatomic) __weak UILabel *personCount_label; // @synthesize personCount_label=_personCount_label;
@property(nonatomic) __weak UILabel *date_label; // @synthesize date_label=_date_label;
@property(retain, nonatomic) MHSpreadRecordModel *recordModel; // @synthesize recordModel=_recordModel;
- (void).cxx_destruct;
- (void)drawRect:(struct CGRect)arg1;
- (void)awakeFromNib;

@end

