//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MHSpreadBaseVC.h"

#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class NSMutableArray, NSString, UITableView, UIView;

@interface MHSpreadDetailVC : MHSpreadBaseVC <UITableViewDelegate, UITableViewDataSource>
{
    UITableView *_tableView;
    long long _currentPage;
    NSMutableArray *_dataAryM;
    UIView *_BGView1;
    UIView *_BGView2;
}

@property(retain, nonatomic) UIView *BGView2; // @synthesize BGView2=_BGView2;
@property(retain, nonatomic) UIView *BGView1; // @synthesize BGView1=_BGView1;
@property(retain, nonatomic) NSMutableArray *dataAryM; // @synthesize dataAryM=_dataAryM;
@property(nonatomic) long long currentPage; // @synthesize currentPage=_currentPage;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
- (void).cxx_destruct;
- (void)didReceiveMemoryWarning;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)_requestData;
- (void)_loadNewData;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

