//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MHSpreadBaseVC.h"

#import "QQShareDelegate.h"
#import "UICollectionViewDataSource.h"
#import "UICollectionViewDelegate.h"
#import "UICollectionViewDelegateFlowLayout.h"
#import "WXDelegate.h"
#import "WeiBoDelegate.h"

@class MHSpreadAppModel, MahuaShareView, NSArray, NSString, UIButton, UICollectionView, UIImageView, UILabel, UIScrollView;

@interface MHSpreadQRCodeVC : MHSpreadBaseVC <UICollectionViewDelegate, UICollectionViewDataSource, UICollectionViewDelegateFlowLayout, WXDelegate, QQShareDelegate, WeiBoDelegate>
{
    UIScrollView *_scrollView;
    UILabel *_method_label;
    UIButton *_back_btn;
    UIImageView *_qrCode_imgView;
    UILabel *_codeTitle_label;
    UILabel *_codeSubTitle_label;
    MHSpreadAppModel *_appModel;
    NSArray *_dataAryM;
    UICollectionView *_rateCollectionView;
    UILabel *_rateDesp_label;
    MahuaShareView *_shareView;
    NSString *_shareString;
}

@property(copy, nonatomic) NSString *shareString; // @synthesize shareString=_shareString;
@property(retain, nonatomic) MahuaShareView *shareView; // @synthesize shareView=_shareView;
@property(retain, nonatomic) UILabel *rateDesp_label; // @synthesize rateDesp_label=_rateDesp_label;
@property(retain, nonatomic) UICollectionView *rateCollectionView; // @synthesize rateCollectionView=_rateCollectionView;
@property(retain, nonatomic) NSArray *dataAryM; // @synthesize dataAryM=_dataAryM;
@property(retain, nonatomic) MHSpreadAppModel *appModel; // @synthesize appModel=_appModel;
@property(retain, nonatomic) UILabel *codeSubTitle_label; // @synthesize codeSubTitle_label=_codeSubTitle_label;
@property(retain, nonatomic) UILabel *codeTitle_label; // @synthesize codeTitle_label=_codeTitle_label;
@property(retain, nonatomic) UIImageView *qrCode_imgView; // @synthesize qrCode_imgView=_qrCode_imgView;
@property(retain, nonatomic) UIButton *back_btn; // @synthesize back_btn=_back_btn;
@property(retain, nonatomic) UILabel *method_label; // @synthesize method_label=_method_label;
@property(retain, nonatomic) UIScrollView *scrollView; // @synthesize scrollView=_scrollView;
- (void).cxx_destruct;
- (void)didReceiveMemoryWarning;
- (void)shareFailByWeiboCode;
- (void)weiboShareSuccessCode:(long long)arg1;
- (void)shareFailByQQCode;
- (void)shareSuccssWithQQCode:(long long)arg1;
- (void)shareFailByCode;
- (void)shareSuccessByCode:(int)arg1;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (void)backBtnAction;
- (void)shareBtnAction;
- (void)_initUI;
- (id)createNonInterpolatedUIImageFormCIImage:(id)arg1 withSize:(double)arg2;
- (void)getImage;
- (void)_requestTaxRate;
- (void)setupUI;
- (void)btn4Click;
- (void)btn2Click;
- (void)btn1Click;
- (void)viewDidLoad;
- (void)loadView;
- (id)initWithAppModel:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

