//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSNumber, NSString;

@interface MHSpreadExchangeModel : NSObject
{
    NSNumber *_account;
    NSNumber *_balance;
    NSString *_createTime;
    NSString *_orderId;
    NSNumber *_status;
}

@property(copy, nonatomic) NSNumber *status; // @synthesize status=_status;
@property(copy, nonatomic) NSString *orderId; // @synthesize orderId=_orderId;
@property(copy, nonatomic) NSString *createTime; // @synthesize createTime=_createTime;
@property(copy, nonatomic) NSNumber *balance; // @synthesize balance=_balance;
@property(copy, nonatomic) NSNumber *account; // @synthesize account=_account;
- (void).cxx_destruct;

@end

