//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class MHSpreadOrderModel, UILabel;

@interface MHSpreadRecordCell : UITableViewCell
{
    MHSpreadOrderModel *_orderModel;
    UILabel *_orderId_label;
    UILabel *_time_label;
    UILabel *_exchange_label;
    UILabel *_over_label;
    UILabel *_state_label;
    UILabel *_real_label;
}

@property(nonatomic) __weak UILabel *real_label; // @synthesize real_label=_real_label;
@property(nonatomic) __weak UILabel *state_label; // @synthesize state_label=_state_label;
@property(nonatomic) __weak UILabel *over_label; // @synthesize over_label=_over_label;
@property(nonatomic) __weak UILabel *exchange_label; // @synthesize exchange_label=_exchange_label;
@property(nonatomic) __weak UILabel *time_label; // @synthesize time_label=_time_label;
@property(nonatomic) __weak UILabel *orderId_label; // @synthesize orderId_label=_orderId_label;
@property(retain, nonatomic) MHSpreadOrderModel *orderModel; // @synthesize orderModel=_orderModel;
- (void).cxx_destruct;
- (void)drawRect:(struct CGRect)arg1;
- (void)awakeFromNib;

@end

