//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UISearchBar.h"

#import "UITextFieldDelegate.h"

@class NSString;

@interface MiddleSearchBar : UISearchBar <UITextFieldDelegate>
{
    double _placeholderWidth;
}

@property(nonatomic) double placeholderWidth; // @synthesize placeholderWidth=_placeholderWidth;
- (_Bool)textFieldShouldEndEditing:(id)arg1;
- (_Bool)textFieldShouldBeginEditing:(id)arg1;
- (void)layoutSubviews;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

