//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface MsgDefault : NSObject
{
}

+ (void)cleanSystemMessageCount;
+ (long long)getSystemMessageCount;
+ (void)setSystemMessageCount:(long long)arg1;
+ (void)cleanFeedBackMessageCount;
+ (long long)getFeedBackMessageCount;
+ (void)setFeedBackMessageCount:(long long)arg1;
+ (void)cleanCommentMessageCount;
+ (long long)getCommentMessageCount;
+ (void)setCommentMessageCount:(long long)arg1;
+ (id)getMessgageRequestLastTime;
+ (void)setMessgageRequestLastTime:(id)arg1;

@end

