//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MahuaParentsViewController.h"

#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class MahuaVoidView, NSMutableArray, NSString, UILabel, UITableView, UIView;

@interface MyInvitionViewController : MahuaParentsViewController <UITableViewDelegate, UITableViewDataSource>
{
    _Bool _isRefresh;
    long long _personCount;
    UITableView *_tableView;
    NSMutableArray *_dataArray;
    UIView *_bgv;
    MahuaVoidView *_noAskFriendView;
    MahuaVoidView *_noWeb;
    UILabel *_personLabel;
    unsigned long long _currentPageIndex;
}

@property(nonatomic) unsigned long long currentPageIndex; // @synthesize currentPageIndex=_currentPageIndex;
@property(retain, nonatomic) UILabel *personLabel; // @synthesize personLabel=_personLabel;
@property(retain, nonatomic) MahuaVoidView *noWeb; // @synthesize noWeb=_noWeb;
@property(retain, nonatomic) MahuaVoidView *noAskFriendView; // @synthesize noAskFriendView=_noAskFriendView;
@property(retain, nonatomic) UIView *bgv; // @synthesize bgv=_bgv;
@property(retain, nonatomic) NSMutableArray *dataArray; // @synthesize dataArray=_dataArray;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
@property(nonatomic) _Bool isRefresh; // @synthesize isRefresh=_isRefresh;
@property(nonatomic) long long personCount; // @synthesize personCount=_personCount;
- (void).cxx_destruct;
- (void)didReceiveMemoryWarning;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)setUpGIFRrfresh;
- (void)createTableView;
- (void)getInviteData;
- (void)askFriend;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

