//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, Reachability;

@interface NetworkStatusTool : NSObject
{
    Reachability *_reachability;
    long long _status;
    NSString *_statusStr;
}

+ (id)allocWithZone:(struct _NSZone *)arg1;
+ (id)shareInstance;
@property(retain, nonatomic) NSString *statusStr; // @synthesize statusStr=_statusStr;
@property(nonatomic) long long status; // @synthesize status=_status;
@property(retain, nonatomic) Reachability *reachability; // @synthesize reachability=_reachability;
- (void).cxx_destruct;
- (id)getNetType;
- (void)realNetworkingStatus:(long long)arg1;
- (void)networkChanged:(id)arg1;
- (void)listenNetWorkingStatus;
- (id)init;

@end

