//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"

@class NSDictionary, NSString;

@interface OpeninstallData : NSObject <NSCopying>
{
    NSDictionary *_data;
    NSString *_channelCode;
}

@property(copy, nonatomic) NSString *channelCode; // @synthesize channelCode=_channelCode;
@property(retain, nonatomic) NSDictionary *data; // @synthesize data=_data;
- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithData:(id)arg1 channelCode:(id)arg2;

@end

