//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class RHScanLineAnimation, RHScanNetAnimation, RHScanViewStyle, UIActivityIndicatorView, UIButton, UIImageView, UILabel;

@interface RHScanView : UIView
{
    RHScanViewStyle *_viewStyle;
    RHScanLineAnimation *_scanLineAnimation;
    RHScanNetAnimation *_scanNetAnimation;
    UIImageView *_scanLineStill;
    UIActivityIndicatorView *_activityView;
    UILabel *_labelReadying;
    UILabel *_tipLab;
    UILabel *_introLab;
    UIButton *_clickBtn;
    struct CGRect _scanRetangleRect;
}

+ (struct CGRect)getZXingScanRectWithPreView:(id)arg1 style:(id)arg2;
+ (struct CGRect)getScanRectWithPreView:(id)arg1 style:(id)arg2;
@property(retain, nonatomic) UIButton *clickBtn; // @synthesize clickBtn=_clickBtn;
@property(retain, nonatomic) UILabel *introLab; // @synthesize introLab=_introLab;
@property(retain, nonatomic) UILabel *tipLab; // @synthesize tipLab=_tipLab;
@property(retain, nonatomic) UILabel *labelReadying; // @synthesize labelReadying=_labelReadying;
@property(retain, nonatomic) UIActivityIndicatorView *activityView; // @synthesize activityView=_activityView;
@property(retain, nonatomic) UIImageView *scanLineStill; // @synthesize scanLineStill=_scanLineStill;
@property(retain, nonatomic) RHScanNetAnimation *scanNetAnimation; // @synthesize scanNetAnimation=_scanNetAnimation;
@property(retain, nonatomic) RHScanLineAnimation *scanLineAnimation; // @synthesize scanLineAnimation=_scanLineAnimation;
@property(nonatomic) struct CGRect scanRetangleRect; // @synthesize scanRetangleRect=_scanRetangleRect;
@property(retain, nonatomic) RHScanViewStyle *viewStyle; // @synthesize viewStyle=_viewStyle;
- (void).cxx_destruct;
- (void)clickBtnClick;
- (struct CGRect)getScanRetangleRect;
- (void)drawScanRect;
- (void)stopScanAnimation;
- (void)startScanAnimation;
- (void)stopDeviceReadying;
- (void)startDeviceReadyingWithText:(id)arg1;
- (void)drawRect:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1 style:(id)arg2;

@end

