//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIImageView;

@interface RHScanNetAnimation : UIView
{
    _Bool isAnimationing;
    UIImageView *_scanImageView;
    struct CGRect _animationRect;
}

@property(retain, nonatomic) UIImageView *scanImageView; // @synthesize scanImageView=_scanImageView;
@property(nonatomic) struct CGRect animationRect; // @synthesize animationRect=_animationRect;
- (void).cxx_destruct;
- (void)stopAnimating;
- (void)dealloc;
- (void)startAnimatingWithRect:(struct CGRect)arg1 InView:(id)arg2 Image:(id)arg3;
- (void)animationDidStop:(id)arg1 finished:(_Bool)arg2;
- (void)stepAnimation;
- (id)init;

@end

