//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "ASIProgressDelegate.h"

@class ASIHTTPRequest, NSString;

@interface SegmentDownloader : NSObject <ASIProgressDelegate>
{
    NSString *_fileName;
    NSString *_filePath;
    NSString *_downloadUrl;
    long long _duration;
    long long _index;
    CDUnknownBlockType _ProgressBlock;
    CDUnknownBlockType _completeblock;
    ASIHTTPRequest *_request;
}

@property(retain, nonatomic) ASIHTTPRequest *request; // @synthesize request=_request;
@property(copy, nonatomic) CDUnknownBlockType completeblock; // @synthesize completeblock=_completeblock;
@property(copy, nonatomic) CDUnknownBlockType ProgressBlock; // @synthesize ProgressBlock=_ProgressBlock;
@property(nonatomic) long long index; // @synthesize index=_index;
@property(nonatomic) long long duration; // @synthesize duration=_duration;
@property(copy, nonatomic) NSString *downloadUrl; // @synthesize downloadUrl=_downloadUrl;
@property(copy, nonatomic) NSString *filePath; // @synthesize filePath=_filePath;
@property(copy, nonatomic) NSString *fileName; // @synthesize fileName=_fileName;
- (void).cxx_destruct;
- (void)request:(id)arg1 didReceiveBytes:(long long)arg2;
- (void)requestFailed:(id)arg1;
- (void)requestFinished:(id)arg1;
- (_Bool)checkIsDownload;
- (void)cancel;
- (void)pause;
- (void)startAndComplete:(CDUnknownBlockType)arg1;
- (void)initDownLoad;
- (id)initWithUrl:(id)arg1 andFilePath:(id)arg2 andFileName:(id)arg3 withDuration:(long long)arg4 withIndex:(long long)arg5;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

