//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, Service;

@interface ServiceDescription : NSObject
{
    NSArray *_actions;
    Service *_service;
}

@property(nonatomic) __weak Service *service; // @synthesize service=_service;
@property(copy, nonatomic) NSArray *actions; // @synthesize actions=_actions;
- (void).cxx_destruct;
- (id)initWithDictionary:(id)arg1;

@end

