//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "UIGestureRecognizerDelegate.h"

@class BorderButton, NSString, SettingSubView;

@interface SettingView : UIView <UIGestureRecognizerDelegate>
{
    UIView *_noramlSettingView;
    UIView *_timeSettingView;
    UIView *_rateSettingView;
    long long _exitAppType;
    double _rate;
    SettingSubView *_rateView;
    SettingSubView *_timeView;
    BorderButton *_rate1Btn;
    BorderButton *_rate1_25Btn;
    BorderButton *_rate1_5Btn;
    BorderButton *_rate2Btn;
    BorderButton *_timeCloseBtn;
    BorderButton *_timePlayEndBtn;
    BorderButton *_time30Btn;
    BorderButton *_time60Btn;
    CDUnknownBlockType _rateChange;
    CDUnknownBlockType _closeAppAfterSomeTime;
}

@property(copy, nonatomic) CDUnknownBlockType closeAppAfterSomeTime; // @synthesize closeAppAfterSomeTime=_closeAppAfterSomeTime;
@property(copy, nonatomic) CDUnknownBlockType rateChange; // @synthesize rateChange=_rateChange;
@property(retain, nonatomic) BorderButton *time60Btn; // @synthesize time60Btn=_time60Btn;
@property(retain, nonatomic) BorderButton *time30Btn; // @synthesize time30Btn=_time30Btn;
@property(retain, nonatomic) BorderButton *timePlayEndBtn; // @synthesize timePlayEndBtn=_timePlayEndBtn;
@property(retain, nonatomic) BorderButton *timeCloseBtn; // @synthesize timeCloseBtn=_timeCloseBtn;
@property(retain, nonatomic) BorderButton *rate2Btn; // @synthesize rate2Btn=_rate2Btn;
@property(retain, nonatomic) BorderButton *rate1_5Btn; // @synthesize rate1_5Btn=_rate1_5Btn;
@property(retain, nonatomic) BorderButton *rate1_25Btn; // @synthesize rate1_25Btn=_rate1_25Btn;
@property(retain, nonatomic) BorderButton *rate1Btn; // @synthesize rate1Btn=_rate1Btn;
@property(retain, nonatomic) SettingSubView *timeView; // @synthesize timeView=_timeView;
@property(retain, nonatomic) SettingSubView *rateView; // @synthesize rateView=_rateView;
@property(nonatomic) double rate; // @synthesize rate=_rate;
@property(nonatomic) long long exitAppType; // @synthesize exitAppType=_exitAppType;
@property(retain, nonatomic) UIView *rateSettingView; // @synthesize rateSettingView=_rateSettingView;
@property(retain, nonatomic) UIView *timeSettingView; // @synthesize timeSettingView=_timeSettingView;
@property(retain, nonatomic) UIView *noramlSettingView; // @synthesize noramlSettingView=_noramlSettingView;
- (void).cxx_destruct;
- (void)rateBtn:(id)arg1;
- (void)timeBtn:(id)arg1;
- (id)createBorderButtonWithFrame:(struct CGRect)arg1 text:(id)arg2 tag:(long long)arg3 selector:(SEL)arg4;
- (void)helpTapGesture:(id)arg1;
- (void)timeTapGesture:(id)arg1;
- (void)rateTapGesture:(id)arg1;
- (id)createSubViewWithCenterPoint:(struct CGPoint)arg1 selector:(SEL)arg2 text:(id)arg3 imgName:(id)arg4;
- (void)hiddenTapGesture:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)hide;
- (void)show;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

