//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSArray, NSMutableArray, NSMutableDictionary, SPPageMenuItem, SPPageMenuScrollView, UIColor, UIFont, UIImageView, UIScrollView;

@interface SPPageMenu : UIView
{
    _Bool _bounces;
    _Bool _alwaysBounceHorizontal;
    _Bool _needTextColorGradients;
    _Bool _showFuntionButton;
    _Bool _closeTrackerFollowingMode;
    _Bool _insert;
    long long _selectedItemIndex;
    long long _trackerStyle;
    double _itemPadding;
    UIColor *_selectedItemTitleColor;
    UIColor *_unSelectedItemTitleColor;
    UIFont *_itemTitleFont;
    UIFont *_selectedItemTitleFont;
    UIFont *_unSelectedItemTitleFont;
    UIScrollView *_bridgeScrollView;
    long long _permutationWay;
    double _trackerWidth;
    long long _trackerFollowingMode;
    UIImageView *_dividingLine;
    double _dividingLineHeight;
    double _selectedItemZoomScale;
    id <SPPageMenuDelegate> _delegate;
    double _funtionButtonshadowOpacity;
    NSArray *_items;
    UIImageView *_tracker;
    double _trackerHeight;
    UIView *_backgroundView;
    UIImageView *_backgroundImageView;
    SPPageMenuScrollView *_itemScrollView;
    SPPageMenuItem *_functionButton;
    NSMutableArray *_buttons;
    SPPageMenuItem *_selectedButton;
    NSMutableDictionary *_setupWidths;
    double _beginOffsetX;
    double _startR;
    double _startG;
    double _startB;
    double _endR;
    double _endG;
    double _endB;
    double _itemScrollViewH;
    struct UIEdgeInsets _contentInset;
}

+ (id)pageMenuWithFrame:(struct CGRect)arg1 trackerStyle:(long long)arg2;
@property(nonatomic) double itemScrollViewH; // @synthesize itemScrollViewH=_itemScrollViewH;
@property(nonatomic) double endB; // @synthesize endB=_endB;
@property(nonatomic) double endG; // @synthesize endG=_endG;
@property(nonatomic) double endR; // @synthesize endR=_endR;
@property(nonatomic) double startB; // @synthesize startB=_startB;
@property(nonatomic) double startG; // @synthesize startG=_startG;
@property(nonatomic) double startR; // @synthesize startR=_startR;
@property(nonatomic) double beginOffsetX; // @synthesize beginOffsetX=_beginOffsetX;
@property(nonatomic) _Bool insert; // @synthesize insert=_insert;
@property(retain, nonatomic) NSMutableDictionary *setupWidths; // @synthesize setupWidths=_setupWidths;
@property(retain, nonatomic) SPPageMenuItem *selectedButton; // @synthesize selectedButton=_selectedButton;
@property(retain, nonatomic) NSMutableArray *buttons; // @synthesize buttons=_buttons;
@property(nonatomic) __weak SPPageMenuItem *functionButton; // @synthesize functionButton=_functionButton;
@property(nonatomic) __weak SPPageMenuScrollView *itemScrollView; // @synthesize itemScrollView=_itemScrollView;
@property(nonatomic) __weak UIImageView *backgroundImageView; // @synthesize backgroundImageView=_backgroundImageView;
@property(nonatomic) __weak UIView *backgroundView; // @synthesize backgroundView=_backgroundView;
@property(nonatomic) double trackerHeight; // @synthesize trackerHeight=_trackerHeight;
@property(retain, nonatomic) UIImageView *tracker; // @synthesize tracker=_tracker;
@property(retain, nonatomic) NSArray *items; // @synthesize items=_items;
@property(nonatomic) _Bool closeTrackerFollowingMode; // @synthesize closeTrackerFollowingMode=_closeTrackerFollowingMode;
@property(nonatomic) double funtionButtonshadowOpacity; // @synthesize funtionButtonshadowOpacity=_funtionButtonshadowOpacity;
@property(nonatomic) _Bool showFuntionButton; // @synthesize showFuntionButton=_showFuntionButton;
@property(nonatomic) __weak id <SPPageMenuDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) _Bool needTextColorGradients; // @synthesize needTextColorGradients=_needTextColorGradients;
@property(nonatomic) double selectedItemZoomScale; // @synthesize selectedItemZoomScale=_selectedItemZoomScale;
@property(nonatomic) double dividingLineHeight; // @synthesize dividingLineHeight=_dividingLineHeight;
@property(retain, nonatomic) UIImageView *dividingLine; // @synthesize dividingLine=_dividingLine;
@property(nonatomic) long long trackerFollowingMode; // @synthesize trackerFollowingMode=_trackerFollowingMode;
@property(nonatomic) double trackerWidth; // @synthesize trackerWidth=_trackerWidth;
@property(nonatomic) _Bool alwaysBounceHorizontal; // @synthesize alwaysBounceHorizontal=_alwaysBounceHorizontal;
@property(nonatomic) _Bool bounces; // @synthesize bounces=_bounces;
@property(nonatomic) struct UIEdgeInsets contentInset; // @synthesize contentInset=_contentInset;
@property(nonatomic) long long permutationWay; // @synthesize permutationWay=_permutationWay;
@property(retain, nonatomic) UIScrollView *bridgeScrollView; // @synthesize bridgeScrollView=_bridgeScrollView;
@property(retain, nonatomic) UIFont *unSelectedItemTitleFont; // @synthesize unSelectedItemTitleFont=_unSelectedItemTitleFont;
@property(retain, nonatomic) UIFont *selectedItemTitleFont; // @synthesize selectedItemTitleFont=_selectedItemTitleFont;
@property(retain, nonatomic) UIFont *itemTitleFont; // @synthesize itemTitleFont=_itemTitleFont;
@property(retain, nonatomic) UIColor *unSelectedItemTitleColor; // @synthesize unSelectedItemTitleColor=_unSelectedItemTitleColor;
@property(retain, nonatomic) UIColor *selectedItemTitleColor; // @synthesize selectedItemTitleColor=_selectedItemTitleColor;
@property(nonatomic) double itemPadding; // @synthesize itemPadding=_itemPadding;
@property(nonatomic) long long trackerStyle; // @synthesize trackerStyle=_trackerStyle;
@property(nonatomic) long long selectedItemIndex; // @synthesize selectedItemIndex=_selectedItemIndex;
- (void).cxx_destruct;
- (void)dealloc;
- (void)resetSetupTrackerFrameWithSelectedButton:(id)arg1;
- (void)layoutSubviews;
@property(readonly, nonatomic) unsigned long long numberOfItems;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)zoomForTitleWithProgress:(double)arg1 fromButton:(id)arg2 toButton:(id)arg3;
- (void)setupEndColor:(id)arg1;
- (void)setupStartColor:(id)arg1;
- (void)getRGBComponents:(double [3])arg1 forColor:(id)arg2;
- (void)colorGradientForTitleWithProgress:(double)arg1 fromButton:(id)arg2 toButton:(id)arg3;
- (void)moveTrackerWithProgress:(double)arg1 fromIndex:(long long)arg2 toIndex:(long long)arg3 currentOffsetX:(double)arg4 beginOffsetX:(double)arg5;
- (void)prepareMoveTrackerFollowScrollView:(id)arg1;
- (void)functionButtonClicked:(id)arg1;
- (void)delegatePerformMethodWithFromIndex:(unsigned long long)arg1 toIndex:(unsigned long long)arg2;
- (void)moveTrackerWithSelectedButton:(id)arg1;
- (void)moveItemScrollViewWithSelectedButton:(id)arg1;
- (void)buttonInPageMenuClicked:(id)arg1;
- (void)setupSubViews;
- (void)initialize;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (_Bool)haveOrNeedsTracker;
- (void)addButton:(long long)arg1 object:(id)arg2 animated:(_Bool)arg3;
- (void)moveTrackerFollowScrollView:(id)arg1;
- (void)setFunctionButtonTitleTextAttributes:(id)arg1 forState:(unsigned long long)arg2;
- (void)setFunctionButtonTitle:(id)arg1 image:(id)arg2 imagePosition:(long long)arg3 imageRatio:(double)arg4 forState:(unsigned long long)arg5;
- (void)setTitle:(id)arg1 image:(id)arg2 imagePosition:(long long)arg3 imageRatio:(double)arg4 forItemIndex:(unsigned long long)arg5;
- (void)setFunctionButtonTitle:(id)arg1 image:(id)arg2 imagePosition:(long long)arg3 imageRatio:(double)arg4 imageTitleSpace:(double)arg5 forState:(unsigned long long)arg6;
- (void)setTitle:(id)arg1 image:(id)arg2 imagePosition:(long long)arg3 imageRatio:(double)arg4 imageTitleSpace:(double)arg5 forItemIndex:(unsigned long long)arg6;
- (void)setTrackerHeight:(double)arg1 cornerRadius:(double)arg2;
- (id)backgroundImageForBarMetrics:(long long)arg1;
- (void)setBackgroundImage:(id)arg1 barMetrics:(long long)arg2;
- (struct UIEdgeInsets)contentEdgeInsetsForItemAtIndex:(unsigned long long)arg1;
- (void)setContentEdgeInsets:(struct UIEdgeInsets)arg1 forItemAtIndex:(unsigned long long)arg2;
- (void)setContentEdgeInsets:(struct UIEdgeInsets)arg1 forForItemAtIndex:(unsigned long long)arg2;
- (double)widthForItemAtIndex:(unsigned long long)arg1;
- (void)setWidth:(double)arg1 forItemAtIndex:(unsigned long long)arg2;
- (_Bool)enabledForItemAtIndex:(unsigned long long)arg1;
- (void)setEnabled:(_Bool)arg1 forItemAtIndex:(unsigned long long)arg2;
- (id)imageForItemAtIndex:(unsigned long long)arg1;
- (void)setImage:(id)arg1 forItemAtIndex:(unsigned long long)arg2;
- (id)titleForItemAtIndex:(unsigned long long)arg1;
- (void)setTitle:(id)arg1 forItemAtIndex:(unsigned long long)arg2;
- (void)removeAllItems;
- (void)removeItemAtIndex:(unsigned long long)arg1 animated:(_Bool)arg2;
- (void)insertItemWithImage:(id)arg1 atIndex:(unsigned long long)arg2 animated:(_Bool)arg3;
- (void)insertItemWithTitle:(id)arg1 atIndex:(unsigned long long)arg2 animated:(_Bool)arg3;
- (void)setItems:(id)arg1 selectedItemIndex:(long long)arg2;
- (id)initWithFrame:(struct CGRect)arg1 trackerStyle:(long long)arg2;

@end

