//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class SPPageMenu, UIButton;

@protocol SPPageMenuDelegate <NSObject>

@optional
- (void)pageMenu:(SPPageMenu *)arg1 functionButtonClicked:(UIButton *)arg2;
- (void)pageMenu:(SPPageMenu *)arg1 itemSelectedFromIndex:(long long)arg2 toIndex:(long long)arg3;
- (void)pageMenu:(SPPageMenu *)arg1 itemSelectedAtIndex:(long long)arg2;
@end

