//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface SubmitTypeListModel : NSObject
{
    NSString *_typeName;
}

@property(retain, nonatomic) NSString *typeName; // @synthesize typeName=_typeName;
- (void).cxx_destruct;

@end

