//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface SWQRCodeManager : NSObject
{
}

+ (void)sw_FlashlightOn:(_Bool)arg1;
+ (id)sw_navigationItemTitleWithType:(long long)arg1;
+ (id)sw_metadataObjectTypesWithType:(long long)arg1;
+ (void)sw_checkAlbumAuthorizationStatusWithGrand:(CDUnknownBlockType)arg1;
+ (void)sw_checkCameraAuthorizationStatusWithGrand:(CDUnknownBlockType)arg1;

@end

