//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class SWQRCodeConfig, UIActivityIndicatorView, UIButton, UIImageView, UILabel;

@interface SWScannerView : UIView
{
    UIImageView *_scannerLine;
    UIActivityIndicatorView *_activityIndicator;
    UIButton *_flashlightBtn;
    UILabel *_flashlightLab;
    UILabel *_tipLab;
    UILabel *_introLab;
    UIButton *_clickBtn;
    SWQRCodeConfig *_config;
}

@property(retain, nonatomic) SWQRCodeConfig *config; // @synthesize config=_config;
@property(retain, nonatomic) UIButton *clickBtn; // @synthesize clickBtn=_clickBtn;
@property(retain, nonatomic) UILabel *introLab; // @synthesize introLab=_introLab;
@property(retain, nonatomic) UILabel *tipLab; // @synthesize tipLab=_tipLab;
@property(retain, nonatomic) UILabel *flashlightLab; // @synthesize flashlightLab=_flashlightLab;
@property(retain, nonatomic) UIButton *flashlightBtn; // @synthesize flashlightBtn=_flashlightBtn;
@property(retain, nonatomic) UIActivityIndicatorView *activityIndicator; // @synthesize activityIndicator=_activityIndicator;
@property(retain, nonatomic) UIImageView *scannerLine; // @synthesize scannerLine=_scannerLine;
- (void).cxx_destruct;
- (void)clickBtnClick;
- (double)scanner_width;
- (double)scanner_y;
- (double)scanner_x;
- (void)drawRect:(struct CGRect)arg1;
- (_Bool)sw_flashlightOn;
- (void)sw_setFlashlightOn:(_Bool)arg1;
- (void)sw_removeActivityIndicator;
- (void)sw_addActivityIndicator;
- (void)sw_hideFlashlightWithAnimated:(_Bool)arg1;
- (void)sw_showFlashlightWithAnimated:(_Bool)arg1;
- (void)sw_pauseScannerLineAnimation;
- (void)sw_addScannerLineAnimation;
- (void)flashlightClicked:(id)arg1;
- (void)_setupUI;
- (id)initWithFrame:(struct CGRect)arg1 config:(id)arg2;

@end

