//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIButton.h"

@interface UIButton (Additions)
+ (id)buttonWithFrame:(struct CGRect)arg1 normalImageStr:(id)arg2 highlightedImageStr:(id)arg3 target:(id)arg4 action:(SEL)arg5;
+ (id)buttonWithFrame:(struct CGRect)arg1 normalImageStr:(id)arg2 selectedImageStr:(id)arg3 target:(id)arg4 action:(SEL)arg5;
+ (id)buttonWithFrame:(struct CGRect)arg1 fontName:(id)arg2 fontSize:(double)arg3 text:(id)arg4 textColor:(id)arg5 target:(id)arg6 action:(SEL)arg7;
+ (id)buttonWithFrame:(struct CGRect)arg1 fontSize:(double)arg2 text:(id)arg3 textColor:(id)arg4 target:(id)arg5 action:(SEL)arg6;
@end

