//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIButton.h"

@interface UIButton (CountDown)
- (void)stopCountDown;
- (void)startWithTime:(long long)arg1 title:(id)arg2 countDownTitle:(id)arg3 mainColor:(id)arg4 countColor:(id)arg5;
@end

