//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITextView.h"

@class NSString, UIColor;

@interface UITextView (ZWPlaceHolder)
+ (void)load;
- (id)cacutDefaultFont;
- (id)zw_placeHolderLabel;
- (void)updatePlaceHolder;
@property(copy, nonatomic) NSString *placeholder;
@property(retain, nonatomic) UIColor *zw_placeHolderColor;
@property(copy, nonatomic) NSString *zw_placeHolder;
- (void)zwPlaceHolder_swizzled_setText:(id)arg1;
- (void)zwPlaceHolder_swizzling_layoutSubviews;
- (void)zwPlaceHolder_swizzled_dealloc;
@end

