//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class MahuaLoadAnimationView, MahuaLoadingView;

@interface UIView (MahuaLoading)
- (void)endToLoading2;
- (void)beginLoading2;
@property(retain, nonatomic) MahuaLoadingView *loadingV;
- (void)endToLoading;
- (void)beginLoading;
@property(retain, nonatomic) MahuaLoadAnimationView *loadingView;
@end

