//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSDictionary, NSString;

@interface UPnPActionResponse : NSObject
{
    long long _statusCode;
    NSString *_respMsg;
    NSString *_errorCode;
    NSString *_errorDescription;
    NSArray *_actions;
    NSDictionary *_xmlDictionary;
}

@property(copy, nonatomic) NSDictionary *xmlDictionary; // @synthesize xmlDictionary=_xmlDictionary;
@property(copy, nonatomic) NSArray *actions; // @synthesize actions=_actions;
@property(copy, nonatomic) NSString *errorDescription; // @synthesize errorDescription=_errorDescription;
@property(copy, nonatomic) NSString *errorCode; // @synthesize errorCode=_errorCode;
@property(copy, nonatomic) NSString *respMsg; // @synthesize respMsg=_respMsg;
@property(nonatomic) long long statusCode; // @synthesize statusCode=_statusCode;
- (void).cxx_destruct;
- (id)description;
- (id)initWithData:(id)arg1;

@end

