//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "UUMarqueeViewTouchResponder.h"

@class NSMutableArray, NSString, NSTimer, UUMarqueeViewTouchReceiver;

@interface UUMarqueeView : UIView <UUMarqueeViewTouchResponder>
{
    _Bool _useDynamicHeight;
    _Bool _stopWhenLessData;
    _Bool _clipsToBounds;
    _Bool _touchEnabled;
    _Bool _isWaiting;
    _Bool _isScrolling;
    _Bool _isScrollNeedsToStop;
    float _scrollSpeed;
    float _itemSpacing;
    float _originalX;
    int _firstItemIndex;
    int _dataIndex;
    id <UUMarqueeViewDelegate> _delegate;
    double _timeIntervalPerScroll;
    double _timeDurationPerScroll;
    unsigned long long _direction;
    UIView *_contentView;
    long long _visibleItemCount;
    NSMutableArray *_items;
    NSTimer *_scrollTimer;
    UUMarqueeViewTouchReceiver *_touchReceiver;
    long long _scrollerIndex;
}

@property(nonatomic) long long scrollerIndex; // @synthesize scrollerIndex=_scrollerIndex;
@property(nonatomic) _Bool isScrollNeedsToStop; // @synthesize isScrollNeedsToStop=_isScrollNeedsToStop;
@property(nonatomic) _Bool isScrolling; // @synthesize isScrolling=_isScrolling;
@property(nonatomic) _Bool isWaiting; // @synthesize isWaiting=_isWaiting;
@property(retain, nonatomic) UUMarqueeViewTouchReceiver *touchReceiver; // @synthesize touchReceiver=_touchReceiver;
@property(retain, nonatomic) NSTimer *scrollTimer; // @synthesize scrollTimer=_scrollTimer;
@property(nonatomic) int dataIndex; // @synthesize dataIndex=_dataIndex;
@property(nonatomic) int firstItemIndex; // @synthesize firstItemIndex=_firstItemIndex;
@property(retain, nonatomic) NSMutableArray *items; // @synthesize items=_items;
@property(nonatomic) long long visibleItemCount; // @synthesize visibleItemCount=_visibleItemCount;
@property(retain, nonatomic) UIView *contentView; // @synthesize contentView=_contentView;
@property(nonatomic) unsigned long long direction; // @synthesize direction=_direction;
@property(nonatomic, getter=isTouchEnabled) _Bool touchEnabled; // @synthesize touchEnabled=_touchEnabled;
@property(nonatomic) _Bool clipsToBounds; // @synthesize clipsToBounds=_clipsToBounds;
@property(nonatomic) float originalX; // @synthesize originalX=_originalX;
@property(nonatomic) _Bool stopWhenLessData; // @synthesize stopWhenLessData=_stopWhenLessData;
@property(nonatomic) float itemSpacing; // @synthesize itemSpacing=_itemSpacing;
@property(nonatomic) float scrollSpeed; // @synthesize scrollSpeed=_scrollSpeed;
@property(nonatomic) _Bool useDynamicHeight; // @synthesize useDynamicHeight=_useDynamicHeight;
@property(nonatomic) double timeDurationPerScroll; // @synthesize timeDurationPerScroll=_timeDurationPerScroll;
@property(nonatomic) double timeIntervalPerScroll; // @synthesize timeIntervalPerScroll=_timeIntervalPerScroll;
@property(nonatomic) __weak id <UUMarqueeViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)touchAtPoint:(struct CGPoint)arg1;
- (void)resetTouchReceiver;
- (void)moveToNextDataIndex;
- (void)scrollTimerDidFire:(id)arg1;
- (void)updateItemView:(id)arg1 atIndex:(long long)arg2;
- (void)createItemView:(id)arg1;
- (double)itemHeightAtIndex:(long long)arg1;
- (double)itemWidthAtIndex:(long long)arg1;
- (void)moveToNextItemIndex;
- (int)itemIndexWithOffsetFromTop:(int)arg1;
- (void)repositionItemViews;
- (void)resetAll;
- (void)dealloc;
- (void)layoutSubviews;
- (void)startAfterTimeInterval:(_Bool)arg1;
- (void)destory;
- (void)repeat;
- (void)pause;
- (void)start;
- (void)reloadData;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1 direction:(unsigned long long)arg2;
- (id)initWithDirection:(unsigned long long)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

