//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "WMMenuItemDelegate.h"

@class NSArray, NSMutableArray, NSString, UIColor, UIScrollView, WMMenuItem, WMProgressView;

@interface WMMenuView : UIView <WMMenuItemDelegate>
{
    _Bool _showDownLine;
    _Bool _progressViewIsNaughty;
    _Bool _showOnNavigationBar;
    double _progressHeight;
    double _progressViewCornerRadius;
    NSArray *_progressWidths;
    WMProgressView *_progressView;
    unsigned long long _style;
    unsigned long long _layoutMode;
    double _contentMargin;
    UIColor *_lineColor;
    double _progressViewBottomSpace;
    id <WMMenuViewDelegate> _delegate;
    id <WMMenuViewDataSource> _dataSource;
    UIView *_leftView;
    UIView *_rightView;
    NSString *_fontName;
    NSString *_normalFontName;
    UIScrollView *_scrollView;
    double _speedFactor;
    WMMenuItem *_selItem;
    NSMutableArray *_frames;
    long long _selectIndex;
}

@property(nonatomic) long long selectIndex; // @synthesize selectIndex=_selectIndex;
@property(retain, nonatomic) NSMutableArray *frames; // @synthesize frames=_frames;
@property(nonatomic) __weak WMMenuItem *selItem; // @synthesize selItem=_selItem;
@property(nonatomic) _Bool showOnNavigationBar; // @synthesize showOnNavigationBar=_showOnNavigationBar;
@property(nonatomic) _Bool progressViewIsNaughty; // @synthesize progressViewIsNaughty=_progressViewIsNaughty;
@property(nonatomic) double speedFactor; // @synthesize speedFactor=_speedFactor;
@property(nonatomic) __weak UIScrollView *scrollView; // @synthesize scrollView=_scrollView;
@property(copy, nonatomic) NSString *normalFontName; // @synthesize normalFontName=_normalFontName;
@property(copy, nonatomic) NSString *fontName; // @synthesize fontName=_fontName;
@property(nonatomic) __weak UIView *rightView; // @synthesize rightView=_rightView;
@property(nonatomic) __weak UIView *leftView; // @synthesize leftView=_leftView;
@property(nonatomic) __weak id <WMMenuViewDataSource> dataSource; // @synthesize dataSource=_dataSource;
@property(nonatomic) __weak id <WMMenuViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) _Bool showDownLine; // @synthesize showDownLine=_showDownLine;
@property(nonatomic) double progressViewBottomSpace; // @synthesize progressViewBottomSpace=_progressViewBottomSpace;
@property(retain, nonatomic) UIColor *lineColor; // @synthesize lineColor=_lineColor;
@property(nonatomic) double contentMargin; // @synthesize contentMargin=_contentMargin;
@property(nonatomic) unsigned long long layoutMode; // @synthesize layoutMode=_layoutMode;
@property(nonatomic) unsigned long long style; // @synthesize style=_style;
@property(nonatomic) __weak WMProgressView *progressView; // @synthesize progressView=_progressView;
@property(retain, nonatomic) NSArray *progressWidths; // @synthesize progressWidths=_progressWidths;
@property(nonatomic) double progressHeight; // @synthesize progressHeight=_progressHeight;
- (void).cxx_destruct;
- (void)didPressedMenuItem:(id)arg1;
- (void)addProgressViewWithFrame:(struct CGRect)arg1 isTriangle:(_Bool)arg2 hasBorder:(_Bool)arg3 hollow:(_Bool)arg4 cornerRadius:(double)arg5;
- (double)itemMarginAtIndex:(long long)arg1;
- (void)calculateItemFrames;
- (void)addItems;
- (void)addScrollView;
- (void)deselectedItemsIfNeeded;
- (void)makeStyle;
- (void)addBadgeViewAtIndex:(long long)arg1;
- (void)addBadgeViews;
- (id)convertProgressWidthsToFrames;
- (void)resetBadgeFrame:(long long)arg1;
- (void)resetItemFrame:(long long)arg1;
- (struct CGRect)calculateProgressViewFrame;
- (void)resetFramesFromIndex:(long long)arg1;
- (void)resetFrames;
- (void)resetSelectionIfNeeded;
- (void)willMoveToSuperview:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1 IsSHowDownLine:(_Bool)arg2;
@property(readonly, nonatomic) long long titlesCount;
- (void)refreshContenOffset;
- (void)updateBadgeViewAtIndex:(long long)arg1;
- (void)updateAttributeTitle:(id)arg1 atIndex:(long long)arg2 andWidth:(_Bool)arg3;
- (void)updateTitle:(id)arg1 atIndex:(long long)arg2 andWidth:(_Bool)arg3;
- (void)selectItemAtIndex:(long long)arg1;
- (void)slideMenuAtProgress:(double)arg1;
- (void)reload;
- (id)itemAtIndex:(long long)arg1;
- (id)badgeViewAtIndex:(long long)arg1;
- (double)sizeForState:(unsigned long long)arg1 atIndex:(long long)arg2;
- (id)colorForState:(unsigned long long)arg1 atIndex:(long long)arg2;
- (id)menuView:(id)arg1 fontNameForState:(unsigned long long)arg2 atIndex:(long long)arg3;
@property(nonatomic) double progressViewCornerRadius; // @synthesize progressViewCornerRadius=_progressViewCornerRadius;
- (void)setFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

