//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UILabel.h"

@class CADisplayLink, UIColor;

@interface WMMenuItem : UILabel
{
    double _selectedRed;
    double _selectedGreen;
    double _selectedBlue;
    double _selectedAlpha;
    double _normalRed;
    double _normalGreen;
    double _normalBlue;
    double _normalAlpha;
    int _sign;
    double _gap;
    double _step;
    CADisplayLink *_link;
    _Bool _selected;
    double _rate;
    double _normalSize;
    double _selectedSize;
    UIColor *_normalColor;
    UIColor *_selectedColor;
    double _speedFactor;
    id <WMMenuItemDelegate> _delegate;
}

@property(readonly, nonatomic) _Bool selected; // @synthesize selected=_selected;
@property(nonatomic) __weak id <WMMenuItemDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) double speedFactor; // @synthesize speedFactor=_speedFactor;
@property(retain, nonatomic) UIColor *selectedColor; // @synthesize selectedColor=_selectedColor;
@property(retain, nonatomic) UIColor *normalColor; // @synthesize normalColor=_normalColor;
@property(nonatomic) double selectedSize; // @synthesize selectedSize=_selectedSize;
@property(nonatomic) double normalSize; // @synthesize normalSize=_normalSize;
@property(nonatomic) double rate; // @synthesize rate=_rate;
- (void).cxx_destruct;
- (void)touchUpInside:(id)arg1;
- (void)rateChange;
- (void)setSelected:(_Bool)arg1 withAnimation:(_Bool)arg2;
- (void)setupGestureRecognizer;
- (id)initWithFrame:(struct CGRect)arg1;

@end

