//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class ZFHttpRequest;

@protocol ZFDownloadDelegate <NSObject>

@optional
- (void)allowNextRequest;
- (void)finishedDownload:(ZFHttpRequest *)arg1;
- (void)updateCellProgress:(ZFHttpRequest *)arg1;
- (void)startDownload:(ZFHttpRequest *)arg1;
@end

