//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDate, NSMutableData, NSString, UIImage;

@interface ZFFileModel : NSObject
{
    _Bool _isFirstReceived;
    _Bool _error;
    NSString *_fileName;
    NSString *_fileSize;
    NSString *_fileType;
    NSString *_fileReceivedSize;
    NSMutableData *_fileReceivedData;
    NSString *_fileURL;
    NSString *_time;
    NSString *_tempPath;
    NSString *_speed;
    NSDate *_startTime;
    NSString *_remainingTime;
    NSString *_playId;
    long long _downloadState;
    NSString *_MD5;
    UIImage *_fileimage;
    NSString *_seeTime;
    NSString *_totalTime;
    NSString *_totalCount;
}

@property(copy, nonatomic) NSString *totalCount; // @synthesize totalCount=_totalCount;
@property(copy, nonatomic) NSString *totalTime; // @synthesize totalTime=_totalTime;
@property(copy, nonatomic) NSString *seeTime; // @synthesize seeTime=_seeTime;
@property(retain, nonatomic) UIImage *fileimage; // @synthesize fileimage=_fileimage;
@property(copy, nonatomic) NSString *MD5; // @synthesize MD5=_MD5;
@property(nonatomic) _Bool error; // @synthesize error=_error;
@property(nonatomic) long long downloadState; // @synthesize downloadState=_downloadState;
@property(copy, nonatomic) NSString *playId; // @synthesize playId=_playId;
@property(copy, nonatomic) NSString *remainingTime; // @synthesize remainingTime=_remainingTime;
@property(retain, nonatomic) NSDate *startTime; // @synthesize startTime=_startTime;
@property(copy, nonatomic) NSString *speed; // @synthesize speed=_speed;
@property(copy, nonatomic) NSString *tempPath; // @synthesize tempPath=_tempPath;
@property(copy, nonatomic) NSString *time; // @synthesize time=_time;
@property(copy, nonatomic) NSString *fileURL; // @synthesize fileURL=_fileURL;
@property(retain, nonatomic) NSMutableData *fileReceivedData; // @synthesize fileReceivedData=_fileReceivedData;
@property(copy, nonatomic) NSString *fileReceivedSize; // @synthesize fileReceivedSize=_fileReceivedSize;
@property(nonatomic) _Bool isFirstReceived; // @synthesize isFirstReceived=_isFirstReceived;
@property(copy, nonatomic) NSString *fileType; // @synthesize fileType=_fileType;
@property(copy, nonatomic) NSString *fileSize; // @synthesize fileSize=_fileSize;
@property(copy, nonatomic) NSString *fileName; // @synthesize fileName=_fileName;
- (void).cxx_destruct;
- (long long)compareZFFileModel:(id)arg1;

@end

