//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@interface ZFFloatView : UIView
{
    UIView *_parentView;
    struct UIEdgeInsets _safeInsets;
}

@property(nonatomic) struct UIEdgeInsets safeInsets; // @synthesize safeInsets=_safeInsets;
@property(nonatomic) __weak UIView *parentView; // @synthesize parentView=_parentView;
- (void).cxx_destruct;
- (void)doMoveAction:(id)arg1;
- (void)initilize;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

