//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSURL, ZFHttpRequest;

@protocol ZFHttpRequestDelegate <NSObject>
- (void)requestFinished:(ZFHttpRequest *)arg1;
- (void)request:(ZFHttpRequest *)arg1 didReceiveBytes:(long long)arg2;
- (void)request:(ZFHttpRequest *)arg1 didReceiveResponseHeaders:(NSDictionary *)arg2;
- (void)requestStarted:(ZFHttpRequest *)arg1;
- (void)requestFailed:(ZFHttpRequest *)arg1;

@optional
- (void)request:(ZFHttpRequest *)arg1 willRedirectToURL:(NSURL *)arg2;
@end

