//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MahuaVideoModel, NSString, UITextField;

@protocol ZFPlayerControlViewDelagate <NSObject>

@optional
- (void)zf_failedPlayerBeginToPlay;
- (void)zf_textFieldDidChange:(UITextField *)arg1;
- (_Bool)zf_textField:(UITextField *)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(NSString *)arg3;
- (_Bool)zf_textFieldShouldBeginEditing:(UITextField *)arg1;
- (_Bool)zf_textFieldShouldReturn:(UITextField *)arg1;
- (void)zf_goGuessULikeIt:(long long)arg1;
- (void)zf_goSharePic;
- (void)zf_goShareBack:(NSString *)arg1;
- (void)zf_playerResetFrameAction;
- (void)zf_collectTheVideo:(_Bool)arg1;
- (void)zf_shareBack:(long long)arg1;
- (void)zf_sliderChanging:(float)arg1;
- (void)zf_sliderShouldBegin;
- (void)zf_barrageSettingSpeed:(float)arg1;
- (void)zf_barrageSettingArea:(float)arg1;
- (void)zf_barrageSettingText:(float)arg1;
- (void)zf_barrageSettingAlpha:(float)arg1;
- (void)zf_restartRender;
- (void)zf_showMsg:(NSString *)arg1;
- (void)zf_feedBack;
- (void)zf_showFirstEditing;
- (void)zf_buyBlueLight;
- (void)zf_get1080URL:(MahuaVideoModel *)arg1;
- (void)zf_earnMoney;
- (void)zf_fullScreenNotLogin;
- (void)zf_getDetailVideoURL;
- (void)zf_airShowUnKnow;
- (void)zf_airPlayEnd;
- (void)zf_airPlayChangeresolution;
- (void)stopGifRecord;
- (void)beginGifRecord;
- (void)zf_airPlayChangeDevice;
- (void)zf_setPlayerRate:(NSString *)arg1;
- (void)zf_airPlayAction;
- (void)zf_repeatToTimePlayVideo:(double)arg1;
- (void)zf_zearoPlayVideo;
- (void)zf_repeatPlayVideo;
- (void)zf_playFailAction;
- (void)zf_collectionCellClickWithVideoModel:(id)arg1 videoPageModel:(id)arg2;
- (void)zf_selectedVideoPageClick:(id)arg1;
- (void)zf_orientationDidChange:(_Bool)arg1;
- (void)zf_orientationWillChange:(_Bool)arg1;
- (void)zf_startBuffer:(_Bool)arg1;
- (void)zf_exitApplicationAfterTime:(double)arg1;
- (void)zf_enterFullScreen:(_Bool)arg1 animated:(_Bool)arg2;
- (void)downLoadPop;
- (void)zf_backAction;
- (void)zf_shareAction;
- (void)zf_barrgeAction:(_Bool)arg1;
- (void)zf_playAction:(_Bool)arg1;
- (void)zf_playAction:(_Bool)arg1 isShowAD:(_Bool)arg2;
- (void)zf_playerPreviousAction;
- (void)zf_playerNextAction;
- (void)zf_fastBackSecond:(long long)arg1;
- (void)zf_fastForwardSecond:(long long)arg1;
- (void)zf_changeResolution:(NSString *)arg1 andSortNum:(long long)arg2;
- (void)zf_changeResolution:(id)arg1;
@end

