//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSURL, UIScrollView, UISlider, UIView, UIView<ZFPlayerMediaControl>, ZFOrientationObserver, ZFPlayerGestureControl, ZFPlayerNotification;

@interface ZFPlayerController : NSObject
{
    UIView *_containerView;
    id <ZFPlayerMediaPlayback> _currentPlayerManager;
    UIView<ZFPlayerMediaControl> *_controlView;
    ZFPlayerNotification *_notification;
    UIScrollView *_scrollView;
    UISlider *_volumeViewSlider;
    long long _containerViewTag;
}

+ (id)playerWithScrollView:(id)arg1 playerManager:(id)arg2 containerViewTag:(long long)arg3;
+ (id)playerWithPlayerManager:(id)arg1 containerView:(id)arg2;
@property(nonatomic) long long containerViewTag; // @synthesize containerViewTag=_containerViewTag;
@property(retain, nonatomic) UISlider *volumeViewSlider; // @synthesize volumeViewSlider=_volumeViewSlider;
@property(nonatomic) __weak UIScrollView *scrollView; // @synthesize scrollView=_scrollView;
@property(retain, nonatomic) ZFPlayerNotification *notification; // @synthesize notification=_notification;
@property(retain, nonatomic) UIView<ZFPlayerMediaControl> *controlView; // @synthesize controlView=_controlView;
@property(retain, nonatomic) id <ZFPlayerMediaPlayback> currentPlayerManager; // @synthesize currentPlayerManager=_currentPlayerManager;
@property(retain, nonatomic) UIView *containerView; // @synthesize containerView=_containerView;
- (void).cxx_destruct;
- (void)layoutPlayerSubViews;
- (void)playerManagerCallbcak;
- (id)initWithScrollView:(id)arg1 playerManager:(id)arg2 containerViewTag:(long long)arg3;
- (id)initWithPlayerManager:(id)arg1 containerView:(id)arg2;
- (void)dealloc;
- (void)configureVolume;
- (id)init;
- (void)seekToTime:(double)arg1 completionHandler:(CDUnknownBlockType)arg2;
@property(readonly, nonatomic) float bufferProgress;
@property(readonly, nonatomic) float progress;
@property(readonly, nonatomic) double bufferTime;
@property(readonly, nonatomic) double totalTime;
@property(readonly, nonatomic) double currentTime;
@property(nonatomic, getter=isViewControllerDisappear) _Bool viewControllerDisappear;
@property(nonatomic) long long currentPlayIndex;
@property(copy, nonatomic) CDUnknownBlockType playerPlayFailed;
@property(copy, nonatomic) CDUnknownBlockType playerDidToEnd;
@property(copy, nonatomic) CDUnknownBlockType playerLoadStatChanged;
@property(copy, nonatomic) CDUnknownBlockType playerPlayStatChanged;
@property(copy, nonatomic) CDUnknownBlockType playerBufferTimeChanged;
@property(copy, nonatomic) CDUnknownBlockType playerPlayTimeChanged;
@property(copy, nonatomic) CDUnknownBlockType playerPrepareToPlay;
@property(nonatomic) _Bool pauseWhenAppResignActive;
@property(nonatomic, getter=isPauseByEvent) _Bool pauseByEvent;
@property(nonatomic) float brightness;
- (void)setLastVolumeValue:(float)arg1;
@property(nonatomic, getter=isMuted) _Bool muted;
@property(nonatomic) float volume;
@property(copy, nonatomic) NSArray *assetURLs;
@property(retain, nonatomic) NSURL *assetURL;
- (_Bool)isPlaying;
- (unsigned long long)playState;
- (float)lastVolumeValue;
@property(readonly, nonatomic) _Bool isFirstAssetURL;
@property(readonly, nonatomic) _Bool isLastAssetURL;
- (void)playTheIndex:(long long)arg1;
- (void)playThePrevious;
- (void)playTheNext;
- (void)replaceCurrentPlayerManager:(id)arg1;
- (void)stop;
@property(nonatomic) _Bool notSmall;
@property(nonatomic) _Bool allowOrentitaionRotation;
@property(nonatomic, getter=isLockedScreen) _Bool lockedScreen;
@property(nonatomic, getter=isStatusBarHidden) _Bool statusBarHidden;
@property(copy, nonatomic) CDUnknownBlockType orientationDidChanged;
@property(copy, nonatomic) CDUnknownBlockType orientationWillChange;
@property(readonly, nonatomic) _Bool shouldAutorotate;
@property(readonly, nonatomic) long long currentOrientation;
@property(readonly, nonatomic) _Bool isFullScreen;
@property(readonly, nonatomic) ZFOrientationObserver *orientationObserver;
- (_Bool)isNeedAdaptiveiOS8Rotation;
- (void)enterFullScreen:(_Bool)arg1 animated:(_Bool)arg2;
- (void)enterPortraitFullScreen:(_Bool)arg1 animated:(_Bool)arg2;
- (void)enterLandscapeFullScreen:(long long)arg1 animated:(_Bool)arg2;
- (void)removeDeviceOrientationObserver;
- (void)addDeviceOrientationObserver;
@property(nonatomic) unsigned long long disableGestureTypes;
@property(readonly, nonatomic) ZFPlayerGestureControl *gestureControl;

@end

