//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface ZFPlayerLogManager : NSObject
{
}

+ (void)logWithFunction:(const char *)arg1 lineNumber:(int)arg2 formatString:(id)arg3;
+ (_Bool)getLogEnable;
+ (void)setLogEnable:(_Bool)arg1;

@end

