//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ZFPlayerController.h"

@class NSArray, NSIndexPath, UIScrollView, ZFFloatView;

@interface ZFPlayerController (ZFPlayerScrollView)
+ (void)load;
- (void)stopCurrentPlayingCell;
- (void)playTheIndexPath:(id)arg1 assetURL:(id)arg2 scrollToTop:(_Bool)arg3;
- (void)playTheIndexPath:(id)arg1 scrollToTop:(_Bool)arg2;
- (void)playTheIndexPath:(id)arg1 scrollToTop:(_Bool)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (CDUnknownBlockType)zf_scrollViewDidStopScrollCallback;
@property(copy, nonatomic) CDUnknownBlockType zf_playerDidDisappearInScrollView;
@property(copy, nonatomic) CDUnknownBlockType zf_playerWillAppearInScrollView;
@property(copy, nonatomic) CDUnknownBlockType zf_playerWillDisappearInScrollView;
@property(copy, nonatomic) CDUnknownBlockType zf_playerDidAppearInScrollView;
@property(copy, nonatomic) CDUnknownBlockType zf_playerDisappearingInScrollView;
@property(copy, nonatomic) CDUnknownBlockType zf_playerAppearingInScrollView;
@property(nonatomic) double playerApperaPercent;
@property(nonatomic) double playerDisapperaPercent;
@property(nonatomic) _Bool shouldAutoPlay;
@property(copy, nonatomic) NSArray *sectionAssetURLs;
@property(readonly, nonatomic) NSIndexPath *playingIndexPath;
@property(readonly, nonatomic) _Bool isSmallFloatViewShow;
@property(readonly, nonatomic) ZFFloatView *smallFloatView;
@property(readonly, nonatomic) long long containerViewTag;
@property(nonatomic) _Bool stopWhileNotVisible;
@property(nonatomic, getter=isWWANAutoPlay) _Bool WWANAutoPlay;
@property(readonly, nonatomic) UIScrollView *scrollView;
- (void)setZf_scrollViewDidStopScrollCallback:(CDUnknownBlockType)arg1;
- (void)setIsSmallFloatViewShow:(_Bool)arg1;
- (void)setSmallFloatView:(id)arg1;
- (void)setPlayingIndexPath:(id)arg1;
- (void)setContainerViewTag:(long long)arg1;
- (void)setScrollView:(id)arg1;
- (void)addPlayerViewToKeyWindow;
- (void)addPlayerViewToCell;
- (void)zf_dealloc;
@end

