//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIButton;

@interface ZFSmallFloatControlView : UIView
{
    CDUnknownBlockType _closeClickCallback;
    UIButton *_closeBtn;
}

@property(retain, nonatomic) UIButton *closeBtn; // @synthesize closeBtn=_closeBtn;
@property(copy, nonatomic) CDUnknownBlockType closeClickCallback; // @synthesize closeClickCallback=_closeClickCallback;
- (void).cxx_destruct;
- (void)closeBtnClick:(id)arg1;
- (void)hideControlView;
- (void)showControlView;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

