//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSTimer, UILabel, ZFLoadingView, ZFNetworkSpeedMonitor;

@interface ZFSpeedLoadingView : UIView
{
    _Bool _allBlack;
    _Bool _isAnimating;
    _Bool _isPor;
    _Bool _isFirst;
    _Bool _doAni;
    ZFLoadingView *_loadingView;
    UILabel *_firstTextLabel;
    UILabel *_speedTextLabel;
    CDUnknownBlockType _showNextVideoClick;
    ZFNetworkSpeedMonitor *_speedMonitor;
    UIView *_spotView;
    UIView *_firstImage;
    UIView *_secondImage;
    UIView *_thirdImage;
    NSTimer *_timer;
    UIView *_smallView;
    UIView *_coverView;
    double _countNum;
    struct CGRect _smallFrame;
}

@property(nonatomic) double countNum; // @synthesize countNum=_countNum;
@property(retain, nonatomic) UIView *coverView; // @synthesize coverView=_coverView;
@property(nonatomic) _Bool doAni; // @synthesize doAni=_doAni;
@property(nonatomic) _Bool isFirst; // @synthesize isFirst=_isFirst;
@property(nonatomic) struct CGRect smallFrame; // @synthesize smallFrame=_smallFrame;
@property(retain, nonatomic) UIView *smallView; // @synthesize smallView=_smallView;
@property(retain, nonatomic) NSTimer *timer; // @synthesize timer=_timer;
@property(retain, nonatomic) UIView *thirdImage; // @synthesize thirdImage=_thirdImage;
@property(retain, nonatomic) UIView *secondImage; // @synthesize secondImage=_secondImage;
@property(retain, nonatomic) UIView *firstImage; // @synthesize firstImage=_firstImage;
@property(retain, nonatomic) UIView *spotView; // @synthesize spotView=_spotView;
@property(nonatomic) _Bool isPor; // @synthesize isPor=_isPor;
@property(retain, nonatomic) ZFNetworkSpeedMonitor *speedMonitor; // @synthesize speedMonitor=_speedMonitor;
@property(copy, nonatomic) CDUnknownBlockType showNextVideoClick; // @synthesize showNextVideoClick=_showNextVideoClick;
@property(nonatomic) _Bool isAnimating; // @synthesize isAnimating=_isAnimating;
@property(retain, nonatomic) UILabel *speedTextLabel; // @synthesize speedTextLabel=_speedTextLabel;
@property(retain, nonatomic) UILabel *firstTextLabel; // @synthesize firstTextLabel=_firstTextLabel;
@property(retain, nonatomic) ZFLoadingView *loadingView; // @synthesize loadingView=_loadingView;
@property(nonatomic) _Bool allBlack; // @synthesize allBlack=_allBlack;
- (void).cxx_destruct;
- (void)invalidateTimer;
- (void)stopAnimating;
- (void)stopSpotViewAnimating;
- (void)doSomething:(id)arg1 WithNumber:(double)arg2;
- (void)doAnimating;
- (void)goDoAnimating;
- (void)startAnimatingWithPorOrLan:(_Bool)arg1 andIsFirst:(_Bool)arg2;
- (void)startAnimating;
- (void)networkSpeedChanged:(id)arg1;
- (void)reloadViews;
- (void)layoutSubviews;
- (void)dealloc;
- (void)initialize;
- (id)initWithFrame:(struct CGRect)arg1 withSmallFrame:(struct CGRect)arg2;

@end

