//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class MPVolumeView, UIImageView, UIProgressView;

@interface ZFVolumeBrightnessView : UIView
{
    long long _volumeBrightnessType;
    UIProgressView *_progressView;
    UIImageView *_iconImageView;
    MPVolumeView *_volumeView;
}

@property(retain, nonatomic) MPVolumeView *volumeView; // @synthesize volumeView=_volumeView;
@property(retain, nonatomic) UIImageView *iconImageView; // @synthesize iconImageView=_iconImageView;
@property(retain, nonatomic) UIProgressView *progressView; // @synthesize progressView=_progressView;
@property(nonatomic) long long volumeBrightnessType; // @synthesize volumeBrightnessType=_volumeBrightnessType;
- (void).cxx_destruct;
- (void)updateProgress:(double)arg1 withVolumeBrightnessType:(long long)arg2;
- (void)removeSystemVolumeView;
- (void)addSystemVolumeView;
- (void)hideTipView;
- (void)layoutSubviews;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

