//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "UIScrollViewDelegate.h"

@class FLAnimatedImageView, NSArray, NSMutableArray, NSOperationQueue, NSString, NSTimer, UIImageView, UILabel, UIScrollView, ZPPageControlView;

@interface ZPCarouselView : UIView <UIScrollViewDelegate>
{
    _Bool _autoCache;
    int _changeMode;
    int _pagePosition;
    long long _contentMode;
    NSArray *_imageArray;
    NSArray *_describeArray;
    double _time;
    CDUnknownBlockType _imageClickBlock;
    id <ZPCarouselViewDelegate> _delegate;
    NSMutableArray *_images;
    UILabel *_describeLabel;
    UIScrollView *_scrollView;
    ZPPageControlView *_pageControl;
    FLAnimatedImageView *_currImageView;
    FLAnimatedImageView *_otherImageView;
    long long _currIndex;
    long long _nextIndex;
    NSTimer *_timer;
    NSOperationQueue *_queue;
    UIImageView *_shadow;
    struct CGSize _pageImageSize;
}

+ (void)clearDiskCache;
+ (void)initialize;
@property(retain, nonatomic) UIImageView *shadow; // @synthesize shadow=_shadow;
@property(retain, nonatomic) NSOperationQueue *queue; // @synthesize queue=_queue;
@property(retain, nonatomic) NSTimer *timer; // @synthesize timer=_timer;
@property(nonatomic) struct CGSize pageImageSize; // @synthesize pageImageSize=_pageImageSize;
@property(nonatomic) long long nextIndex; // @synthesize nextIndex=_nextIndex;
@property(nonatomic) long long currIndex; // @synthesize currIndex=_currIndex;
@property(retain, nonatomic) FLAnimatedImageView *otherImageView; // @synthesize otherImageView=_otherImageView;
@property(retain, nonatomic) FLAnimatedImageView *currImageView; // @synthesize currImageView=_currImageView;
@property(retain, nonatomic) ZPPageControlView *pageControl; // @synthesize pageControl=_pageControl;
@property(retain, nonatomic) UIScrollView *scrollView; // @synthesize scrollView=_scrollView;
@property(retain, nonatomic) UILabel *describeLabel; // @synthesize describeLabel=_describeLabel;
@property(retain, nonatomic) NSMutableArray *images; // @synthesize images=_images;
@property(nonatomic) __weak id <ZPCarouselViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(copy, nonatomic) CDUnknownBlockType imageClickBlock; // @synthesize imageClickBlock=_imageClickBlock;
@property(nonatomic) _Bool autoCache; // @synthesize autoCache=_autoCache;
@property(nonatomic) double time; // @synthesize time=_time;
@property(retain, nonatomic) NSArray *describeArray; // @synthesize describeArray=_describeArray;
@property(retain, nonatomic) NSArray *imageArray; // @synthesize imageArray=_imageArray;
@property(nonatomic) int pagePosition; // @synthesize pagePosition=_pagePosition;
@property(nonatomic) long long contentMode; // @synthesize contentMode=_contentMode;
@property(nonatomic) int changeMode; // @synthesize changeMode=_changeMode;
- (void).cxx_destruct;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)changeToNext;
- (void)scrollViewDidScroll:(id)arg1;
- (void)changeCurrentPageWithOffset:(double)arg1;
- (void)downloadImages:(int)arg1;
- (void)imageClick;
- (void)layoutSubviews;
- (void)nextPage;
- (void)stopTimer;
- (void)startTimer;
- (void)setPageColor:(id)arg1 andCurrentPageColor:(id)arg2;
- (void)setPageImage:(id)arg1 andCurrentPageImage:(id)arg2;
- (void)setDescribeTextColor:(id)arg1 font:(id)arg2 bgColor:(id)arg3;
- (void)setScrollViewContentSize;
- (double)width;
- (double)height;
- (void)initSubView;
- (void)awakeFromNib;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

